/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 6
#define FLOWC_N_LANES 2


static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "dronet", 0, 0, "qnn_graph", "dronet_full", "dsp", 6, 0.000000, 0.645000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 0, 24, 0, 23 },
    { 1, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.000000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 2, "dronet", 1, 0, "qnn_graph", "dronet_full", "dsp", 6, 8.000000, 0.645000, 0, NULL, 0, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 0, 24, 0, 23 },
    { 3, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 8.000000, 0.107000, 0, NULL, 1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 4, "dronet", 2, 0, "qnn_graph", "dronet_full", "dsp", 6, 16.000000, 0.645000, 0, NULL, 2, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 0, 24, 0, 23 },
    { 5, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 16.000000, 0.107000, 0, NULL, 3, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "dsp|dronet",
    "cpu|mlp_control",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 6, 5 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 2000 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 40 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "6",
    "4,5",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
