"""NPU program emission for simulator and baremetal.

Converts a ``ModelProgram`` into:
1. NPU simulator ``Program`` objects (for ``third_party/npu_model/``)
2. NPU-specific ``npu_driver.c`` implementation (for baremetal)

The simulator path produces Python ``Program`` objects with instruction
lists and memory regions.  The baremetal path produces C source code
with MMIO register writes and DMA channel management.
"""

from __future__ import annotations

import structlog

from compgen.runtime.program_builder import ModelProgram
from compgen.targets.backends.npu.memory_map import (
    NPU_DMA_CHANNELS,
)

logger = structlog.get_logger()


class NpuProgramEmitter:
    """Emit NPU programs for the simulator or baremetal deployment.

    This is the NPU extension point's implementation of program emission.
    It translates ``ModelProgram`` kernel sequences into NPU ISA
    instruction sequences.
    """

    def emit_baremetal_driver(self, program: ModelProgram) -> str:
        """Generate NPU-specific npu_driver.c implementation.

        Produces C code with:
        - MMIO register definitions for DMA and kernel dispatch
        - DMA channel management (8 channels)
        - Kernel dispatch via instruction memory loading
        - Synchronization via status register polling

        Args:
            program: The assembled model program.

        Returns:
            C source code string for npu_driver.c.
        """
        patterns = sorted(set(k.pattern_id for k in program.device_kernels))

        dispatch_cases = []
        for pattern in patterns:
            dispatch_cases.append(
                f"        case KERNEL_{pattern.upper()}:\n"
                f"            /* Load {pattern} kernel to IMEM and execute */\n"
                f"            npu_write_reg(NPU_REG_KERNEL_ID, KERNEL_{pattern.upper()});\n"
                f"            npu_write_reg(NPU_REG_INPUT_ADDR, input_addr);\n"
                f"            npu_write_reg(NPU_REG_WEIGHT_ADDR, weight_addr);\n"
                f"            npu_write_reg(NPU_REG_OUTPUT_ADDR, output_addr);\n"
                f"            npu_write_reg(NPU_REG_CONTROL, NPU_CTRL_START);\n"
                f"            break;"
            )

        cases_body = "\n".join(dispatch_cases)

        return f"""\
/*
 * NPU driver for {program.name}
 * Auto-generated by CompGen — NPU-specific implementation
 *
 * Hardware: 32x32 MXU (FP8→BF16), BF16 VPU, 1MiB VMEM, 8 DMA channels
 * ISA: See third_party/npu_model/npu_spec/06_instruction_set/
 */

#include "npu_driver.h"
#include <string.h>

/* NPU MMIO register base (from hardware spec) */
#define NPU_MMIO_BASE       0x10000000

/* Register offsets */
#define NPU_REG_CONTROL     (NPU_MMIO_BASE + 0x00)
#define NPU_REG_STATUS      (NPU_MMIO_BASE + 0x04)
#define NPU_REG_KERNEL_ID   (NPU_MMIO_BASE + 0x08)
#define NPU_REG_INPUT_ADDR  (NPU_MMIO_BASE + 0x0C)
#define NPU_REG_WEIGHT_ADDR (NPU_MMIO_BASE + 0x10)
#define NPU_REG_OUTPUT_ADDR (NPU_MMIO_BASE + 0x14)

/* DMA register offsets (per channel) */
#define NPU_DMA_BASE        0x10001000
#define NPU_DMA_CHAN_SIZE    0x20
#define NPU_DMA_SRC(ch)     (NPU_DMA_BASE + (ch) * NPU_DMA_CHAN_SIZE + 0x00)
#define NPU_DMA_DST(ch)     (NPU_DMA_BASE + (ch) * NPU_DMA_CHAN_SIZE + 0x04)
#define NPU_DMA_LEN(ch)     (NPU_DMA_BASE + (ch) * NPU_DMA_CHAN_SIZE + 0x08)
#define NPU_DMA_CTRL(ch)    (NPU_DMA_BASE + (ch) * NPU_DMA_CHAN_SIZE + 0x0C)
#define NPU_DMA_STATUS(ch)  (NPU_DMA_BASE + (ch) * NPU_DMA_CHAN_SIZE + 0x10)

/* Control bits */
#define NPU_CTRL_START      0x01
#define NPU_STATUS_BUSY     0x01
#define NPU_DMA_CTRL_START  0x01
#define NPU_DMA_STATUS_DONE 0x01

static inline void npu_write_reg(uint32_t addr, uint32_t value) {{
    *(volatile uint32_t *)(uintptr_t)addr = value;
}}

static inline uint32_t npu_read_reg(uint32_t addr) {{
    return *(volatile uint32_t *)(uintptr_t)addr;
}}

static int dma_next_channel = 0;

void npu_init(void) {{
    /* Reset all DMA channels */
    for (int ch = 0; ch < {NPU_DMA_CHANNELS}; ch++) {{
        npu_write_reg(NPU_DMA_CTRL(ch), 0);
    }}
    dma_next_channel = 0;
}}

void npu_dma_write(uint32_t dst_addr, const void *src, size_t size) {{
    int ch = dma_next_channel++ % {NPU_DMA_CHANNELS};
    npu_write_reg(NPU_DMA_SRC(ch), (uint32_t)(uintptr_t)src);
    npu_write_reg(NPU_DMA_DST(ch), dst_addr);
    npu_write_reg(NPU_DMA_LEN(ch), (uint32_t)size);
    npu_write_reg(NPU_DMA_CTRL(ch), NPU_DMA_CTRL_START);
}}

void npu_dma_read(void *dst, uint32_t src_addr, size_t size) {{
    int ch = dma_next_channel++ % {NPU_DMA_CHANNELS};
    npu_write_reg(NPU_DMA_SRC(ch), src_addr);
    npu_write_reg(NPU_DMA_DST(ch), (uint32_t)(uintptr_t)dst);
    npu_write_reg(NPU_DMA_LEN(ch), (uint32_t)size);
    npu_write_reg(NPU_DMA_CTRL(ch), NPU_DMA_CTRL_START);
}}

void npu_dma_wait(void) {{
    for (int ch = 0; ch < {NPU_DMA_CHANNELS}; ch++) {{
        while (!(npu_read_reg(NPU_DMA_STATUS(ch)) & NPU_DMA_STATUS_DONE)) {{
            /* spin */
        }}
    }}
}}

void npu_dispatch_kernel(kernel_id_t kernel,
                         uint32_t input_addr,
                         uint32_t weight_addr,
                         uint32_t output_addr) {{
    switch (kernel) {{
{cases_body}
        default:
            break;
    }}
}}

void npu_wait(void) {{
    while (npu_read_reg(NPU_REG_STATUS) & NPU_STATUS_BUSY) {{
        /* spin until NPU completes */
    }}
}}

void npu_shutdown(void) {{
    npu_write_reg(NPU_REG_CONTROL, 0);
}}
"""


__all__ = ["NpuProgramEmitter"]
