/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 23
#define FLOWC_N_LANES 12

static const int flowc_e4_deps[] = { 0, 2 };
static const int flowc_e7_deps[] = { 5 };
static const int flowc_e11_deps[] = { 8, 9 };
static const int flowc_e14_deps[] = { 1 };
static const int flowc_e19_deps[] = { 18, 17 };
static const int flowc_e21_deps[] = { 12 };
static const int flowc_e22_deps[] = { 15 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 0.000000, 0.459000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 1, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 0.000000, 13.909000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 1, 103, 0, 102 },
    { 2, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 0.000000, 0.014000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 2, 2, 6, 7 },
    { 3, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.014000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 4, "fused_split", 0, 2, "qnn_graph", "fused_tail", "cpu", 5, 0.459000, 0.354000, 2, flowc_e4_deps, 3, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 2, 10, 4, 15 },
    { 5, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 0.459000, 13.267000, 0, NULL, 0, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 6, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 7.000000, 0.107000, 0, NULL, 4, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 7, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 13.726000, 15.377000, 1, flowc_e7_deps, 5, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 4, 146, 103, 248 },
    { 8, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 14.000000, 0.931000, 0, NULL, 1, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 5, 4, 0, 3 },
    { 9, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 14.000000, 0.014000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 2, 2, 6, 7 },
    { 10, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 14.824000, 0.107000, 0, NULL, 9, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 11, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 14.931000, 0.354000, 2, flowc_e11_deps, 10, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 2, 10, 4, 15 },
    { 12, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 14.931000, 13.909000, 0, NULL, 1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 6, 103, 0, 102 },
    { 13, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 21.000000, 0.107000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 14, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "cpu", 5, 21.107000, 39.464000, 1, flowc_e14_deps, 13, "CPU", "libQnnCpu.so", "ctx_yolov8n_head__Cpu.bin", "yolov8n_HTA_split_seg101", 0, 7, 146, 103, 248 },
    { 15, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 28.840000, 13.909000, 0, NULL, 8, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 8, 103, 0, 102 },
    { 16, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 29.103000, 0.589000, 0, NULL, 5, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 9, 7, 0, 6 },
    { 17, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 29.692000, 0.392000, 0, NULL, 16, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 18, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 30.238000, 0.459000, 0, NULL, 17, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 19, "fused_split", 2, 2, "qnn_graph", "fused_tail", "dsp", 6, 30.697000, 4.303000, 2, flowc_e19_deps, 17, "DSP", "libQnnDsp.so", "ctx_fused_tail_from_conv__Dsp.bin", "fused_tail_from_conv", 1, 0, 10, 4, 15 },
    { 20, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 35.000000, 0.589000, 0, NULL, 18, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 9, 7, 0, 6 },
    { 21, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 35.589000, 15.377000, 1, flowc_e21_deps, 20, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 10, 146, 103, 248 },
    { 22, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 50.966000, 15.377000, 1, flowc_e22_deps, 20, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 11, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "dsp|fused_split",
    "hta|yolov8n_b",
    "cpu|fused_split",
    "cpu|mlp_control",
    "dsp|yolov8n_a",
    "hta|fused_split",
    "hta|yolov8n_c",
    "cpu|yolov8n_b",
    "hta|yolov8n_d",
    "dsp|mlp_control",
    "dsp|yolov8n_c",
    "dsp|yolov8n_d",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 6, 7, 5, 4, 6, 7, 7, 5, 7, 6, 6, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 114, 200, 114, 1544, 200, 200, 200, 2000, 200, 200, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 0, 40, 40, 0, 0, 0, 40, 0, 0, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "6",
    "7",
    "4,5",
    "4,5",
    "6",
    "7",
    "7",
    "4,5",
    "7",
    "6",
    "6",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
