"""Recipe IR Family F: Provenance/Feedback operations.

These record where a choice came from and what happened to it.
Enables lineage, auditing, replay, and promotion tracking.
"""

from __future__ import annotations

from xdsl.dialects.builtin import ArrayAttr, IntegerAttr, StringAttr, SymbolRefAttr
from xdsl.irdl import (
    IRDLOperation,
    irdl_op_definition,
    opt_prop_def,
    prop_def,
    traits_def,
)
from xdsl.traits import Pure

from compgen.ir.recipe.attrs import CostAttr


@irdl_op_definition
class FromAgentOp(IRDLOperation):
    """Records that a candidate was generated by an LLM agent."""

    name = "recipe.from_agent"

    agent_id = prop_def(StringAttr)
    iteration = prop_def(IntegerAttr)
    reasoning = opt_prop_def(StringAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class FromEqsatOp(IRDLOperation):
    """Records that a candidate came from equality saturation."""

    name = "recipe.from_eqsat"

    rule_name = prop_def(StringAttr)
    eclass_count = opt_prop_def(IntegerAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class FromTemplateOp(IRDLOperation):
    """Records that a candidate came from a deterministic template."""

    name = "recipe.from_template"

    template_name = prop_def(StringAttr)
    template_version = opt_prop_def(IntegerAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class FeedbackOp(IRDLOperation):
    """Records verification/profiling feedback for a candidate.

    Outcomes: "passed", "failed", "timeout", "error".
    """

    name = "recipe.feedback"

    candidate_ref = prop_def(SymbolRefAttr)
    outcome = prop_def(StringAttr)
    measured_cost = opt_prop_def(CostAttr)
    message = opt_prop_def(StringAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class RejectOp(IRDLOperation):
    """Records that a candidate was rejected."""

    name = "recipe.reject"

    candidate_ref = prop_def(SymbolRefAttr)
    reason = prop_def(StringAttr)
    feedback_ref = opt_prop_def(SymbolRefAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class PromoteOp(IRDLOperation):
    """Records that a candidate was promoted into the recipe library."""

    name = "recipe.promote"

    candidate_ref = prop_def(SymbolRefAttr)
    recipe_key = prop_def(StringAttr)
    version = prop_def(IntegerAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class LineageOp(IRDLOperation):
    """Full lineage chain for a candidate.

    Tracks parent candidates and generation number for evolutionary
    search and audit trails.
    """

    name = "recipe.lineage"

    candidate_ref = prop_def(SymbolRefAttr)
    parent_refs = prop_def(ArrayAttr)  # ArrayAttr of SymbolRefAttr
    generation = prop_def(IntegerAttr)

    traits = traits_def(Pure())


__all__ = [
    "FeedbackOp",
    "FromAgentOp",
    "FromEqsatOp",
    "FromTemplateOp",
    "LineageOp",
    "PromoteOp",
    "RejectOp",
]
