"""Recipe IR Family F: Provenance/Feedback operations.

These record where a choice came from and what happened to it.
Enables lineage, auditing, replay, and promotion tracking.
"""

from __future__ import annotations

from xdsl.dialects.builtin import ArrayAttr, IntegerAttr, StringAttr, SymbolRefAttr
from xdsl.irdl import (
    IRDLOperation,
    irdl_op_definition,
    opt_prop_def,
    prop_def,
    traits_def,
)
from xdsl.traits import Pure

from compgen.ir.recipe.attrs import CostAttr


@irdl_op_definition
class FromAgentOp(IRDLOperation):
    """Records that a candidate was generated by an LLM agent."""

    name = "recipe.from_agent"

    agent_id = prop_def(StringAttr)
    iteration = prop_def(IntegerAttr)
    reasoning = opt_prop_def(StringAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class FromEqsatOp(IRDLOperation):
    """Records that a candidate came from equality saturation."""

    name = "recipe.from_eqsat"

    rule_name = prop_def(StringAttr)
    eclass_count = opt_prop_def(IntegerAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class FromTemplateOp(IRDLOperation):
    """Records that a candidate came from a deterministic template."""

    name = "recipe.from_template"

    template_name = prop_def(StringAttr)
    template_version = opt_prop_def(IntegerAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class FeedbackOp(IRDLOperation):
    """Records verification/profiling feedback for a candidate.

    Outcomes: "passed", "failed", "timeout", "error".
    """

    name = "recipe.feedback"

    candidate_ref = prop_def(SymbolRefAttr)
    outcome = prop_def(StringAttr)
    measured_cost = opt_prop_def(CostAttr)
    message = opt_prop_def(StringAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class RejectOp(IRDLOperation):
    """Records that a candidate was rejected."""

    name = "recipe.reject"

    candidate_ref = prop_def(SymbolRefAttr)
    reason = prop_def(StringAttr)
    feedback_ref = opt_prop_def(SymbolRefAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class PromoteOp(IRDLOperation):
    """Records that a candidate was promoted into the recipe library.

    M-27 (Section 19) extends the original three-field op
    ``(candidate_ref, recipe_key, version)`` with five optional
    pattern-level attrs that let a future run decide whether the
    promoted recipe applies, rank it among alternatives, or reject it
    cleanly:

    - ``recipe_signature``: JSON projection of the region pattern this
      recipe was promoted *for* (op_family / dtype / layout /
      shape_class / target_class). Pairs with the
      :class:`compgen.promotion.region_signature.RegionSignature` hash
      stored in :class:`compgen.promotion.promote.RecipeKey`.
    - ``applies_when``: ``ArrayAttr`` of ``SymbolRefAttr`` references to
      ``recipe.fact_*`` ops that must hold for the recipe to apply
      (e.g. ``@fact_tile_divisible_16`` or ``@fact_contiguous_layout``).
      Validated by :func:`validate_recipe_module` to resolve.
    - ``evidence_summary``: compact JSON projection of readiness rows /
      gate level / certificate hashes — written by the M-26 bridge,
      mirrored into the recipe sidecar so the agent can rank promoted
      candidates without re-reading the bundle.
    - ``fallback_chain``: ``ArrayAttr`` of ``SymbolRefAttr`` candidate
      references to try (in order) if this recipe is rejected at apply
      time. Empty by default.
    - ``target_class``: canonical target-class string (e.g.
      ``host_cpu``, ``cuda_sm75``, ``triton_friendly``). Validated
      against an enum-like allowlist by ``validate_recipe_module``.

    All five are optional so the existing three-field PromoteOp surface
    keeps working for legacy callers.
    """

    name = "recipe.promote"

    candidate_ref = prop_def(SymbolRefAttr)
    recipe_key = prop_def(StringAttr)
    version = prop_def(IntegerAttr)

    # M-27 additions — optional for backward compatibility.
    recipe_signature = opt_prop_def(StringAttr)
    applies_when = opt_prop_def(ArrayAttr)
    evidence_summary = opt_prop_def(StringAttr)
    fallback_chain = opt_prop_def(ArrayAttr)
    target_class = opt_prop_def(StringAttr)

    traits = traits_def(Pure())


@irdl_op_definition
class LineageOp(IRDLOperation):
    """Full lineage chain for a candidate.

    Tracks parent candidates and generation number for evolutionary
    search and audit trails.
    """

    name = "recipe.lineage"

    candidate_ref = prop_def(SymbolRefAttr)
    parent_refs = prop_def(ArrayAttr)  # ArrayAttr of SymbolRefAttr
    generation = prop_def(IntegerAttr)

    traits = traits_def(Pure())


__all__ = [
    "FeedbackOp",
    "FromAgentOp",
    "FromEqsatOp",
    "FromTemplateOp",
    "LineageOp",
    "PromoteOp",
    "RejectOp",
]
