"""Stage 5 — codegen: the QNN back end of the flow.

ModelBlaster's `generate_xpurt_main.py` emits Zephyr C that calls
generated kernels through a hart-pinned `modelblaster_pool`.  That pool is
a *parallel-for*: one op, N harts, a range split.  It is the right shape
for RISC-V, and the wrong shape here — on this board the work inside a
dispatch is done by HVX / the tensor accelerator / the CPU op package,
none of which the host runtime can subdivide.

So Flow C emits a different runtime over the same table:

  threading   One lane worker per machine kind (`--lane-mode kind`), or per
              (kind, network) (`--lane-mode kind-network`) when the schedule
              serialises two networks onto one kind and their periods differ
              enough that head-of-line blocking would eat a deadline.  Each
              worker is a std::thread pinned with pthread_setaffinity_np to
              the core the registry gives that kind.  Workers block inside
              QnnGraph_execute, so the lane count is the concurrency: three
              lanes = HTA + DSP + CPU running at once, which is the whole
              point of the schedule.

  tiling      A tile is a binding — a contiguous IR op range compiled into
              one QNN graph.  The runtime executes exactly one graph per
              entry, so re-tiling is a compile-time decision (see
              flowc/bindings.py).  Instance-level tiling falls out for free:
              two instances of the same network may carry different
              backends, and each (ctx, backend) pair is brought up once.

  ordering    Per-entry POSIX completion semaphores, the schedule's
              intra-job `deps[]` and cross-job `time_dep`, and a start-time
              gate against the run's t0.

  serialization  Backends flagged `exec_serialized` in the registry (HTA,
              DSP — their drivers keep process-global state) take a
              per-backend mutex around execute; per-graph mutexes always
              apply because two entries sharing a graph share its I/O
              buffers.
"""

from __future__ import annotations

import os
from collections import OrderedDict

from .schedule import FlowCEntry

HEADER = "/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */"


def _lane_key(e: FlowCEntry, mode: str) -> str:
    return e.kind if mode == "kind" else f"{e.kind}|{e.network}"


def _c_str(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def emit_table(entries: list[FlowCEntry], lane_mode: str, out_path: str) -> dict:
    lanes: "OrderedDict[str, dict]" = OrderedDict()
    for e in entries:
        key = _lane_key(e, lane_mode)
        if key not in lanes:
            lanes[key] = {"kind": e.kind, "label": e.backend_label,
                          "hart": e.hart, "harts": e.harts, "network": e.network,
                          "serialized": e.exec_serialized,
                          "spin_us": e.gate_spin_us,
                          "fifo": e.sched_fifo_prio,
                          "exec_cores": e.exec_cores}
    # Several lanes of one kind (kind-network mode) must not share a gate core:
    # two spinning waiters on one core serialise each other. Spread them over
    # the kind's harts, cycling if there are more lanes than cores.
    from collections import defaultdict
    per_kind = defaultdict(list)
    for key, v in lanes.items():
        per_kind[v["kind"]].append(key)
    for kind, keys in per_kind.items():
        harts = [lanes[k]["harts"] for k in keys][0] or []
        for i, key in enumerate(keys):
            if harts:
                lanes[key]["hart"] = harts[i % len(harts)]
    lane_index = {k: i for i, k in enumerate(lanes)}

    lines = [HEADER, "#pragma once", "#include <stddef.h>", "",
             "#ifdef __cplusplus", 'extern "C" {', "#endif", ""]
    lines += [
        "/* The first block is field-for-field modelblaster's xpurt_sched_entry_t",
        " * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read",
        " * the other; the second block is what a QNN dispatch additionally needs. */",
        "typedef struct {",
        "    int          entry_id;",
        "    const char  *network;",
        "    int          instance;",
        "    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */",
        "    const char  *op;               /* IR op kind: always \"qnn_graph\" here */",
        "    const char  *name;             /* binding name */",
        "    const char  *core_kind;        /* registry kind: hta / dsp / cpu */",
        "    int          hart;             /* host core this lane pins to */",
        "    double       start_time_ms;",
        "    double       duration_ms;",
        "    int          n_deps;",
        "    const int   *deps;",
        "    int          time_dep_entry_id;",
        "    /* ---- Flow C ---- */",
        "    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */",
        "    const char  *backend_lib;      /* libQnn*.so to dlopen */",
        "    const char  *ctx;              /* context binary filename */",
        "    const char  *graph;            /* graph inside that context */",
        "    int          exec_serialized;  /* backend needs a process-wide exec lock */",
        "    int          lane;             /* worker lane index */",
        "    int          n_ir_ops;         /* IR ops this tile covers */",
        "    int          ir_first;",
        "    int          ir_last;",
        "} flowc_sched_entry_t;",
        "",
        f"#define FLOWC_N_ENTRIES {len(entries)}",
        f"#define FLOWC_N_LANES {len(lanes)}",
        "",
    ]
    for e in entries:
        if e.deps:
            lines.append(f"static const int flowc_e{e.entry_id}_deps[] = "
                         f"{{ {', '.join(str(d) for d in e.deps)} }};")
    lines.append("")
    lines.append("static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {")
    for e in entries:
        deps_ref = f"flowc_e{e.entry_id}_deps" if e.deps else "NULL"
        lines.append(
            f"    {{ {e.entry_id}, {_c_str(e.network)}, {e.instance}, {e.binding_id}, "
            f'"qnn_graph", {_c_str(e.binding_name)}, {_c_str(e.kind)}, {e.hart}, '
            f"{e.start_time_ms:.6f}, {e.duration_ms:.6f}, "
            f"{len(e.deps)}, {deps_ref}, {e.time_dep}, "
            f"{_c_str(e.backend_label)}, {_c_str(e.backend_lib)}, "
            f"{_c_str(e.ctx)}, {_c_str(e.graph)}, {1 if e.exec_serialized else 0}, "
            f"{lane_index[_lane_key(e, lane_mode)]}, {e.n_ir_ops}, {e.ir_first}, {e.ir_last} }},")
    lines.append("};")
    lines.append("")
    lines.append("static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {")
    for key in lanes:
        lines.append(f"    {_c_str(key)},")
    lines.append("};")
    lines.append("static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { "
                 + ", ".join(str(v["hart"]) for v in lanes.values()) + " };")
    lines.append("/* Spin-before-deadline budget per lane. The registry's")
    lines.append(" * qnn.gate_spin_us, capped at a quarter of the lane's own minimum")
    lines.append(" * inter-entry gap: a lane whose period equals its spin window spins")
    lines.append(" * essentially continuously, which is fine while it owns its core and")
    lines.append(" * ruinous once another lane's compute shares the cluster. */")
    starts = {}
    for e in entries:
        starts.setdefault(lane_index[_lane_key(e, lane_mode)], []).append(e.start_time_ms)
    capped = []
    for key, v in lanes.items():
        ss = sorted(starts.get(lane_index[key], []))
        gaps = [b - a for a, b in zip(ss, ss[1:]) if b - a > 1e-6]
        spin = v["spin_us"]
        if gaps:
            cap = int(0.25 * min(gaps) * 1000.0)
            if cap < spin:
                v["spin_capped_from"] = spin
                spin = max(cap, 0)
        v["spin_effective"] = spin
        capped.append(spin)
    lines.append("static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { "
                 + ", ".join(str(x) for x in capped) + " };")
    lines.append("/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), "
                 "from the registry's qnn.sched_fifo_prio. */")
    lines.append("static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { "
                 + ", ".join(str(v["fifo"]) for v in lanes.values()) + " };")
    lines.append("/* Cores the backend's own threads may use during execute, from")
    lines.append(" * the registry's qnn.exec_cores. Empty string = the whole machine. */")
    lines.append("static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {")
    for v in lanes.values():
        lines.append("    " + _c_str(",".join(str(c) for c in v["exec_cores"])) + ",")
    lines.append("};")
    lines.append("")
    lines += ["#ifdef __cplusplus", "}  /* extern \"C\" */", "#endif", ""]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(lines))
    return {"lanes": list(lanes), "lane_index": lane_index, "n_entries": len(entries)}

MAIN_TEMPLATE = r'''__HEADER__

// Flow C runtime — modelblaster's schedule table, QNN's execution model.
//
// Threading: one std::thread per lane (see FLOWC_LANE_NAME), pinned with
// pthread_setaffinity_np to the core the registry assigns that machine
// kind. Workers block inside QnnGraph_execute; lanes are the concurrency.
// There is deliberately no intra-dispatch thread pool: HVX / HTA / the CPU
// op package do that work themselves, and a host-side parallel-for would
// only contend with them.
//
// gcc 9.4 on the board has no <semaphore>, so completion gates are POSIX
// sem_t.
#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdarg>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cerrno>
#include <cstring>
#include <ctime>
#include <dlfcn.h>
#include <fstream>
#include <memory>
#include <mutex>
#include <pthread.h>
#include <sched.h>
#include <semaphore.h>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>

#include "QNN/QnnInterface.h"
#include "QNN/QnnTypes.h"
#include "QNN/System/QnnSystemInterface.h"
#include "QNN/System/QnnSystemContext.h"
#include "dispatch_table.h"

#define CHECK(expr) do { Qnn_ErrorHandle_t _e = (expr);                        \
    if (_e != QNN_SUCCESS) {                                                   \
        std::fprintf(stderr, "QNN error 0x%llx at %s:%d — %s\n",               \
                     (unsigned long long)_e, __FILE__, __LINE__, #expr);       \
        std::exit(1);                                                          \
    } } while (0)

static const std::string CTX_DIR = "__CTX_DIR__";

static double now_ms() {
    using namespace std::chrono;
    return duration<double, std::milli>(steady_clock::now().time_since_epoch()).count();
}
static void log_cb(const char* fmt, QnnLog_Level_t, uint64_t, va_list ap) {
    std::vfprintf(stderr, fmt, ap); std::fprintf(stderr, "\n");
}
static std::vector<uint8_t> slurp(const std::string& p) {
    std::ifstream f(p, std::ios::binary | std::ios::ate);
    if (!f) { std::fprintf(stderr, "open %s failed\n", p.c_str()); std::exit(1); }
    auto n = f.tellg(); f.seekg(0); std::vector<uint8_t> v(n);
    f.read((char*)v.data(), n); return v;
}

// ---------------------------------------------------------------- tensors
static uint32_t tensor_rank(const Qnn_Tensor_t& t) {
    return t.version == QNN_TENSOR_VERSION_2 ? t.v2.rank : t.v1.rank;
}
static const uint32_t* tensor_dims(const Qnn_Tensor_t& t) {
    return t.version == QNN_TENSOR_VERSION_2 ? t.v2.dimensions : t.v1.dimensions;
}
static Qnn_DataType_t tensor_dtype(const Qnn_Tensor_t& t) {
    return t.version == QNN_TENSOR_VERSION_2 ? t.v2.dataType : t.v1.dataType;
}
static const char* tensor_name(const Qnn_Tensor_t& t) {
    const char* n = (t.version == QNN_TENSOR_VERSION_2 ? t.v2.name : t.v1.name);
    return n ? n : "";
}
static size_t bytes_per_element(Qnn_DataType_t dt) {
    switch (dt) {
        case QNN_DATATYPE_INT_8: case QNN_DATATYPE_UINT_8:
        case QNN_DATATYPE_SFIXED_POINT_8: case QNN_DATATYPE_UFIXED_POINT_8:
        case QNN_DATATYPE_BOOL_8:        return 1;
        case QNN_DATATYPE_INT_16: case QNN_DATATYPE_UINT_16:
        case QNN_DATATYPE_SFIXED_POINT_16: case QNN_DATATYPE_UFIXED_POINT_16:
        case QNN_DATATYPE_FLOAT_16:      return 2;
        case QNN_DATATYPE_INT_32: case QNN_DATATYPE_UINT_32:
        case QNN_DATATYPE_FLOAT_32:
        case QNN_DATATYPE_SFIXED_POINT_32: case QNN_DATATYPE_UFIXED_POINT_32: return 4;
        case QNN_DATATYPE_INT_64: case QNN_DATATYPE_UINT_64:
        case QNN_DATATYPE_FLOAT_64:      return 8;
        default:                         return 4;
    }
}
static size_t tensor_byte_size(const Qnn_Tensor_t& t) {
    size_t n = 1; uint32_t r = tensor_rank(t); auto* d = tensor_dims(t);
    for (uint32_t i = 0; i < r; ++i) n *= d[i];
    return n * bytes_per_element(tensor_dtype(t));
}
// The binary-info tensors point into memory owned by the QnnSystem handle;
// deep-copy dims and name so they survive after we free it.
static void rebind_tensor(Qnn_Tensor_t& t, std::vector<uint32_t>& d, std::string& nm) {
    uint32_t r = tensor_rank(t); auto* dp = tensor_dims(t);
    d.assign(dp, dp + r); nm = tensor_name(t);
    if (t.version == QNN_TENSOR_VERSION_2) { t.v2.dimensions = d.data(); t.v2.name = nm.c_str(); }
    else                                   { t.v1.dimensions = d.data(); t.v1.name = nm.c_str(); }
}
static void set_tensor_buffer(Qnn_Tensor_t& t, void* data, uint32_t bytes) {
    if (t.version == QNN_TENSOR_VERSION_2) {
        t.v2.memType = QNN_TENSORMEMTYPE_RAW;
        t.v2.clientBuf.data = data; t.v2.clientBuf.dataSize = bytes;
    } else {
        t.v1.memType = QNN_TENSORMEMTYPE_RAW;
        t.v1.clientBuf.data = data; t.v1.clientBuf.dataSize = bytes;
    }
}

// ------------------------------------------------------------- QNN handles
// One backend handle per library. HTA-class backends keep process-global
// state and reject a second QnnBackend for the same lib ("Context handle
// already exists!"), so every context on a lib shares one of these.
struct SharedBackend {
    void*                   lib     = nullptr;
    QNN_INTERFACE_VER_TYPE  iface{};
    Qnn_LogHandle_t         log     = nullptr;
    Qnn_BackendHandle_t     backend = nullptr;
    std::mutex              exec_mu;   // used when the registry says serialized
};
static std::unordered_map<std::string, std::shared_ptr<SharedBackend>> g_backends;

struct GraphInfo {
    Qnn_GraphHandle_t                  graph = nullptr;
    std::string                        name;
    std::vector<Qnn_Tensor_t>          inputs, outputs;
    std::vector<std::vector<uint8_t>>  inputBufs, outputBufs;
    std::vector<std::vector<uint32_t>> dimStorage;
    std::vector<std::string>           nameStorage;
    std::mutex                         m;   // two entries on one graph share its buffers
};

struct LoadedCtx {
    std::string                     label, ctx_file;
    std::shared_ptr<SharedBackend>  sb;
    Qnn_ContextHandle_t             ctx = nullptr;
    std::unordered_map<std::string, std::unique_ptr<GraphInfo>> graphs;
    // --- lazy-load bookkeeping (only used when a budget is set) ---
    std::string lib_path;          // enough to reconstruct the context on demand
    bool        loaded   = false;
    long long   last_use = 0;      // for LRU
    int         in_use   = 0;      // a lane is executing on it right now
};
static std::unordered_map<std::string, std::shared_ptr<LoadedCtx>> g_ctx;

// Lazy context loading. A 141-tile network exhausts the board if every context
// is created at bringup -- QNN error 0x4 out of contextCreateFromBinary at ~56
// contexts on QRB5165 v66. With FLOWC_CTX_BUDGET set, contexts are created on
// first use and the least-recently-used one on the same backend is freed when
// the budget is reached. Default 0 = eager, which is exactly the old behaviour,
// so runtimes that already fit are bit-identical.
static std::mutex g_load_mu;
static long long  g_use_clock  = 0;
static int        g_ctx_budget = 0;
static long long  g_n_loads = 0, g_n_evicts = 0;
static double     g_load_ms = 0.0;

struct SysFns {
    QnnSystemContext_CreateFn_t        create        = nullptr;
    QnnSystemContext_GetBinaryInfoFn_t getBinaryInfo = nullptr;
    QnnSystemContext_FreeFn_t          free          = nullptr;
};
static SysFns g_sys;   // set in main; workers need it to reload lazily

static SysFns load_system() {
    SysFns f{};
    void* lib = dlopen("libQnnSystem.so", RTLD_NOW | RTLD_GLOBAL);
    if (!lib) { std::fprintf(stderr, "dlopen libQnnSystem.so: %s\n", dlerror()); std::exit(1); }
    auto fn = (Qnn_ErrorHandle_t (*)(const QnnSystemInterface_t***, uint32_t*))
              dlsym(lib, "QnnSystemInterface_getProviders");
    const QnnSystemInterface_t** prov = nullptr; uint32_t n = 0;
    CHECK(fn(&prov, &n));
    auto& s = prov[0]->QNN_SYSTEM_INTERFACE_VER_NAME;
    f.create = s.systemContextCreate; f.getBinaryInfo = s.systemContextGetBinaryInfo;
    f.free = s.systemContextFree;
    return f;
}

static int g_warmup = 2;

static void bringup(LoadedCtx& bc, const std::string& bin_path,
                    const std::string& lib_path, const std::string& label,
                    const SysFns& sys) {
    bc.label = label; bc.ctx_file = bin_path; bc.lib_path = lib_path;
    auto it = g_backends.find(lib_path);
    if (it != g_backends.end()) {
        bc.sb = it->second;
    } else {
        auto sb = std::make_shared<SharedBackend>();
        sb->lib = dlopen(lib_path.c_str(), RTLD_NOW | RTLD_LOCAL);
        if (!sb->lib) { std::fprintf(stderr, "dlopen %s: %s\n", lib_path.c_str(), dlerror()); std::exit(1); }
        auto getProv = (Qnn_ErrorHandle_t (*)(const QnnInterface_t***, uint32_t*))
                       dlsym(sb->lib, "QnnInterface_getProviders");
        const QnnInterface_t** prov = nullptr; uint32_t np = 0;
        CHECK(getProv(&prov, &np));
        sb->iface = prov[0]->QNN_INTERFACE_VER_NAME;
        CHECK(sb->iface.logCreate(log_cb, QNN_LOG_LEVEL_ERROR, &sb->log));
        CHECK(sb->iface.backendCreate(sb->log, nullptr, &sb->backend));
        g_backends[lib_path] = sb;
        bc.sb = sb;
    }
    auto& iface = bc.sb->iface;

    auto bin = slurp(bin_path);
    QnnSystemContext_Handle_t sysHandle = nullptr;
    CHECK(sys.create(&sysHandle));
    const QnnSystemContext_BinaryInfo_t* info = nullptr;
    Qnn_ContextBinarySize_t infoSz = 0;
    CHECK(sys.getBinaryInfo(sysHandle, bin.data(), bin.size(), &info, &infoSz));
    uint32_t nG = 0; const QnnSystemContext_GraphInfo_t* gs = nullptr;
    if      (info->version == QNN_SYSTEM_CONTEXT_BINARY_INFO_VERSION_1) { nG = info->contextBinaryInfoV1.numGraphs; gs = info->contextBinaryInfoV1.graphs; }
    else if (info->version == QNN_SYSTEM_CONTEXT_BINARY_INFO_VERSION_2) { nG = info->contextBinaryInfoV2.numGraphs; gs = info->contextBinaryInfoV2.graphs; }
    else                                                                { nG = info->contextBinaryInfoV3.numGraphs; gs = info->contextBinaryInfoV3.graphs; }
    if (!nG) { std::fprintf(stderr, "no graphs in %s\n", bin_path.c_str()); std::exit(1); }

    CHECK(iface.contextCreateFromBinary(bc.sb->backend, nullptr, nullptr,
                                        bin.data(), bin.size(), &bc.ctx, nullptr));

    for (uint32_t gi = 0; gi < nG; ++gi) {
        const auto& g = gs[gi];
        const char* nm = nullptr; uint32_t nIn = 0, nOut = 0;
        const Qnn_Tensor_t *inT = nullptr, *outT = nullptr;
        if      (g.version == QNN_SYSTEM_CONTEXT_GRAPH_INFO_VERSION_1) { nm = g.graphInfoV1.graphName; nIn = g.graphInfoV1.numGraphInputs; inT = g.graphInfoV1.graphInputs; nOut = g.graphInfoV1.numGraphOutputs; outT = g.graphInfoV1.graphOutputs; }
        else if (g.version == QNN_SYSTEM_CONTEXT_GRAPH_INFO_VERSION_2) { nm = g.graphInfoV2.graphName; nIn = g.graphInfoV2.numGraphInputs; inT = g.graphInfoV2.graphInputs; nOut = g.graphInfoV2.numGraphOutputs; outT = g.graphInfoV2.graphOutputs; }
        else                                                          { nm = g.graphInfoV3.graphName; nIn = g.graphInfoV3.numGraphInputs; inT = g.graphInfoV3.graphInputs; nOut = g.graphInfoV3.numGraphOutputs; outT = g.graphInfoV3.graphOutputs; }
        auto info2 = std::make_unique<GraphInfo>();
        info2->name = nm ? nm : "";
        info2->inputs.assign(inT, inT + nIn);
        info2->outputs.assign(outT, outT + nOut);
        info2->dimStorage.resize(nIn + nOut);
        info2->nameStorage.resize(nIn + nOut);
        for (size_t i = 0; i < info2->inputs.size(); ++i)
            rebind_tensor(info2->inputs[i], info2->dimStorage[i], info2->nameStorage[i]);
        for (size_t i = 0; i < info2->outputs.size(); ++i)
            rebind_tensor(info2->outputs[i], info2->dimStorage[nIn + i], info2->nameStorage[nIn + i]);
        CHECK(iface.graphRetrieve(bc.ctx, info2->name.c_str(), &info2->graph));
        info2->inputBufs.resize(info2->inputs.size());
        for (size_t i = 0; i < info2->inputs.size(); ++i) {
            size_t sz = tensor_byte_size(info2->inputs[i]);
            info2->inputBufs[i].assign(sz, 0);
            set_tensor_buffer(info2->inputs[i], info2->inputBufs[i].data(), (uint32_t)sz);
        }
        info2->outputBufs.resize(info2->outputs.size());
        for (size_t i = 0; i < info2->outputs.size(); ++i) {
            size_t sz = tensor_byte_size(info2->outputs[i]);
            info2->outputBufs[i].assign(sz, 0);
            set_tensor_buffer(info2->outputs[i], info2->outputBufs[i].data(), (uint32_t)sz);
        }
        // Warm up: the first execute on a fresh context pays a cold cost the
        // cost model never saw, and it lands on whichever entry runs first.
        for (int w = 0; w < g_warmup; ++w) {
            Qnn_ErrorHandle_t err = iface.graphExecute(
                info2->graph, info2->inputs.data(), (uint32_t)info2->inputs.size(),
                info2->outputs.data(), (uint32_t)info2->outputs.size(), nullptr, nullptr);
            if (err != QNN_SUCCESS) {
                std::fprintf(stderr, "[bringup] warmup %d failed on %s::%s (0x%llx)\n",
                             w, bin_path.c_str(), info2->name.c_str(), (unsigned long long)err);
                break;
            }
        }
        bc.graphs[info2->name] = std::move(info2);
    }
    sys.free(sysHandle);
    if (std::getenv("FLOWC_DUMP_TENSORS")) {
        for (auto& kv : bc.graphs) {
            std::fprintf(stderr, "[tensors] %s::%s in:", bin_path.c_str(), kv.first.c_str());
            for (auto& t : kv.second->inputs)  std::fprintf(stderr, " %s", tensor_name(t));
            std::fprintf(stderr, "  out:");
            for (auto& t : kv.second->outputs) std::fprintf(stderr, " %s", tensor_name(t));
            std::fprintf(stderr, "\n");
        }
    }
    std::fprintf(stderr, "[bringup] %-4s %s → %zu graph(s):", label.c_str(),
                 bin_path.c_str(), bc.graphs.size());
    for (auto& kv : bc.graphs) std::fprintf(stderr, " %s", kv.first.c_str());
    std::fprintf(stderr, "\n");
}

// ------------------------------------------------------ lazy ctx loading
static void unload_ctx(LoadedCtx& bc) {
    if (!bc.loaded) return;
    bc.graphs.clear();                       // buffers + tensor storage
    if (bc.ctx) bc.sb->iface.contextFree(bc.ctx, nullptr);
    bc.ctx = nullptr;
    bc.loaded = false;
    ++g_n_evicts;
}

// Caller must hold g_load_mu.
static void evict_for(const std::string& label) {
    if (g_ctx_budget <= 0) return;
    for (;;) {
        int live = 0;
        LoadedCtx* victim = nullptr;
        for (auto& kv : g_ctx) {
            LoadedCtx& c = *kv.second;
            if (!c.loaded || c.label != label) continue;
            ++live;
            if (c.in_use > 0) continue;
            if (!victim || c.last_use < victim->last_use) victim = &c;
        }
        if (live < g_ctx_budget || !victim) return;
        unload_ctx(*victim);
    }
}

static bool ensure_loaded(LoadedCtx& bc, const SysFns& sys) {
    if (g_ctx_budget <= 0) return true;               // eager: already up
    std::lock_guard<std::mutex> lk(g_load_mu);
    if (!bc.loaded) {
        evict_for(bc.label);
        double t0 = now_ms();
        bringup(bc, bc.ctx_file, bc.lib_path, bc.label, sys);
        g_load_ms += now_ms() - t0;
        bc.loaded = true;
        ++g_n_loads;
    }
    bc.last_use = ++g_use_clock;
    ++bc.in_use;
    return true;
}

static void release_ctx(LoadedCtx& bc) {
    if (g_ctx_budget <= 0) return;
    std::lock_guard<std::mutex> lk(g_load_mu);
    if (bc.in_use > 0) --bc.in_use;
}

// ------------------------------------------------------ boundary handoff
// Bindings that hand a tensor to the next tile (yolov8n backbone → head)
// match on tensor name. Anything unmatched keeps its zeroed buffer, which
// is what the timing-only runs want.
static std::mutex g_cache_mu;
static std::unordered_map<std::string, std::vector<uint8_t>> g_cache;
static std::atomic<int> g_handoffs{0};

static void cache_put(const std::string& key, const void* p, size_t n) {
    std::lock_guard<std::mutex> lk(g_cache_mu);
    auto& v = g_cache[key]; v.resize(n); std::memcpy(v.data(), p, n);
}
static bool cache_get(const std::string& key, void* p, size_t n) {
    std::lock_guard<std::mutex> lk(g_cache_mu);
    auto it = g_cache.find(key);
    if (it == g_cache.end() || it->second.size() != n) return false;
    std::memcpy(p, it->second.data(), n);
    return true;
}

// --------------------------------------------------------------- schedule
struct TraceRec {
    double dep_done_ms = 0, gate_done_ms = 0, start_ms = 0, end_ms = 0;
    int    lane = -1;
    bool   ran = false;
    // Boundary-handoff instrumentation. The cache_get loop runs BEFORE
    // start_ms and the cache_put loop AFTER end_ms, so this cost is real lane
    // wall time that the tile duration does not contain and the scheduler's
    // transfer model -- a zero matrix, see run_xpurt_schedule.py -- does not
    // predict. Measured per entry so it can be characterised by tensor size
    // and lane pair rather than inferred.
    double hin_ms = 0, hout_ms = 0;     // time in the get / put loops
    long   hin_bytes = 0, hout_bytes = 0;
    int    hin_hits = 0, hin_tensors = 0, hout_tensors = 0;
};
static std::vector<TraceRec> g_trace;
static std::vector<sem_t>    g_done;
static std::atomic<bool>     g_go{false};
static std::atomic<int>      g_ready{0};   // lanes parked at the start barrier
static double                g_t0 = 0.0;
static bool                  g_verbose = true;

static std::string ctx_key(const flowc_sched_entry_t& e) {
    return std::string(e.ctx) + "|" + e.backend_label;
}

// Start-time gate. A spin-yield loop is the obvious implementation and the
// wrong one here: it burns the lane's core for the whole idle window, which
// on the CPU lane is the same core the QNN CPU op package and the FastRPC
// callbacks want. Sleep on the absolute deadline instead (CLOCK_MONOTONIC,
// TIMER_ABSTIME — no drift from repeated relative sleeps), then spin only
// the last few hundred microseconds where the sleep's own wakeup jitter
// would otherwise dominate.
// Per-lane, because the right trade differs by lane: a lane whose entries
// are short and frequent (mlp_control at 500 Hz) wants a wide spin window
// so a timer wakeup never eats its 2 ms period, while a lane that sits in
// a 16 ms accelerator call wants to give its core back.
static long g_spin_us[FLOWC_N_LANES];

static void gate_until(double target_ms, int lane) {
    double remaining = target_ms - (now_ms() - g_t0);
    if (remaining > (double)g_spin_us[lane] / 1000.0) {
        struct timespec now, deadline;
        clock_gettime(CLOCK_MONOTONIC, &now);
        double sleep_ms = remaining - (double)g_spin_us[lane] / 1000.0;
        long long ns = now.tv_nsec + (long long)(sleep_ms * 1e6);
        deadline.tv_sec = now.tv_sec + ns / 1000000000LL;
        deadline.tv_nsec = (long)(ns % 1000000000LL);
        while (clock_nanosleep(CLOCK_MONOTONIC, TIMER_ABSTIME, &deadline, nullptr) == EINTR) {}
    }
    while ((now_ms() - g_t0) < target_ms) std::this_thread::yield();
}

static void pin_to(int core) {
    if (core < 0) return;
    cpu_set_t set; CPU_ZERO(&set); CPU_SET(core, &set);
    int rc = pthread_setaffinity_np(pthread_self(), sizeof(set), &set);
    if (rc != 0) std::fprintf(stderr, "[lane] affinity to core %d failed (%d)\n", core, rc);
}

// Real-time policy for a lane. Off by default: SCHED_FIFO at high priority
// on a phone SoC can starve the very kernel threads (FastRPC callbacks,
// DVFS governor) the accelerator lanes depend on. Worth turning on for a
// lane that carries a hard-deadline network and whose dispatches are short.
// Raise for the wait, drop for the work.
//
// SCHED_FIFO exists here to make a lane's *wake-up* punctual. Holding it
// across QnnGraph_execute is actively harmful: the backend op packages
// spawn their own worker threads, and a pthread inherits both scheduling
// policy and affinity from its creator — so a real-time, core-pinned lane
// hands the QNN CPU backend a pool of real-time threads all pinned to one
// core. Two such lanes on one core wedged the board hard enough to need a
// power cycle. The policy is therefore scoped to the gate.
static void set_sched(int prio) {
    struct sched_param sp{};
    if (prio > 0) {
        sp.sched_priority = prio;
        if (pthread_setschedparam(pthread_self(), SCHED_FIFO, &sp) != 0)
            std::fprintf(stderr, "[lane] SCHED_FIFO %d failed — need root?\n", prio);
    } else {
        sp.sched_priority = 0;
        pthread_setschedparam(pthread_self(), SCHED_OTHER, &sp);
    }
}

// Affinity is likewise gate-scoped: pinned while waiting so the wake lands
// on a known core, unpinned for execute so the backend's own threads can
// use the machine.
static cpu_set_t g_all_cores;
static cpu_set_t g_exec_mask[FLOWC_N_LANES];   // per-lane execute affinity

static void pin_to_core(int core) {
    if (core < 0) return;
    cpu_set_t set; CPU_ZERO(&set); CPU_SET(core, &set);
    pthread_setaffinity_np(pthread_self(), sizeof(set), &set);
}
// Restore the lane's *execute* affinity — not "everything". The backend's
// worker threads inherit this mask, so it decides which cores the compute
// lands on; leaving it wide lets a CPU-heavy network stomp the cores the
// accelerator lanes wake up on.
static void unpin_to_exec(int lane) {
    pthread_setaffinity_np(pthread_self(), sizeof(g_exec_mask[lane]), &g_exec_mask[lane]);
}

static void worker(int lane, int core, int fifo_prio) {
    // Park at the barrier *after* pinning and first-touching this thread's
    // stack, so t0 measures the schedule and not thread startup.
    g_ready.fetch_add(1, std::memory_order_release);
    while (!g_go.load(std::memory_order_acquire)) std::this_thread::yield();

    for (int i = 0; i < FLOWC_N_ENTRIES; ++i) {
        const flowc_sched_entry_t& e = FLOWC_TABLE[i];
        if (e.lane != lane) continue;

        for (int d = 0; d < e.n_deps; ++d) { sem_wait(&g_done[e.deps[d]]); sem_post(&g_done[e.deps[d]]); }
        if (e.time_dep_entry_id >= 0) {
            sem_wait(&g_done[e.time_dep_entry_id]); sem_post(&g_done[e.time_dep_entry_id]);
        }
        TraceRec& tr = g_trace[e.entry_id];
        tr.lane = lane;
        tr.dep_done_ms = now_ms() - g_t0;

        // --- gate: pinned and (optionally) real-time ---
        pin_to_core(core);
        set_sched(fifo_prio);
        gate_until(e.start_time_ms, lane);
        tr.gate_done_ms = now_ms() - g_t0;
        // --- work: ordinary policy, full machine ---
        set_sched(0);
        unpin_to_exec(lane);

        auto cit = g_ctx.find(ctx_key(e));
        if (cit == g_ctx.end()) {
            std::fprintf(stderr, "[run] entry %d: context %s not loaded — skipping\n",
                         e.entry_id, e.ctx);
            sem_post(&g_done[e.entry_id]);
            continue;
        }
        LoadedCtx& bc = *cit->second;
        ensure_loaded(bc, g_sys);          // no-op unless FLOWC_CTX_BUDGET is set
        auto git = bc.graphs.find(e.graph);
        if (git == bc.graphs.end()) {
            std::fprintf(stderr, "[run] entry %d: graph %s not in %s — skipping\n",
                         e.entry_id, e.graph, e.ctx);
            release_ctx(bc);
            sem_post(&g_done[e.entry_id]);
            continue;
        }
        GraphInfo& gi = *git->second;

        std::unique_lock<std::mutex> be_lk(bc.sb->exec_mu, std::defer_lock);
        if (e.exec_serialized) be_lk.lock();
        std::lock_guard<std::mutex> g_lk(gi.m);

        double h0 = now_ms();
        for (size_t t = 0; t < gi.inputs.size(); ++t) {
            std::string key = std::string(e.network) + "/" + tensor_name(gi.inputs[t]);
            tr.hin_tensors++;
            if (cache_get(key, gi.inputBufs[t].data(), gi.inputBufs[t].size())) {
                g_handoffs.fetch_add(1, std::memory_order_relaxed);
                tr.hin_hits++;
                tr.hin_bytes += (long)gi.inputBufs[t].size();
            }
        }
        tr.hin_ms = now_ms() - h0;

        tr.start_ms = now_ms() - g_t0;
        Qnn_ErrorHandle_t err = bc.sb->iface.graphExecute(
            gi.graph, gi.inputs.data(), (uint32_t)gi.inputs.size(),
            gi.outputs.data(), (uint32_t)gi.outputs.size(), nullptr, nullptr);
        tr.end_ms = now_ms() - g_t0;
        tr.ran = true;

        double h1 = now_ms();
        for (size_t t = 0; t < gi.outputs.size(); ++t) {
            cache_put(std::string(e.network) + "/" + tensor_name(gi.outputs[t]),
                      gi.outputBufs[t].data(), gi.outputBufs[t].size());
            tr.hout_tensors++;
            tr.hout_bytes += (long)gi.outputBufs[t].size();
        }
        tr.hout_ms = now_ms() - h1;

        release_ctx(bc);
        if (err != QNN_SUCCESS)
            std::fprintf(stderr, "[run] entry %d (%s/%s) execute failed: 0x%llx\n",
                         e.entry_id, e.network, e.name, (unsigned long long)err);
        else if (g_verbose)
            std::printf("[run] e=%-3d %-14s#%-2d %-22s lane=%-10s %-3s "
                        "predicted=%7.3f actual=%7.3f ms (start=%8.3f, late=%+.3f)\n",
                        e.entry_id, e.network, e.instance, e.name,
                        FLOWC_LANE_NAME[e.lane], e.backend_label,
                        e.duration_ms, tr.end_ms - tr.start_ms, tr.start_ms,
                        tr.start_ms - e.start_time_ms);
        sem_post(&g_done[e.entry_id]);
    }
}

int main() {
    // deploy_and_run.sh captures the run as `> run.log 2>&1`, so stdout and
    // stderr share one file description. stdout is block-buffered when it is
    // a file, stderr is unbuffered: a 4 KiB flush boundary can land in the
    // middle of a printf while an unbuffered stderr write slips into the gap,
    // splitting a trace CSV row in two. Line-buffer stdout so every
    // newline-terminated record is flushed as a unit, and flush before each
    // stderr write so the two streams stay in program order.
    std::setvbuf(stdout, nullptr, _IOLBF, 0);
    if (const char* v = std::getenv("FLOWC_WARMUP"))  g_warmup  = std::atoi(v);
    if (const char* v = std::getenv("FLOWC_SPIN_US")) {
        // "500" sets every lane; "200,2000,200" sets them in lane order.
        std::string s(v); size_t pos = 0; int l = 0; long last = 200;
        while (pos <= s.size() && l < FLOWC_N_LANES) {
            size_t comma = s.find(',', pos);
            last = std::atol(s.substr(pos, comma - pos).c_str());
            g_spin_us[l++] = last;
            if (comma == std::string::npos) break;
            pos = comma + 1;
        }
        for (; l < FLOWC_N_LANES; ++l) g_spin_us[l] = last;
    }
    if (const char* v = std::getenv("FLOWC_VERBOSE")) g_verbose = std::atoi(v) != 0;
    int iterations = 1;
    if (const char* v = std::getenv("FLOWC_ITERATIONS")) iterations = std::max(1, std::atoi(v));
    bool trace = true;
    if (const char* v = std::getenv("FLOWC_TRACE")) trace = std::atoi(v) != 0;

    for (int l = 0; l < FLOWC_N_LANES; ++l) g_spin_us[l] = FLOWC_LANE_SPIN_US[l];
    std::vector<int> lane_core(FLOWC_N_LANES);
    for (int l = 0; l < FLOWC_N_LANES; ++l) lane_core[l] = FLOWC_LANE_HART[l];
    if (const char* v = std::getenv("FLOWC_AFFINITY")) {
        std::string s(v);
        if (s == "off") { for (auto& c : lane_core) c = -1; }
        else {
            size_t pos = 0; int l = 0;
            while (pos < s.size() && l < FLOWC_N_LANES) {
                size_t comma = s.find(',', pos);
                lane_core[l++] = std::atoi(s.substr(pos, comma - pos).c_str());
                if (comma == std::string::npos) break;
                pos = comma + 1;
            }
        }
    }

    std::vector<int> lane_fifo(FLOWC_N_LANES);
    for (int l = 0; l < FLOWC_N_LANES; ++l) lane_fifo[l] = FLOWC_LANE_FIFO[l];
    if (const char* v = std::getenv("FLOWC_FIFO")) {
        std::string s(v); size_t pos = 0; int l = 0; int last = 0;
        while (pos <= s.size() && l < FLOWC_N_LANES) {
            size_t comma = s.find(',', pos);
            last = std::atoi(s.substr(pos, comma - pos).c_str());
            lane_fifo[l++] = last;
            if (comma == std::string::npos) break;
            pos = comma + 1;
        }
        for (; l < FLOWC_N_LANES; ++l) lane_fifo[l] = last;
    }

    // kind-network mode can put several lanes on one kind, and they all
    // inherit that kind's core and priority from the registry. Two spinning
    // real-time lanes on one core is a livelock, so only the first lane on a
    // core keeps a real-time priority and a spin window.
    {
        std::unordered_map<int, int> first_on_core;
        for (int l = 0; l < FLOWC_N_LANES; ++l) {
            int core = lane_core[l];
            if (core < 0) continue;
            auto it = first_on_core.find(core);
            if (it == first_on_core.end()) { first_on_core[core] = l; continue; }
            if (lane_fifo[l] > 0 || g_spin_us[l] > 0) {
                std::fprintf(stderr,
                    "[main] lane %d (%s) shares core %d with lane %d (%s): "
                    "dropping its SCHED_FIFO %d and %ld us spin to avoid two "
                    "real-time spinners on one core\n",
                    l, FLOWC_LANE_NAME[l], core, it->second,
                    FLOWC_LANE_NAME[it->second], lane_fifo[l], g_spin_us[l]);
                lane_fifo[l] = 0;
                g_spin_us[l] = 0;
            }
        }
    }

    CPU_ZERO(&g_all_cores);
    for (int c = 0; c < CPU_SETSIZE && c < 64; ++c) CPU_SET(c, &g_all_cores);
    for (int l = 0; l < FLOWC_N_LANES; ++l) {
        const char* spec = FLOWC_LANE_EXEC_CORES[l];
        if (const char* env = std::getenv("FLOWC_EXEC_CORES")) spec = env;
        if (!spec || !*spec) { g_exec_mask[l] = g_all_cores; continue; }
        CPU_ZERO(&g_exec_mask[l]);
        std::string sp(spec); size_t pos = 0;
        while (pos <= sp.size()) {
            size_t comma = sp.find(',', pos);
            int c = std::atoi(sp.substr(pos, comma - pos).c_str());
            if (c >= 0 && c < CPU_SETSIZE) CPU_SET(c, &g_exec_mask[l]);
            if (comma == std::string::npos) break;
            pos = comma + 1;
        }
    }

    if (const char* v = std::getenv("FLOWC_CTX_BUDGET")) g_ctx_budget = std::atoi(v);
    SysFns sys = load_system();
    g_sys = sys;

    // Bring up every distinct (context binary, backend) the table names.
    // Order follows the table, so the first thing the schedule runs is the
    // first thing loaded.
    for (int i = 0; i < FLOWC_N_ENTRIES; ++i) {
        const flowc_sched_entry_t& e = FLOWC_TABLE[i];
        std::string key = ctx_key(e);
        if (g_ctx.count(key)) continue;
        std::string path = CTX_DIR + "/" + e.ctx;
        std::ifstream probe(path, std::ios::binary);
        if (!probe) {
            std::fprintf(stderr, "[bringup] MISSING %s — entries on it will be skipped\n",
                         path.c_str());
            continue;
        }
        probe.close();
        auto bc = std::make_shared<LoadedCtx>();
        if (g_ctx_budget > 0) {
            // Lazy: record what a reload needs, create nothing yet.
            bc->label = e.backend_label; bc->ctx_file = path;
            bc->lib_path = e.backend_lib;
            // bc->sb is filled by bringup() on first use; unload_ctx() only
            // ever touches it for a context that has actually been loaded.
        } else {
            bringup(*bc, path, e.backend_lib, e.backend_label, sys);
            bc->loaded = true;
        }
        g_ctx[key] = bc;
    }
    if (g_ctx_budget > 0)
        std::fprintf(stderr, "[main] lazy contexts: budget %d per backend, "
                     "%zu registered\n", g_ctx_budget, g_ctx.size());
    std::fprintf(stderr, "[main] %zu context(s), %d entries, %d lane(s):\n",
                 g_ctx.size(), FLOWC_N_ENTRIES, FLOWC_N_LANES);
    for (int l = 0; l < FLOWC_N_LANES; ++l)
        std::fprintf(stderr, "  lane %d  %-14s core %d  spin %ld us  fifo %d\n",
                     l, FLOWC_LANE_NAME[l], lane_core[l], g_spin_us[l], lane_fifo[l]);

    double wall = 0.0;
    for (int iter = 0; iter < iterations; ++iter) {
        g_verbose = (iter == iterations - 1) && (std::getenv("FLOWC_VERBOSE") == nullptr ||
                                                 std::atoi(std::getenv("FLOWC_VERBOSE")) != 0);
        g_trace.assign(FLOWC_N_ENTRIES, TraceRec{});
        g_done.resize(FLOWC_N_ENTRIES);
        for (int i = 0; i < FLOWC_N_ENTRIES; ++i) sem_init(&g_done[i], 0, 0);
        g_go.store(false, std::memory_order_release);
        g_cache.clear();
        g_handoffs.store(0);

        std::vector<std::thread> lanes;
        g_ready.store(0, std::memory_order_release);
        for (int l = 0; l < FLOWC_N_LANES; ++l)
            lanes.emplace_back(worker, l, lane_core[l], lane_fifo[l]);
        while (g_ready.load(std::memory_order_acquire) < FLOWC_N_LANES)
            std::this_thread::yield();

        g_t0 = now_ms();
        g_go.store(true, std::memory_order_release);
        for (auto& t : lanes) t.join();
        wall = 0.0;
        for (auto& tr : g_trace) wall = std::max(wall, tr.end_ms);
        for (int i = 0; i < FLOWC_N_ENTRIES; ++i) sem_destroy(&g_done[i]);
        if (iterations > 1) {
            std::fflush(stdout);
            std::fprintf(stderr, "[main] iteration %d/%d wall=%.3f ms\n",
                         iter + 1, iterations, wall);
        }
    }

    int ran = 0;
    for (auto& tr : g_trace) ran += tr.ran ? 1 : 0;
    double predicted = 0.0;
    for (int i = 0; i < FLOWC_N_ENTRIES; ++i)
        predicted = std::max(predicted, FLOWC_TABLE[i].start_time_ms + FLOWC_TABLE[i].duration_ms);
    std::printf("\n[summary] %d/%d entries executed, wall=%.3f ms "
                "(predicted makespan %.3f ms, ratio %.2fx), tensor handoffs=%d\n",
                ran, FLOWC_N_ENTRIES, wall, predicted,
                predicted > 0 ? wall / predicted : 0.0, g_handoffs.load());

    if (g_ctx_budget > 0)
        std::fprintf(stderr, "[main] ctx loads=%lld evictions=%lld load_time=%.1f ms\n",
                     g_n_loads, g_n_evicts, g_load_ms);

    if (trace) {
        // Column names match modelblaster's MODELBLASTER_XPURT_TRACE block so
        // scripts/plot_xpurt_trace.py reads this unmodified (--clock-mhz 1,
        // i.e. one "cycle" == one microsecond); the trailing columns are the
        // Flow C extras a unit-aware reader can pick up.
        std::printf("\n=== MODELBLASTER_XPURT_TRACE_BEGIN ===\n");
        std::printf("entry_id,network,instance,dispatch_id,op,name,core_kind,hart,"
                    "predicted_start_ms,predicted_duration_ms,worker_kind_idx,"
                    "actual_start_cycles,actual_end_cycles,"
                    "time_unit,backend,ctx,graph,dep_wait_ms,gate_ms,n_ir_ops,"
                    "hin_ms,hout_ms,hin_bytes,hout_bytes,hin_hits,hin_tensors,"
                    "hout_tensors\n");
        for (int i = 0; i < FLOWC_N_ENTRIES; ++i) {
            const flowc_sched_entry_t& e = FLOWC_TABLE[i];
            const TraceRec& tr = g_trace[e.entry_id];
            std::printf("%d,%s,%d,%d,%s,%s,%s,%d,%.6f,%.6f,%d,%lld,%lld,"
                        "us,%s,%s,%s,%.6f,%.6f,%d,"
                        "%.6f,%.6f,%ld,%ld,%d,%d,%d\n",
                        e.entry_id, e.network, e.instance, e.dispatch_id, e.op, e.name,
                        e.core_kind, FLOWC_LANE_HART[e.lane],
                        e.start_time_ms, e.duration_ms, e.lane,
                        (long long)(tr.start_ms * 1000.0), (long long)(tr.end_ms * 1000.0),
                        e.backend_label, e.ctx, e.graph,
                        tr.dep_done_ms, tr.gate_done_ms, e.n_ir_ops,
                        tr.hin_ms, tr.hout_ms, tr.hin_bytes, tr.hout_bytes,
                        tr.hin_hits, tr.hin_tensors, tr.hout_tensors);
        }
        std::printf("=== MODELBLASTER_XPURT_TRACE_END ===\n");
    }
    return 0;
}
'''


def emit_main(out_path: str, ctx_dir: str) -> str:
    src = MAIN_TEMPLATE.replace("__HEADER__", HEADER).replace("__CTX_DIR__", ctx_dir)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w") as f:
        f.write(src)
    return out_path


def emit(entries, out_dir: str, ctx_dir: str, lane_mode: str = "kind") -> dict:
    """Emit dispatch_table.h + runtime_main.cpp into out_dir."""
    os.makedirs(out_dir, exist_ok=True)
    info = emit_table(entries, lane_mode, os.path.join(out_dir, "dispatch_table.h"))
    emit_main(os.path.join(out_dir, "runtime_main.cpp"), ctx_dir)
    info["out_dir"] = out_dir
    info["lane_mode"] = lane_mode
    return info
