"""Public facade for the agent-first compiler environment.

The package was split from a single 2571-line env.py module.  All original
public names are preserved via re-export so existing `from compgen.agent.env
import X` callers keep working.
"""

from __future__ import annotations

from compgen.agent.env.actions import (
    Action,
    AnalyzeAction,
    ApplyPassAction,
    AssignDeviceAction,
    BenchmarkAction,
    CalibrateAction,
    CheckpointAction,
    CompileAndRunAction,
    ConfigureDispatchAction,
    ConfigureProfilingAction,
    DiscoverOpsAction,
    EqSatAction,
    FuseAction,
    GenerateLLVMPatchAction,
    GeneratePassAction,
    GenerateRuntimeHooksAction,
    GenerateXDSLDialectAction,
    GeneralizeAction,
    InsertCopyAction,
    InspectAction,
    InspectEGraphAction,
    LegalAction,
    NoopAction,
    ProposeRuleAction,
    RequestSemanticsAction,
    RequestTransferAnalysisAction,
    RequestVerificationAction,
    RollbackAction,
    SearchKernelAction,
    SetDtypeAction,
    SetExtractionObjectiveAction,
    SolveAction,
    StepInfo,
    StepResult,
    TileAction,
)
from compgen.agent.env.core import CompilerEnv
from compgen.agent.env.observations import (
    Observation,
    RegionInfo,
    StepRecord,
    VerificationSummary,
    VerifiedFactInfo,
)

__all__ = [
    "Action",
    "AnalyzeAction",
    "ApplyPassAction",
    "AssignDeviceAction",
    "BenchmarkAction",
    "CalibrateAction",
    "CheckpointAction",
    "CompileAndRunAction",
    "ConfigureDispatchAction",
    "ConfigureProfilingAction",
    "CompilerEnv",
    "DiscoverOpsAction",
    "EqSatAction",
    "FuseAction",
    "GenerateLLVMPatchAction",
    "GeneratePassAction",
    "GenerateRuntimeHooksAction",
    "GenerateXDSLDialectAction",
    "GeneralizeAction",
    "InsertCopyAction",
    "InspectAction",
    "InspectEGraphAction",
    "LegalAction",
    "NoopAction",
    "Observation",
    "ProposeRuleAction",
    "RegionInfo",
    "RequestSemanticsAction",
    "RequestTransferAnalysisAction",
    "RequestVerificationAction",
    "RollbackAction",
    "SearchKernelAction",
    "SetDtypeAction",
    "SetExtractionObjectiveAction",
    "SolveAction",
    "StepInfo",
    "StepRecord",
    "StepResult",
    "TileAction",
    "VerificationSummary",
    "VerifiedFactInfo",
]
