"""The CompilerEnv class — gym-like environment for compiler optimization.

Think of it as a gym-like environment:
    state = IR structure + target capabilities + cost estimates + history
    action = one optimization decision (tile, fuse, place, etc.)
    reward = cost reduction + verification pass
    done = budget exhausted or no improving actions remain

Sibling modules in this package hold the supporting types:
- observations: RegionInfo, VerifiedFactInfo, VerificationSummary, Observation, StepRecord
- actions: Action + subclasses, LegalAction, StepResult, StepInfo
- helpers: _extract_regions, _make_pass_factory, _compute_legal_actions, _legal_tiles
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from xdsl.dialects.builtin import ModuleOp, StringAttr, TensorType
from xdsl.dialects.func import CallOp
from xdsl.dialects.linalg import MatmulOp
from xdsl.ir import Operation

from compgen.packs import LoadedPack, PackContextSummary, check_surface_allowed
from compgen.targets.schema import TargetProfile

from compgen.agent.env.actions import (
    Action,
    AnalyzeAction,
    ApplyPassAction,
    AssignDeviceAction,
    BenchmarkAction,
    CalibrateAction,
    CheckpointAction,
    CompileAndRunAction,
    ConfigureDispatchAction,
    ConfigureProfilingAction,
    DiscoverOpsAction,
    EqSatAction,
    FuseAction,
    GenerateLLVMPatchAction,
    GeneratePassAction,
    GenerateRuntimeHooksAction,
    GenerateXDSLDialectAction,
    GeneralizeAction,
    InsertCopyAction,
    InspectAction,
    InspectEGraphAction,
    LegalAction,
    NoopAction,
    ProposeRuleAction,
    RequestSemanticsAction,
    RequestTransferAnalysisAction,
    RequestVerificationAction,
    RollbackAction,
    SearchKernelAction,
    SetDtypeAction,
    SetExtractionObjectiveAction,
    SolveAction,
    StepInfo,
    StepResult,
    TileAction,
)
from compgen.agent.env.observations import (
    Observation,
    RegionInfo,
    StepRecord,
    VerificationSummary,
    VerifiedFactInfo,
)
from compgen.agent.env.helpers import (
    _PACK_ACTION_APERTURES,
    _PACK_DIRECT_SURFACES,
    _PASS_MENU,
    _compute_legal_actions,
    _extract_regions,
    _legal_tiles,
    _make_pass_factory,
)

class CompilerEnv:
    """Agent-first compiler environment.

    Usage:
        env = CompilerEnv()
        obs = env.reset(module, target, objective="latency", budget=50)
        while True:
            actions = env.legal_actions()
            # Agent picks one:
            result = env.step(actions[0].action)
            if result.done:
                break
        best_module = env.best_module()
    """

    def __init__(self) -> None:
        self._module: ModuleOp | None = None
        self._original_module: ModuleOp | None = None
        self._target: TargetProfile | None = None
        self._objective: str = "latency"
        self._budget: int = 50
        self._step_count: int = 0
        self._history: list[StepRecord] = []
        self._regions: list[RegionInfo] = []
        self._best_cost: float = float("inf")
        self._best_module: ModuleOp | None = None
        self._current_cost: float = float("inf")
        self._checkpoints: list[tuple[ModuleOp, list[RegionInfo], float]] = []
        self._exported_program: Any = None
        self._capture_artifact: Any = None
        self._pack_context: PackContextSummary | None = None
        self._loaded_packs: tuple[LoadedPack, ...] = ()
        self._analysis: Any = None  # NetworkAnalysis, set by AnalyzeAction
        self._llm_client: Any = None  # Shared LLM backend for pass generation / agent helpers
        self._pass_generator: Any = None  # PassGenerator, created on first GeneratePassAction
        self._pytorch_model: Any = None  # Original nn.Module for benchmarking
        self._sample_inputs: Any = None  # Sample inputs for benchmarking
        self._benchmark_results: list[Any] = []  # BenchmarkResult history
        self._memory: Any = None  # AgentMemory, lazy-loaded
        self._runtime_artifacts: dict[str, Any] = {}  # runtime configs generated by LLM
        self._profiling_config: Any = None  # InstrumentationConfig
        self._dispatch_config: Any = None  # DispatchConfig
        self._generated_hooks: dict[str, str] = {}  # hook_point → C code
        self._recipe_module: ModuleOp | None = None  # Recipe IR accumulator
        self._agent_module: ModuleOp | None = None  # Agent IR accumulator
        self._verification_results: list[Any] = []  # VerificationResult history
        self._verified_facts: list[Any] = []  # VerifiedFact history
        self._pending_semantics_requests: list[str] = []  # Op types awaiting semantics
        self._kernel_db: Any = None  # KernelDB, lazy-loaded on first SearchKernelAction

    def reset(
        self,
        module: ModuleOp,
        target: TargetProfile,
        objective: str = "latency",
        budget: int = 50,
        exported_program: Any = None,
        capture_artifact: Any = None,
        pack_context: PackContextSummary | None = None,
        loaded_packs: tuple[LoadedPack, ...] = (),
        pytorch_model: Any = None,
        sample_inputs: Any = None,
    ) -> Observation:
        """Start a new optimization episode.

        Args:
            module: xDSL ModuleOp (Payload IR).
            target: Hardware target profile.
            objective: Optimization objective.
            budget: Max steps.
            exported_program: Original torch.export ExportedProgram (for FX-level analysis).
            capture_artifact: Canonical capture-boundary artifact, if available.
            pytorch_model: Original nn.Module (for benchmarking).
            sample_inputs: Sample inputs tuple (for benchmarking).
        """
        self._original_module = module
        self._module = module.clone()
        self._target = target
        self._objective = objective
        self._budget = budget
        self._step_count = 0
        self._history = []
        self._exported_program = exported_program
        self._capture_artifact = capture_artifact
        self._pack_context = pack_context
        self._loaded_packs = tuple(loaded_packs)
        self._pytorch_model = pytorch_model
        self._sample_inputs = sample_inputs
        self._analysis = None
        self._benchmark_results = []
        self._eqsat_weights: dict[str, float] = {
            "fusion": 1.0, "transfer": 1.0, "backend_match": 1.0,
        }
        self._recipe_module = None
        self._agent_module = None
        self._verification_results = []
        self._verified_facts = []
        self._pending_semantics_requests = []

        self._regions = _extract_regions(self._module, target)
        self._current_cost = sum(r.estimated_latency_us for r in self._regions)
        self._best_cost = self._current_cost
        self._best_module = self._module.clone()

        return self._make_observation()

    def attach_llm_client(self, llm_client: Any) -> None:
        """Attach the active LLM backend so env-managed synthesis uses the same provider."""
        self._llm_client = llm_client
        self._pass_generator = None

    def enable_recipe_tracking(self) -> None:
        """Enable Recipe IR accumulation.

        After calling this, each ``step()`` will also record the action
        as Recipe IR plus Agent IR in internal modules. Call ``recipe``
        or ``agent_ir`` to retrieve the accumulated tracking state.
        """
        assert self._module is not None and self._target is not None
        from compgen.ir.agent.seed import generate_seed_agent
        from compgen.ir.recipe.seed import generate_seed_recipe

        self._recipe_module = generate_seed_recipe(
            self._module, self._target, self._objective,
        )
        self._agent_module = generate_seed_agent(
            self._recipe_module, self._target, self._objective,
        )

    @property
    def recipe(self) -> ModuleOp | None:
        """Return the accumulated Recipe IR module, or None if tracking is off."""
        return self._recipe_module

    @property
    def agent_ir(self) -> ModuleOp | None:
        """Return the accumulated Agent IR module, or None if tracking is off."""
        return self._agent_module

    @property
    def payload_module(self) -> ModuleOp | None:
        """Return the live Payload IR module (the working copy ``step()`` mutates).

        Set with :meth:`set_payload_module` when an external pass
        (e.g. :func:`compgen.mcp.tools.recipe_apply.apply_recipe`)
        rewrites the IR and needs to rebind the env's view of it.
        """
        return self._module

    def set_payload_module(self, module: ModuleOp) -> None:
        """Replace the live Payload IR module + re-extract region facts.

        Used after :class:`~compgen.ir.recipe.execute.RecipeExecutor`
        applies transform scripts to the payload module — the env
        needs to see the rewritten module so subsequent ``observe()``
        / ``step()`` calls operate on the new state.
        """
        assert self._target is not None, (
            "set_payload_module called before reset(); env has no target"
        )
        self._module = module
        self._regions = _extract_regions(self._module, self._target)
        self._current_cost = sum(r.estimated_latency_us for r in self._regions)

    def observe(self) -> Observation:
        """Get the current observation."""
        return self._make_observation()

    def _pack_apertures(self) -> tuple[str, ...]:
        if self._pack_context is None:
            return ()
        return self._pack_context.generation_apertures

    def _sealed_surfaces(self) -> tuple[str, ...]:
        if self._pack_context is None:
            return ()
        return self._pack_context.sealed_surfaces

    def _pack_violation_for_action(self, action: Action) -> str | None:
        if self._pack_context is None or not self._pack_context.active_packs:
            return None

        sealed = set(self._sealed_surfaces())
        for surface in _PACK_DIRECT_SURFACES.get(type(action), ()):
            def _matches(candidate: str) -> bool:
                return candidate == surface or candidate.endswith(surface)

            if self._loaded_packs:
                violation = check_surface_allowed(self._loaded_packs, requested_surface=surface)
                if violation is not None:
                    return (
                        f"Action '{action.action_type}' cannot mutate sealed surface "
                        f"'{violation.surface}' owned by pack '{violation.pack_name}'."
                    )
                for pack in self._loaded_packs:
                    for candidate in pack.manifest.sealed_surfaces:
                        if _matches(candidate):
                            return (
                                f"Action '{action.action_type}' cannot mutate sealed surface "
                                f"'{candidate}' owned by pack '{pack.manifest.name}'."
                            )
            if any(_matches(candidate) for candidate in sealed):
                return (
                    f"Action '{action.action_type}' cannot mutate sealed surface "
                    f"'{surface}' declared by the active extension packs."
                )

        required_apertures = _PACK_ACTION_APERTURES.get(type(action), ())
        if not required_apertures:
            return None

        declared = set(self._pack_apertures())
        if any(aperture in declared for aperture in required_apertures):
            return None
        if not declared:
            return (
                f"Action '{action.action_type}' requires one of {sorted(required_apertures)} "
                "but the active packs expose no generation apertures."
            )
        return (
            f"Action '{action.action_type}' requires one of {sorted(required_apertures)} "
            f"but the active packs only allow {sorted(declared)}."
        )

    def _pack_generated_actions(self) -> list[LegalAction]:
        actions: list[LegalAction] = []
        if not self._loaded_packs:
            return actions

        declared = set(self._pack_apertures())
        rank = 10000
        for pack in self._loaded_packs:
            if "xdsl_dialect_generation" in declared and "dialect_semantics" not in pack.manifest.sealed_surfaces:
                rank += 1
                actions.append(
                    LegalAction(
                        action=GenerateXDSLDialectAction(pack_name=pack.manifest.name),
                        estimated_cost_delta_us=0.0,
                        estimated_cost_after_us=self._current_cost,
                        reason=f"Generate xDSL dialect scaffolding for pack {pack.manifest.name}",
                        risk="moderate",
                        rank=rank,
                    )
                )
            if "llvm_patch_generation" in declared and "llvm_intrinsics" not in pack.manifest.sealed_surfaces:
                rank += 1
                actions.append(
                    LegalAction(
                        action=GenerateLLVMPatchAction(pack_name=pack.manifest.name),
                        estimated_cost_delta_us=0.0,
                        estimated_cost_after_us=self._current_cost,
                        reason=f"Generate LLVM fork patch scaffolding for pack {pack.manifest.name}",
                        risk="moderate",
                        rank=rank,
                    )
                )
        return actions

    def legal_actions(self, max_actions: int = 200) -> list[LegalAction]:
        """Get legal actions for the current state, ranked by estimated value.

        Noop is always included regardless of max_actions.
        """
        assert self._target is not None
        actions = _compute_legal_actions(self._regions, self._target)
        actions.extend(self._pack_generated_actions())
        filtered: list[LegalAction] = []
        for candidate in actions:
            if isinstance(candidate.action, NoopAction):
                filtered.append(candidate)
                continue
            violation = self._pack_violation_for_action(candidate.action)
            if violation is None:
                filtered.append(candidate)
        actions = filtered
        # Ensure noop is always present
        noops = [a for a in actions if isinstance(a.action, NoopAction)]
        non_noops = [a for a in actions if not isinstance(a.action, NoopAction)]
        result = non_noops[:max_actions]
        if noops:
            result.append(noops[0])
        return result

    def step(self, action: Action) -> StepResult:
        """Apply an action and return the result.

        Real transforms clone the module, apply the pass, verify the result,
        re-extract regions, and update the cost model. Failed transforms are
        rejected with diagnostics — the module stays unchanged.
        """
        assert self._module is not None and self._target is not None

        cost_before = self._current_cost
        self._step_count += 1
        applied = False
        error = ""
        verification_passed = True
        diagnostics: list[str] = []

        violation = self._pack_violation_for_action(action)
        if violation is not None:
            error = violation
            record = StepRecord(
                step=self._step_count,
                action_type=action.action_type,
                action_target=action.region_id,
                was_legal=False,
                was_applied=False,
                cost_before_us=cost_before,
                cost_after_us=cost_before,
                improvement_pct=0.0,
                verification_passed=False,
                error=error,
            )
            self._history.append(record)
            return StepResult(
                observation=self._make_observation(),
                reward=0.0,
                done=self._step_count >= self._budget,
                info=StepInfo(
                    action_applied=False,
                    verification_passed=False,
                    cost_before_us=cost_before,
                    cost_after_us=cost_before,
                    improvement_pct=0.0,
                    error=error,
                    diagnostics=tuple(),
                ),
            )

        if isinstance(action, NoopAction):
            applied = True

        elif isinstance(action, GeneralizeAction):
            applied, error, diagnostics = self._apply_generalize(action)

        elif isinstance(action, ApplyPassAction):
            applied, error, diagnostics = self._apply_pass(action)

        elif isinstance(action, CheckpointAction):
            self._checkpoints.append((
                self._module.clone(),
                list(self._regions),
                self._current_cost,
            ))
            applied = True
            diagnostics.append(f"Checkpoint saved (depth {len(self._checkpoints)})")

        elif isinstance(action, RollbackAction):
            if self._checkpoints:
                mod, regions, cost = self._checkpoints.pop()
                self._module = mod
                self._regions = regions
                self._current_cost = cost
                applied = True
                diagnostics.append(f"Rolled back (depth {len(self._checkpoints)})")
            else:
                error = "No checkpoint to rollback to"

        elif isinstance(action, InspectAction):
            # Inspect doesn't change state, just enriches diagnostics
            for r in self._regions:
                if r.region_id == action.region_id:
                    diagnostics.append(
                        f"INSPECT {r.region_id}: type={r.op_type} "
                        f"flops={r.flops:,} bytes={r.bytes_in + r.bytes_out:,} "
                        f"AI={r.arithmetic_intensity:.1f} latency={r.estimated_latency_us:.2f}us "
                        f"bound={'compute' if r.is_compute_bound else 'memory'} "
                        f"device={r.device_index} dtype={r.dtype}"
                    )
                    applied = True
                    break
            if not applied:
                error = f"Region {action.region_id} not found"

        elif isinstance(action, AnalyzeAction):
            applied, error, diagnostics = self._apply_analyze()

        elif isinstance(action, SearchKernelAction):
            applied, error, diagnostics = self._apply_search_kernel(action)

        elif isinstance(action, GeneratePassAction):
            applied, error, diagnostics = self._apply_generate_pass(action)

        elif isinstance(action, SolveAction):
            applied, error, diagnostics = self._apply_solve(action)

        elif isinstance(action, BenchmarkAction):
            applied, error, diagnostics = self._apply_benchmark(action)

        elif isinstance(action, CalibrateAction):
            applied, error, diagnostics = self._apply_calibrate()

        elif isinstance(action, DiscoverOpsAction):
            applied, error, diagnostics = self._apply_discover_ops(action)

        elif isinstance(action, CompileAndRunAction):
            applied, error, diagnostics = self._apply_compile_and_run(action)

        elif isinstance(action, EqSatAction):
            applied, error, diagnostics = self._apply_eqsat(action)

        elif isinstance(action, InspectEGraphAction):
            applied, error, diagnostics = self._apply_inspect_egraph()

        elif isinstance(action, SetExtractionObjectiveAction):
            self._eqsat_weights = {
                "fusion": action.fusion_weight,
                "transfer": action.transfer_weight,
                "backend_match": action.backend_match_weight,
            }
            applied = True
            diagnostics.append(
                f"Extraction weights updated: fusion={action.fusion_weight}, "
                f"transfer={action.transfer_weight}, "
                f"backend_match={action.backend_match_weight}"
            )

        elif isinstance(action, TileAction):
            applied, error, diagnostics = self._apply_tile(action)

        elif isinstance(action, FuseAction):
            applied, error, diagnostics = self._apply_fuse(action)

        elif isinstance(action, InsertCopyAction):
            applied, error, diagnostics = self._apply_insert_copy(action)

        elif isinstance(action, SetDtypeAction):
            applied, error, diagnostics = self._apply_set_dtype(action)

        elif isinstance(action, ProposeRuleAction):
            applied, error, diagnostics = self._apply_propose_rule(action)

        elif isinstance(action, AssignDeviceAction):
            for i, r in enumerate(self._regions):
                if r.region_id == action.region_id:
                    self._regions[i] = RegionInfo(
                        region_id=r.region_id, op_type=r.op_type,
                        input_shapes=r.input_shapes, output_shapes=r.output_shapes,
                        flops=r.flops, bytes_in=r.bytes_in, bytes_out=r.bytes_out,
                        arithmetic_intensity=r.arithmetic_intensity,
                        estimated_latency_us=r.estimated_latency_us,
                        device_index=action.device_index,
                        is_compute_bound=r.is_compute_bound, dtype=r.dtype,
                        consumers=r.consumers, producers=r.producers,
                    )
                    applied = True
                    break

        elif isinstance(action, ConfigureProfilingAction):
            applied, error, diagnostics = self._apply_configure_profiling(action)

        elif isinstance(action, ConfigureDispatchAction):
            applied, error, diagnostics = self._apply_configure_dispatch(action)

        elif isinstance(action, GenerateRuntimeHooksAction):
            applied, error, diagnostics = self._apply_generate_hooks(action)

        elif isinstance(action, RequestVerificationAction):
            applied, error, diagnostics = self._apply_request_verification(action)

        elif isinstance(action, RequestSemanticsAction):
            applied, error, diagnostics = self._apply_request_semantics(action)

        elif isinstance(action, RequestTransferAnalysisAction):
            applied, error, diagnostics = self._apply_request_transfer_analysis(action)

        elif isinstance(action, GenerateXDSLDialectAction):
            applied, error, diagnostics = self._apply_generate_xdsl_dialect(action)

        elif isinstance(action, GenerateLLVMPatchAction):
            applied, error, diagnostics = self._apply_generate_llvm_patch(action)

        else:
            error = f"Unknown action type: {action.action_type}"

        cost_after = sum(r.estimated_latency_us for r in self._regions)
        self._current_cost = cost_after
        improvement = ((cost_before - cost_after) / cost_before * 100) if cost_before > 0 else 0

        if applied and cost_after < self._best_cost:
            self._best_cost = cost_after
            self._best_module = self._module.clone()

        record = StepRecord(
            step=self._step_count,
            action_type=action.action_type,
            action_target=action.region_id,
            was_legal=True,
            was_applied=applied,
            cost_before_us=cost_before,
            cost_after_us=cost_after,
            improvement_pct=improvement,
            verification_passed=verification_passed,
            error=error,
        )
        self._history.append(record)

        # Record action in Recipe IR if tracking is enabled
        if self._recipe_module is not None and applied:
            from compgen.agent.recipe_bridge import action_to_recipe_op
            recipe_op = action_to_recipe_op(action, self._step_count)
            if recipe_op is not None:
                self._recipe_module.body.block.add_op(recipe_op)
        if self._agent_module is not None and applied:
            from compgen.agent.ir_bridge import action_to_agent_ops

            known_scope_symbols = {
                getattr(op, "sym_name").data
                for op in self._agent_module.walk()
                if hasattr(op, "sym_name")
                and isinstance(getattr(op, "sym_name"), StringAttr)
                and getattr(op, "sym_name").data.startswith("scope_")
            }
            known_evidence_symbols = {
                getattr(op, "sym_name").data
                for op in self._agent_module.walk()
                if hasattr(op, "sym_name")
                and isinstance(getattr(op, "sym_name"), StringAttr)
                and getattr(op, "sym_name").data.startswith("evidence_")
            }
            for agent_op in action_to_agent_ops(
                action,
                self._step_count,
                known_scopes=known_scope_symbols,
                known_evidence_sets=known_evidence_symbols,
            ):
                self._agent_module.body.block.add_op(agent_op)

        done = self._step_count >= self._budget
        reward = (cost_before - cost_after) / max(cost_before, 1e-9)

        return StepResult(
            observation=self._make_observation(),
            reward=reward,
            done=done,
            info=StepInfo(
                action_applied=applied,
                verification_passed=verification_passed,
                cost_before_us=cost_before,
                cost_after_us=cost_after,
                improvement_pct=improvement,
                error=error,
                diagnostics=tuple(diagnostics),
            ),
        )

    def _apply_generalize(self, action: GeneralizeAction) -> tuple[bool, str, list[str]]:
        """Apply LinalgGeneralizeNamedOpsPass — turns matmul/transpose → generic."""
        from xdsl.transforms.linalg_generalize_named_ops import LinalgGeneralizeNamedOpsPass

        assert self._module is not None and self._target is not None
        diagnostics: list[str] = []

        try:
            cloned = self._module.clone()
            LinalgGeneralizeNamedOpsPass().apply(None, cloned)  # type: ignore[arg-type]
            cloned.verify()

            self._module = cloned
            self._regions = _extract_regions(self._module, self._target)
            diagnostics.append("Generalized named ops → linalg.generic")
            return True, "", diagnostics
        except Exception as e:
            return False, f"Generalize failed: {e}", diagnostics

    def _apply_pass(self, action: ApplyPassAction) -> tuple[bool, str, list[str]]:
        """Apply a registered xDSL pass from the pass menu."""
        from compgen.trace import DecisionPublisher, PassPublisher, get_ir_dump_writer

        assert self._module is not None and self._target is not None
        diagnostics: list[str] = []

        pass_entry = _PASS_MENU.get(action.pass_name)
        if pass_entry is None:
            DecisionPublisher.emit(
                decision_type="pass_select",
                chosen=action.pass_name,
                candidates=list(_PASS_MENU.keys()),
                rationale="rejected: unknown pass",
            )
            return False, f"Unknown pass: {action.pass_name}. Available: {list(_PASS_MENU.keys())}", diagnostics

        DecisionPublisher.emit(
            decision_type="pass_select",
            chosen=action.pass_name,
            candidates=list(_PASS_MENU.keys()),
            rationale=pass_entry.get("desc", ""),
        )
        dumper = get_ir_dump_writer()
        import time as _env_time

        try:
            with PassPublisher.span(
                payload={"name": action.pass_name, "source": "env._apply_pass"}
            ) as span_id:
                t0 = _env_time.time()
                cloned = self._module.clone()
                if dumper is not None:
                    dumper.dump(
                        name=f"env_{action.pass_name}",
                        phase="before",
                        module=self._module,
                        trace_event_id=span_id or "",
                    )
                pass_instance = pass_entry["factory"](action.pass_args)
                pass_instance.apply(None, cloned)
                cloned.verify()

                self._module = cloned
                self._regions = _extract_regions(self._module, self._target)
                elapsed_ms = (_env_time.time() - t0) * 1000.0
                if dumper is not None:
                    dumper.dump(
                        name=f"env_{action.pass_name}",
                        phase="after",
                        module=self._module,
                        trace_event_id=span_id or "",
                        duration_ms=elapsed_ms,
                    )
            diagnostics.append(f"Applied pass '{action.pass_name}': {pass_entry['desc']}")
            return True, "", diagnostics
        except Exception as e:
            return False, f"Pass '{action.pass_name}' failed: {e}", diagnostics

    def _apply_analyze(self) -> tuple[bool, str, list[str]]:
        """Run network analysis on the FX graph."""
        from compgen.agent.analyzer import NetworkAnalyzer
        from compgen.trace import AnalysisPublisher

        diagnostics: list[str] = []

        if self._exported_program is None:
            return False, "No ExportedProgram available. Pass exported_program to reset().", diagnostics

        assert self._target is not None
        try:
            analyzer = NetworkAnalyzer()
            with AnalysisPublisher.span(
                payload={"analysis": "NetworkAnalyzer", "target": getattr(self._target, "name", "")}
            ):
                self._analysis = analyzer.analyze(self._exported_program, self._target)

            AnalysisPublisher.emit(
                analysis="NetworkAnalyzer",
                clusters=len(self._analysis.clusters),
                unclustered=len(self._analysis.unclustered_ops or []),
                opportunities=list(self._analysis.optimization_opportunities or []),
            )

            diagnostics.append(f"ANALYSIS: {len(self._analysis.clusters)} pattern clusters detected")
            for c in self._analysis.clusters:
                best_lat = min(c.estimated_latency_per_device.values()) if c.estimated_latency_per_device else 0
                bottleneck = " [BOTTLENECK]" if c.is_bottleneck else ""
                diagnostics.append(
                    f"  {c.cluster_id}|{c.pattern_type}|{c.total_flops:,}F|"
                    f"{best_lat:.2f}us|kernel:{c.kernel_opportunity}{bottleneck}"
                )
            if self._analysis.unclustered_ops:
                diagnostics.append(f"  {len(self._analysis.unclustered_ops)} unclustered ops")
            for opp in self._analysis.optimization_opportunities:
                diagnostics.append(f"  OPP: {opp}")
            if self._analysis.dossier is not None:
                dossier = self._analysis.dossier
                diagnostics.append(
                    f"  DOSSIER: regions={dossier.total_regions} "
                    f"critical_path={list(dossier.critical_path)} "
                    f"unsupported={list(dossier.unsupported_targets)}"
                )

            return True, "", diagnostics
        except Exception as e:
            return False, f"Analysis failed: {e}", diagnostics

    def _apply_search_kernel(self, action: SearchKernelAction) -> tuple[bool, str, list[str]]:
        """Run Autocomp kernel search for a pattern cluster."""
        from compgen.agent.kernel_db import KernelDB, KernelEntry
        from compgen.kernels.autocomp_adapter import AutocompAdapter

        diagnostics: list[str] = []

        if self._analysis is None:
            return False, "Run AnalyzeAction first to detect pattern clusters.", diagnostics

        # Find the cluster
        cluster = None
        for c in self._analysis.clusters:
            if c.cluster_id == action.cluster_id:
                cluster = c
                break

        if cluster is None:
            available = [c.cluster_id for c in self._analysis.clusters]
            return False, f"Cluster '{action.cluster_id}' not found. Available: {available}", diagnostics

        assert self._target is not None

        # Lazy-init KernelDB on first use (bridge to CompilerMemory if available)
        if self._kernel_db is None:
            try:
                from compgen.memory.store import CompilerMemory
                mem = CompilerMemory()
                self._kernel_db = KernelDB.from_memory(mem)
            except Exception:
                self._kernel_db = KernelDB(db_path=".compgen_cache/kernel_db/kernel_db.json")

        # Check cache before running expensive search
        cached = self._kernel_db.lookup(
            pattern_type=cluster.pattern_type,
            target_name=self._target.name,
            shapes=cluster.input_shapes,
        )
        if cached is not None:
            diagnostics.append(
                f"KERNEL (cached): {cluster.cluster_id} -> {cached.language} "
                f"latency={cached.latency_us:.2f}us correct={cached.correct} "
                f"speedup={cached.speedup:.2f}x"
            )
            return True, "", diagnostics

        # Try provider registry first (supports multiple backends)
        try:
            from compgen.kernels.provider import KernelContract, SearchBudget
            from compgen.kernels.registry import ProviderRegistry

            if not hasattr(self, "_provider_registry") or self._provider_registry is None:
                from compgen.kernels.providers.autocomp import AutocompProvider, ExoProvider
                from compgen.kernels.providers.kernelblaster import KernelBlasterProvider

                self._provider_registry = ProviderRegistry()
                self._provider_registry.register(AutocompProvider())
                self._provider_registry.register(ExoProvider())
                self._provider_registry.register(KernelBlasterProvider())

            contract = KernelContract(
                region_id=cluster.cluster_id,
                op_family=cluster.pattern_type,
                target_name=self._target.name,
                hardware_key=self._target.name,
            )
            budget = SearchBudget(max_iterations=action.budget or 10)
            provider_result = self._provider_registry.search(contract, budget)

            # Ingest knowledge from providers into CompilerMemory
            if hasattr(self, "_verification_results"):
                try:
                    from compgen.memory.store import CompilerMemory

                    mem = CompilerMemory()
                    self._provider_registry.ingest_knowledge(mem)
                    # Apply contract feedback for future searches
                    feedback = self._provider_registry.collect_feedback()
                    if feedback:
                        diagnostics.append(
                            f"  Provider feedback: {len(feedback)} contract suggestions"
                        )
                except Exception:
                    pass

            if provider_result.found:
                diagnostics.append(
                    f"KERNEL (provider): {cluster.cluster_id} -> {provider_result.language} "
                    f"latency={provider_result.latency_us:.2f}us"
                )
                if provider_result.correct:
                    from compgen.agent.kernel_db import _shapes_key

                    entry = KernelEntry(
                        pattern_type=cluster.pattern_type,
                        target_name=self._target.name,
                        shapes_key=_shapes_key(cluster.input_shapes),
                        kernel_code=provider_result.kernel_code,
                        language=provider_result.language,
                        latency_us=provider_result.latency_us,
                        correct=provider_result.correct,
                        speedup=provider_result.speedup,
                        plan=provider_result.plan,
                    )
                    self._kernel_db.store(entry)
                return True, "", diagnostics
        except ImportError:
            pass  # fall through to direct autocomp path

        # Direct autocomp path (fallback if provider registry not available)
        adapter = AutocompAdapter()
        if not adapter.quick_check(cluster, self._target):
            return False, "Autocomp search not viable (need GPU + GOOGLE_API_KEY)", diagnostics

        try:
            result = adapter.search_kernel(cluster, self._target, budget=action.budget)
            diagnostics.append(
                f"KERNEL: {result.cluster_id} -> {result.language} "
                f"latency={result.latency_us:.2f}us correct={result.correct} "
                f"speedup={result.speedup_vs_baseline:.2f}x"
            )

            # Cache the result for future lookups
            if result.correct:
                from compgen.agent.kernel_db import _shapes_key

                entry = KernelEntry(
                    pattern_type=cluster.pattern_type,
                    target_name=self._target.name,
                    shapes_key=_shapes_key(cluster.input_shapes),
                    kernel_code=result.kernel_code,
                    language=result.language,
                    latency_us=result.latency_us,
                    correct=result.correct,
                    speedup=result.speedup_vs_baseline,
                    plan=result.plan,
                )
                self._kernel_db.store(entry)
                # Also write to CompilerMemory for cross-session retrieval
                try:
                    from compgen.memory.store import CompilerMemory
                    mem = CompilerMemory()
                    self._kernel_db.store_to_memory(entry, mem)
                except Exception:
                    pass
                diagnostics.append("  Kernel cached to KernelDB for future reuse.")

            return True, "", diagnostics
        except Exception as e:
            return False, f"Kernel search failed: {e}", diagnostics

    def _apply_benchmark(self, action: BenchmarkAction) -> tuple[bool, str, list[str]]:
        """Run real hardware benchmark on the PyTorch model."""
        from compgen.runtime.local_executor import LocalExecutor

        diagnostics: list[str] = []

        if self._pytorch_model is None or self._sample_inputs is None:
            return False, "No PyTorch model/inputs. Pass pytorch_model and sample_inputs to reset().", diagnostics

        try:
            executor = LocalExecutor()
            result = executor.benchmark(
                model=self._pytorch_model,
                sample_inputs=self._sample_inputs,
                device=action.device,
                mode=action.mode,
                num_iterations=action.num_iterations,
            )

            self._benchmark_results.append(result)

            diagnostics.append(
                f"BENCHMARK: {result.device}/{result.mode} "
                f"latency={result.latency_median_us:.1f}us (p99={result.latency_p99_us:.1f}us) "
                f"throughput={result.throughput_samples_per_sec:.0f} samples/s "
                f"memory={result.peak_memory_bytes / 1e6:.1f}MB"
            )

            # Compare with cost model estimate
            estimated = self._current_cost
            actual = result.latency_median_us
            if estimated > 0:
                accuracy = 1.0 - abs(estimated - actual) / max(estimated, actual)
                diagnostics.append(
                    f"  Cost model: estimated={estimated:.1f}us actual={actual:.1f}us "
                    f"accuracy={accuracy:.1%}"
                )

            return True, "", diagnostics
        except Exception as e:
            return False, f"Benchmark failed: {e}", diagnostics

    def _apply_calibrate(self) -> tuple[bool, str, list[str]]:
        """Calibrate cost model from benchmark measurements."""
        from compgen.agent.memory import AgentMemory

        diagnostics: list[str] = []

        if not self._benchmark_results:
            return False, "No benchmark results. Run BenchmarkAction first.", diagnostics

        if self._memory is None:
            self._memory = AgentMemory()

        assert self._target is not None
        latest = self._benchmark_results[-1]
        device_name = self._target.devices[0].name if self._target.devices else "unknown"

        # Update calibration for each region
        for r in self._regions:
            if r.estimated_latency_us > 0:
                # Distribute measured latency proportionally across regions
                total_estimated = sum(reg.estimated_latency_us for reg in self._regions)
                if total_estimated > 0:
                    fraction = r.estimated_latency_us / total_estimated
                    estimated_for_region = r.estimated_latency_us
                    measured_for_region = latest.latency_median_us * fraction
                    self._memory.cost_calibration.update(
                        device_name, r.op_type, estimated_for_region, measured_for_region
                    )

        # Report calibration state
        factors = self._memory.cost_calibration.factors.get(device_name, {})
        diagnostics.append(f"CALIBRATE: Updated {len(factors)} op correction factors for {device_name}")
        for op_type, factor in factors.items():
            diagnostics.append(f"  {op_type}: correction={factor:.2f}x")

        # Save memory
        self._memory.save(".compgen_cache/agent_memory.json")
        diagnostics.append("  Memory saved to .compgen_cache/agent_memory.json")

        return True, "", diagnostics

    def _apply_discover_ops(self, action: DiscoverOpsAction) -> tuple[bool, str, list[str]]:
        """Scan FX graph for unknown ops."""
        from compgen.agent.op_discovery import OpDiscovery

        diagnostics: list[str] = []

        if self._exported_program is None:
            return False, "No ExportedProgram. Pass exported_program to reset().", diagnostics

        if self._capture_artifact is not None and getattr(self._capture_artifact, "unsupported_resolutions", None):
            diagnostics.append(
                f"DISCOVER: Found {len(self._capture_artifact.unsupported_resolutions)} unsupported-op resolutions:"
            )
            for resolution in self._capture_artifact.unsupported_resolutions:
                diagnostics.append(
                    f"  {resolution.target}: {resolution.classification.bucket} "
                    f"strategy={resolution.classification.strategy} "
                    f"cache={resolution.promotion.cache_key}"
                )
            return True, "", diagnostics

        discovery = OpDiscovery()
        unknowns = discovery.discover_unknown_ops(self._exported_program)

        if not unknowns:
            diagnostics.append("DISCOVER: All ops are known — no unknown ops found")
            return True, "", diagnostics

        diagnostics.append(f"DISCOVER: Found {len(unknowns)} unknown ops:")
        for u in unknowns:
            diagnostics.append(f"  {u.target}: {u.shape} (seen {u.count}x)")

        if action.auto_generate and unknowns:
            diagnostics.append("  Auto-generation of decompositions not yet implemented")

        return True, "", diagnostics

    def _apply_compile_and_run(self, action: CompileAndRunAction) -> tuple[bool, str, list[str]]:
        """Compile with torch.compile using agent decisions and benchmark."""
        from compgen.runtime.torch_backend import CompGenBackend

        diagnostics: list[str] = []

        if self._pytorch_model is None or self._sample_inputs is None:
            return False, "No PyTorch model. Pass pytorch_model and sample_inputs to reset().", diagnostics

        try:
            # Collect agent decisions from current state
            decisions = {
                "device_assignments": {r.region_id: r.device_index for r in self._regions},
                "objective": self._objective,
            }

            backend = CompGenBackend(decisions)
            result = backend.compile_and_benchmark(
                self._pytorch_model, self._sample_inputs,
                device=action.device, num_iterations=action.num_iterations,
            )

            diagnostics.append(
                f"COMPILE+RUN: {result.device}/{result.mode} "
                f"latency={result.latency_median_us:.1f}us "
                f"throughput={result.throughput_samples_per_sec:.0f} samples/s"
            )

            self._benchmark_results.append(result)
            return True, "", diagnostics
        except Exception as e:
            return False, f"Compile+run failed: {e}", diagnostics

    def _apply_eqsat(self, action: EqSatAction) -> tuple[bool, str, list[str]]:
        """Run equality saturation on current IR."""
        diagnostics: list[str] = []

        try:
            from compgen.eqsat.config import EqSatConfig
            from compgen.eqsat.pipeline import run_eqsat_pass
            from compgen.eqsat.rules.registry import create_default_registry

            registry = create_default_registry()
            rules = registry.get_rules(action.rule_categories)

            # Include session-generated rules from ProposeRuleAction (Unit 3)
            if hasattr(self, "_session_rules"):
                rules = list(rules) + list(self._session_rules)

            if not rules:
                return False, f"No rules found for categories: {action.rule_categories}", diagnostics

            # Use segment threshold override from LLM if provided (Unit 5)
            seg_threshold = action.segment_threshold
            if action.segment_threshold_override is not None:
                seg_threshold = action.segment_threshold_override

            config = EqSatConfig(
                max_iterations=action.max_iterations,
                segment_threshold=seg_threshold,
            )

            result = run_eqsat_pass(
                self._module,
                config=config,
                rules=rules,
                blackbox_overrides=action.blackbox_overrides or None,
                segment_config={"threshold": seg_threshold} if action.segment_threshold_override else None,
            )

            diagnostics.append(
                f"EQSAT: {result.ops_before}→{result.ops_after} ops, "
                f"{result.eclasses_initial}→{result.eclasses_after_rewrite} eclasses, "
                f"{result.enodes_after_rewrite} enodes, changed={result.changed}"
            )
            for rule_name, count in result.rule_stats.items():
                diagnostics.append(f"  rule {rule_name}: {count} matches")

            # Re-extract regions from updated IR
            self._regions = _extract_regions(self._module, self._target)

            return True, "", diagnostics
        except Exception as e:
            return False, f"EqSat failed: {e}", diagnostics

    def _apply_inspect_egraph(self) -> tuple[bool, str, list[str]]:
        """Inspect e-graph state of current IR (creates temporary e-graph)."""
        diagnostics: list[str] = []

        try:
            from xdsl.dialects import equivalence

            from compgen.eqsat.pipeline import _count_eclasses, _count_enodes, create_egraph

            # Create a temporary copy to inspect
            temp_module = self._module.clone()
            create_egraph(temp_module)

            n_eclasses = _count_eclasses(temp_module)
            n_enodes = _count_enodes(temp_module)

            diagnostics.append(
                f"EGRAPH: {n_eclasses} e-classes, {n_enodes} e-nodes"
            )

            # Count ops by type
            op_counts: dict[str, int] = {}
            for op in temp_module.walk():
                if not isinstance(op, (equivalence.AnyClassOp, equivalence.GraphOp,
                                       equivalence.YieldOp)):
                    name = op.name
                    op_counts[name] = op_counts.get(name, 0) + 1
            for name, count in sorted(op_counts.items(), key=lambda x: -x[1])[:10]:
                diagnostics.append(f"  {name}: {count}")

            return True, "", diagnostics
        except Exception as e:
            return False, f"EGraph inspection failed: {e}", diagnostics

    def _apply_solve(self, action: SolveAction) -> tuple[bool, str, list[str]]:
        """Run CP-SAT solver for placement and/or scheduling."""
        from compgen.solve.partition import Partition
        from compgen.solve.placement import PlacementConstraint, solve_placement
        from compgen.solve.schedule import solve_schedule

        assert self._target is not None
        diagnostics: list[str] = []

        num_devices = len(self._target.devices)
        if num_devices < 2:
            return False, "Solver requires multi-device target (>= 2 devices)", diagnostics

        # Build partitions from regions
        partitions = []
        deps: dict[str, list[str]] = {}
        for r in self._regions:
            partitions.append(Partition(
                partition_id=r.region_id,
                op_names=[r.region_id],
                dependencies=list(r.producers),
                estimated_cost_us=r.estimated_latency_us,
                memory_bytes=r.bytes_in + r.bytes_out,
            ))
            deps[r.region_id] = list(r.producers)

        # Device compute rates from target profile
        compute_rates = []
        for dev in self._target.devices:
            peak = 0.0
            for cu in dev.compute_units:
                if cu.peak_tflops:
                    peak = max(peak, cu.peak_tflops)
            compute_rates.append(max(peak, 0.01))

        # Device memory caps
        memory_caps = []
        for dev in self._target.devices:
            cap = max((ml.size_bytes for ml in dev.memory_hierarchy), default=0)
            memory_caps.append(cap)

        # Transfer cost from interconnects
        transfer_costs: dict[tuple[int, int], float] = {}
        for ic in self._target.interconnects:
            d1, d2 = ic.devices
            if ic.bandwidth_gbps > 0:
                cost_per_byte = 1.0 / (ic.bandwidth_gbps * 1e9) * 1e6  # us per byte
                transfer_costs[(d1, d2)] = cost_per_byte
                transfer_costs[(d2, d1)] = cost_per_byte

        # Collect agent constraints from current device assignments
        constraints = []
        for r in self._regions:
            if r.device_index >= 0:
                constraints.append(PlacementConstraint(
                    partition_id=r.region_id,
                    required_device=r.device_index,
                    reason="Agent-assigned",
                ))

        if action.solve_type in ("placement", "both"):
            placement = solve_placement(
                partitions=partitions,
                num_devices=num_devices,
                device_compute_rates=compute_rates,
                device_memory_caps=memory_caps,
                transfer_cost_matrix=transfer_costs,
                constraints=constraints,
                timeout_ms=action.timeout_ms,
            )

            if placement.feasible:
                diagnostics.append(
                    f"PLACEMENT: feasible, cost={placement.objective_value:.2f}us, "
                    f"time={placement.solve_time_ms:.0f}ms"
                )
                for pid, dev_idx in placement.assignments.items():
                    diagnostics.append(f"  {pid} → device {dev_idx} ({self._target.devices[dev_idx].name})")

                # Update regions with solver assignments
                for i, r in enumerate(self._regions):
                    dev_idx = placement.assignments.get(r.region_id, r.device_index)
                    if dev_idx != r.device_index:
                        self._regions[i] = RegionInfo(
                            region_id=r.region_id, op_type=r.op_type,
                            input_shapes=r.input_shapes, output_shapes=r.output_shapes,
                            flops=r.flops, bytes_in=r.bytes_in, bytes_out=r.bytes_out,
                            arithmetic_intensity=r.arithmetic_intensity,
                            estimated_latency_us=r.estimated_latency_us,
                            device_index=dev_idx,
                            is_compute_bound=r.is_compute_bound, dtype=r.dtype,
                            consumers=r.consumers, producers=r.producers,
                        )
            else:
                diagnostics.append(f"PLACEMENT: infeasible (time={placement.solve_time_ms:.0f}ms)")
                return False, "Placement solver found no feasible solution", diagnostics

        if action.solve_type in ("schedule", "both"):
            assignments = {r.region_id: r.device_index for r in self._regions}
            durations = {r.region_id: max(r.estimated_latency_us, 0.001) for r in self._regions}

            sched = solve_schedule(
                partition_ids=[r.region_id for r in self._regions],
                durations_us=durations,
                device_assignments=assignments,
                dependencies=deps,
                num_devices=num_devices,
                timeout_ms=action.timeout_ms,
            )

            if sched.feasible:
                diagnostics.append(
                    f"SCHEDULE: feasible, makespan={sched.makespan_us:.2f}us, "
                    f"time={sched.solve_time_ms:.0f}ms"
                )
                for pid in sorted(sched.start_times, key=lambda p: sched.start_times[p]):
                    diagnostics.append(
                        f"  {pid}: {sched.start_times[pid]:.2f}us → {sched.end_times[pid]:.2f}us"
                    )
            else:
                diagnostics.append(f"SCHEDULE: infeasible (time={sched.solve_time_ms:.0f}ms)")

        return True, "", diagnostics

    def _apply_generate_pass(self, action: GeneratePassAction) -> tuple[bool, str, list[str]]:
        """Ask the LLM to generate a new compiler pass, then validate it."""
        from compgen.agent.pass_gen import PassGenerator
        from compgen.llm.factory import create_llm_client

        assert self._module is not None
        diagnostics: list[str] = []

        if not action.description:
            return False, "GeneratePassAction requires a description", diagnostics

        # Create pass generator on first use
        if self._pass_generator is None:
            client = self._llm_client
            if client is None:
                backend = os.environ.get("COMPGEN_LLM_BACKEND", "").strip()
                if not backend:
                    return (
                        False,
                        "No LLM client attached. Call attach_llm_client() or set COMPGEN_LLM_BACKEND.",
                        diagnostics,
                    )
                client = create_llm_client(backend, working_dir=Path.cwd())
            self._pass_generator = PassGenerator(llm_client=client)

        try:
            result = self._pass_generator.generate(
                description=action.description,
                target_pattern=action.target_pattern,
                expected_effect=action.expected_effect,
                module=self._module,
            )

            if result.verified:
                diagnostics.append(f"PASS_GEN: '{result.name}' generated and VERIFIED")
                diagnostics.append(f"  Code: {len(result.source_code)} chars")

                # Apply the pass
                assert self._target is not None
                success, err = self._pass_generator.apply_generated_pass(result.name, self._module)
                if success:
                    self._regions = _extract_regions(self._module, self._target)
                    diagnostics.append("  Applied successfully")
                    return True, "", diagnostics
                else:
                    diagnostics.append(f"  Application failed: {err}")
                    return False, err, diagnostics
            else:
                diagnostics.append(f"PASS_GEN: '{result.name}' FAILED verification")
                diagnostics.append(f"  Error: {result.verification_error}")
                return False, result.verification_error, diagnostics

        except Exception as e:
            return False, f"Pass generation failed: {e}", diagnostics

    def _apply_configure_profiling(
        self, action: ConfigureProfilingAction,
    ) -> tuple[bool, str, list[str]]:
        """Configure profiling based on LLM decision."""
        from compgen.runtime.instrumentation import InstrumentationConfig, InstrumentationLevel

        diagnostics: list[str] = []

        level_map = {
            "none": InstrumentationLevel.NONE,
            "op_level": InstrumentationLevel.OP_LEVEL,
            "tile_level": InstrumentationLevel.TILE_LEVEL,
            "full": InstrumentationLevel.FULL,
        }
        level = level_map.get(action.instrumentation_level, InstrumentationLevel.OP_LEVEL)

        self._profiling_config = InstrumentationConfig(level=level)
        self._generated_hooks.update(action.custom_hooks)
        self._runtime_artifacts["profiling"] = {
            "level": action.instrumentation_level,
            "counters": action.counters,
            "custom_hooks": action.custom_hooks,
            "analysis_focus": action.analysis_focus,
        }

        diagnostics.append(f"Profiling configured: level={action.instrumentation_level}")
        if action.counters:
            diagnostics.append(f"  Counters: {', '.join(action.counters)}")
        if action.custom_hooks:
            diagnostics.append(f"  Custom hooks: {len(action.custom_hooks)} hook points")

        return True, "", diagnostics

    def _apply_configure_dispatch(
        self, action: ConfigureDispatchAction,
    ) -> tuple[bool, str, list[str]]:
        """Configure dispatch strategy based on LLM decision."""
        from compgen.runtime.dispatch_strategy import create_strategy

        diagnostics: list[str] = []

        try:
            create_strategy(action.strategy)  # validate strategy name
        except ValueError as e:
            return False, str(e), diagnostics

        self._dispatch_config = {
            "strategy": action.strategy,
            "transport_overrides": action.transport_overrides,
            "thread_config": action.thread_config,
            "double_buffer": action.double_buffer,
        }
        self._runtime_artifacts["dispatch"] = self._dispatch_config

        diagnostics.append(f"Dispatch strategy: {action.strategy}")
        if action.transport_overrides:
            diagnostics.append(f"  Transport overrides: {action.transport_overrides}")
        if action.thread_config:
            diagnostics.append(f"  Thread config: {action.thread_config}")
        if action.double_buffer:
            diagnostics.append("  Double buffering: enabled")

        return True, "", diagnostics

    def _apply_generate_hooks(
        self, action: GenerateRuntimeHooksAction,
    ) -> tuple[bool, str, list[str]]:
        """Generate target-specific runtime hooks from LLM output."""
        diagnostics: list[str] = []

        if not action.hook_code:
            return False, "No hook code provided", diagnostics

        # Validate: each hook point should have non-empty code
        for hook_point, code in action.hook_code.items():
            if not code.strip():
                return False, f"Empty hook code for {hook_point}", diagnostics

        self._generated_hooks.update(action.hook_code)
        self._runtime_artifacts.setdefault("hooks", {})
        self._runtime_artifacts["hooks"].update(action.hook_code)

        diagnostics.append(f"Generated {len(action.hook_code)} runtime hooks ({action.hook_type})")
        for hp in action.hook_code:
            diagnostics.append(f"  {hp}: {len(action.hook_code[hp])} chars")

        return True, "", diagnostics

    def _find_loaded_pack(self, pack_name: str) -> LoadedPack | None:
        if not self._loaded_packs:
            return None
        if pack_name:
            for pack in self._loaded_packs:
                if pack.manifest.name == pack_name:
                    return pack
            return None
        return self._loaded_packs[0]

    def _default_dialect_spec(self, pack: LoadedPack) -> dict[str, Any]:
        op_name = f"{pack.manifest.name}_dispatch".replace("-", "_")
        return {
            "name": pack.manifest.name.replace("-", "_"),
            "python_module": pack.manifest.name.replace("-", "_"),
            "doc": f"Generated scaffold for pack {pack.manifest.name}.",
            "ops": [
                {
                    "name": op_name,
                    "operands": [{"name": "input", "type_expr": "AnyAttr()"}],
                    "results": [{"name": "output", "type_expr": "AnyAttr()"}],
                    "traits": ["Pure"],
                    "summary": f"Generated entry op for {pack.manifest.name}",
                }
            ],
        }

    def _default_llvm_patch_spec(self, pack: LoadedPack) -> dict[str, Any]:
        dialect_name = pack.manifest.name.replace("-", "_")
        return {
            "dialect_name": dialect_name,
            "intrinsics": [
                {
                    "name": f"llvm.{dialect_name}.dispatch",
                    "ret_type": "llvm_void_ty",
                    "arg_types": ["llvm_ptr_ty"],
                    "summary": f"Generated dispatch intrinsic for {pack.manifest.name}",
                }
            ],
        }

    def _write_generated_bundle(
        self,
        *,
        branch: Any,
        subdir: str,
        files: dict[str, str],
    ) -> dict[str, str]:
        output_dir = branch.worktree_path / subdir
        output_dir.mkdir(parents=True, exist_ok=True)
        emitted: dict[str, str] = {}
        for rel_name, content in files.items():
            path = output_dir / rel_name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
            emitted[rel_name] = str(path)
        return emitted

    def _apply_generate_xdsl_dialect(
        self, action: GenerateXDSLDialectAction,
    ) -> tuple[bool, str, list[str]]:
        from compgen.extensions.xdsl_generate import generate_xdsl_dialect

        diagnostics: list[str] = []
        pack = self._find_loaded_pack(action.pack_name)
        if pack is None:
            return False, f"Unknown pack '{action.pack_name}'", diagnostics

        branch = pack.pack.branch_plan(run_id=f"step-{self._step_count}")
        spec = action.spec or self._default_dialect_spec(pack)
        files = generate_xdsl_dialect(spec)
        emitted = self._write_generated_bundle(
            branch=branch,
            subdir=f"generated/xdsl/{pack.manifest.name}",
            files=files,
        )
        self._runtime_artifacts.setdefault("xdsl_dialects", {})
        self._runtime_artifacts["xdsl_dialects"][pack.manifest.name] = {
            "branch_name": branch.branch_name,
            "worktree_path": str(branch.worktree_path),
            "files": emitted,
        }
        diagnostics.append(
            f"Generated xDSL dialect scaffold for {pack.manifest.name} at {branch.worktree_path}"
        )
        diagnostics.extend(f"  {name} -> {path}" for name, path in emitted.items())
        return True, "", diagnostics

    def _apply_generate_llvm_patch(
        self, action: GenerateLLVMPatchAction,
    ) -> tuple[bool, str, list[str]]:
        from compgen.extensions.llvm_patchgen import generate_llvm_patch_bundle

        diagnostics: list[str] = []
        pack = self._find_loaded_pack(action.pack_name)
        if pack is None:
            return False, f"Unknown pack '{action.pack_name}'", diagnostics

        branch = pack.pack.branch_plan(run_id=f"step-{self._step_count}")
        spec = action.spec or self._default_llvm_patch_spec(pack)
        files = generate_llvm_patch_bundle(spec)
        emitted = self._write_generated_bundle(
            branch=branch,
            subdir=f"generated/llvm/{pack.manifest.name}",
            files=files,
        )
        self._runtime_artifacts.setdefault("llvm_patches", {})
        self._runtime_artifacts["llvm_patches"][pack.manifest.name] = {
            "branch_name": branch.branch_name,
            "worktree_path": str(branch.worktree_path),
            "llvm_fork_path": str(branch.llvm_fork_path) if branch.llvm_fork_path else "",
            "files": emitted,
        }
        diagnostics.append(
            f"Generated LLVM patch scaffold for {pack.manifest.name} at {branch.worktree_path}"
        )
        diagnostics.extend(f"  {name} -> {path}" for name, path in emitted.items())
        return True, "", diagnostics

    # ------------------------------------------------------------------
    # Core transform actions
    # ------------------------------------------------------------------

    def _apply_tile(self, action: TileAction) -> tuple[bool, str, list[str]]:
        """Apply tiling to a region by running the tiling pass on the module."""
        diagnostics: list[str] = []

        if self._module is None:
            return False, "No module loaded", diagnostics

        if not action.tile_sizes:
            return False, "No tile sizes specified", diagnostics

        try:
            from xdsl.transforms.linalg_to_loops import LinalgTiledLoopOp  # noqa: F401

            # Clone, apply tiling annotation, verify, re-extract
            cloned = self._module.clone()
            # Mark region as tiled in metadata — the actual tiling transform
            # will be applied when Recipe IR is lowered and executed
            cloned.verify()
            self._module = cloned
            self._regions = self._extract_regions(self._module, self._target)

            sizes_str = ",".join(str(s) for s in action.tile_sizes)
            diagnostics.append(f"Tiled {action.region_id} with sizes [{sizes_str}]")
            return True, "", diagnostics
        except ImportError:
            # Fallback: accept the tiling decision without applying the pass
            sizes_str = ",".join(str(s) for s in action.tile_sizes)
            diagnostics.append(f"Tiled {action.region_id} with sizes [{sizes_str}] (deferred to recipe)")
            return True, "", diagnostics
        except Exception as e:
            return False, f"Tiling failed: {e}", diagnostics

    def _apply_fuse(self, action: FuseAction) -> tuple[bool, str, list[str]]:
        """Apply fusion between two regions."""
        diagnostics: list[str] = []

        if self._module is None:
            return False, "No module loaded", diagnostics

        target_id = getattr(action, "target_region_id", "")
        if not action.region_id:
            return False, "No region_id specified", diagnostics

        # Fusion is recorded as a decision; actual transform applied via recipe
        diagnostics.append(
            f"Fused {action.region_id}"
            + (f" with {target_id}" if target_id else " (producer-consumer)")
        )
        return True, "", diagnostics

    def _apply_insert_copy(self, action: InsertCopyAction) -> tuple[bool, str, list[str]]:
        """Insert a copy boundary between two regions."""
        diagnostics: list[str] = []

        if not action.region_id:
            return False, "No region_id specified", diagnostics

        target_id = getattr(action, "target_region_id", "")
        is_async = getattr(action, "async_", False)
        diagnostics.append(
            f"Copy boundary: {action.region_id} → {target_id or '(next)'}"
            + (" (async)" if is_async else "")
        )
        return True, "", diagnostics

    def _apply_set_dtype(self, action: SetDtypeAction) -> tuple[bool, str, list[str]]:
        """Set the dtype for a region."""
        diagnostics: list[str] = []

        if not action.region_id:
            return False, "No region_id specified", diagnostics

        new_dtype = getattr(action, "dtype", "f16")

        # Update the region's dtype in our tracking
        for i, r in enumerate(self._regions):
            if r.region_id == action.region_id:
                self._regions[i] = RegionInfo(
                    region_id=r.region_id, op_type=r.op_type,
                    input_shapes=r.input_shapes, output_shapes=r.output_shapes,
                    flops=r.flops, bytes_in=r.bytes_in, bytes_out=r.bytes_out,
                    arithmetic_intensity=r.arithmetic_intensity,
                    estimated_latency_us=r.estimated_latency_us,
                    device_index=r.device_index,
                    is_compute_bound=r.is_compute_bound, dtype=new_dtype,
                    consumers=r.consumers, producers=r.producers,
                )
                diagnostics.append(f"Set dtype of {action.region_id} to {new_dtype}")
                return True, "", diagnostics

        return False, f"Region {action.region_id} not found", diagnostics

    def _apply_propose_rule(self, action: ProposeRuleAction) -> tuple[bool, str, list[str]]:
        """Validate and optionally verify a proposed eqsat rule."""
        diagnostics: list[str] = []

        if not action.rule_code:
            return False, "No rule code provided", diagnostics

        from compgen.eqsat.llm_interface import validate_and_verify_rule

        result = validate_and_verify_rule(action.rule_code)
        if result.valid:
            # Store rule for subsequent EqSatAction use (Unit 3)
            if not hasattr(self, "_session_rules"):
                self._session_rules = []
            self._session_rules.append(result.rule)
            diagnostics.append(f"Rule '{result.rule.name}' validated and registered for session")
            return True, "", diagnostics
        else:
            return False, f"Rule validation failed: {result.error}", diagnostics

    # ------------------------------------------------------------------
    # Verification actions
    # ------------------------------------------------------------------

    def _apply_request_verification(
        self, action: RequestVerificationAction,
    ) -> tuple[bool, str, list[str]]:
        """Run formal verification on a region."""
        diagnostics: list[str] = []

        if self._module is None:
            return False, "No module loaded", diagnostics

        if not action.region_id:
            return False, "No region_id specified", diagnostics

        from compgen.semantic.executor import VerificationExecutor

        executor = VerificationExecutor()
        obligation = {
            "type": action.level,
            "region_id": action.region_id,
        }

        before = self._best_module if self._best_module is not None else self._module
        result = executor.execute_single(
            obligation,
            payload_before=before,
            payload_after=self._module,
        )

        diagnostics.append(
            f"verification({action.level}): {result.status} for {action.region_id}"
        )
        if result.counterexample:
            diagnostics.append(f"  counterexample: {result.counterexample.summary}")

        # Store result for observation
        self._verification_results.append(result)

        return True, "", diagnostics

    def _apply_request_semantics(
        self, action: RequestSemanticsAction,
    ) -> tuple[bool, str, list[str]]:
        """Request LLM to generate semantics for an op type."""
        diagnostics: list[str] = []
        diagnostics.append(
            f"semantics_request: {action.op_type} — "
            "queued for LLM generation (handled in compilation loop)"
        )
        self._pending_semantics_requests.append(action.op_type)
        return True, "", diagnostics

    def _apply_request_transfer_analysis(
        self, action: RequestTransferAnalysisAction,
    ) -> tuple[bool, str, list[str]]:
        """Run a verified transfer analysis and materialize facts."""
        diagnostics: list[str] = []

        if not action.region_id:
            return False, "No region_id specified", diagnostics

        from compgen.semantic.backends.xdsl_smt.transfer_analyses import TransferAnalysisBridge

        bridge = TransferAnalysisBridge()

        # Gather region properties
        region_props: dict[str, Any] = {}
        for r in self._regions:
            if r.region_id == action.region_id:
                region_props = {
                    "shapes": list(r.input_shapes) + list(r.output_shapes),
                    "bytes_in": r.bytes_in,
                    "bytes_out": r.bytes_out,
                    "dtype": r.dtype,
                }
                break

        facts = bridge.analyze_and_materialize(
            region_id=action.region_id,
            analysis_type=action.analysis_type,
            region_properties=region_props,
        )

        for fact in facts:
            diagnostics.append(
                f"verified_fact: {fact.kind} for {fact.region_id} — {fact.payload}"
            )
            self._verified_facts.append(fact)

        return True, "", diagnostics

    @property
    def runtime_artifacts(self) -> dict[str, Any]:
        """Get all generated runtime artifacts."""
        return dict(self._runtime_artifacts)

    @property
    def generated_hooks(self) -> dict[str, str]:
        """Get all generated hook code."""
        return dict(self._generated_hooks)

    @property
    def analysis(self) -> Any:
        """Get the current network analysis (None if not yet run)."""
        return self._analysis

    def best_module(self) -> ModuleOp | None:
        """Get the best module seen during this episode."""
        return self._best_module

    def _make_observation(self) -> Observation:
        """Build the current observation."""
        assert self._target is not None

        device_names = tuple(d.name for d in self._target.devices)
        device_memory = tuple(
            max((ml.size_bytes for ml in d.memory_hierarchy), default=0)
            for d in self._target.devices
        )
        graph_break_count = 0
        guard_count = 0
        unsupported_ops: tuple[str, ...] = ()
        if self._capture_artifact is not None:
            diagnostics = getattr(self._capture_artifact, "diagnostics", None)
            graph_break_count = len(getattr(diagnostics, "graph_breaks", ()) or ())
            guard_count = len(getattr(diagnostics, "guard_observations", ()) or ())
            unsupported_ops = tuple(
                resolution.target
                for resolution in getattr(self._capture_artifact, "unsupported_resolutions", ())
            )
        pack_context = self._pack_context or PackContextSummary()

        return Observation(
            regions=tuple(self._regions),
            total_flops=sum(r.flops for r in self._regions),
            total_bytes=sum(r.bytes_in + r.bytes_out for r in self._regions),
            estimated_total_latency_us=self._current_cost,
            num_devices=len(self._target.devices),
            device_names=device_names,
            device_memory_bytes=device_memory,
            objective=self._objective,
            step_count=self._step_count,
            budget_remaining=self._budget - self._step_count,
            best_latency_us=self._best_cost,
            history_summary=tuple(self._history[-10:]),
            graph_break_count=graph_break_count,
            guard_count=guard_count,
            unsupported_ops=unsupported_ops,
            analysis_dossier=getattr(self._analysis, "dossier", None),
            active_packs=pack_context.active_packs,
            sealed_surfaces=pack_context.sealed_surfaces,
            generation_apertures=pack_context.generation_apertures,
            available_profilers=pack_context.available_profilers,
            pack_benchmark_targets=pack_context.benchmark_targets,
            integration_branch=pack_context.integration_branch,
        )


__all__ = [
    "Action",
    "AnalyzeAction",
    "ApplyPassAction",
    "AssignDeviceAction",
    "BenchmarkAction",
    "CalibrateAction",
    "CheckpointAction",
    "CompileAndRunAction",
    "ConfigureDispatchAction",
    "ConfigureProfilingAction",
    "CompilerEnv",
    "DiscoverOpsAction",
    "EqSatAction",
    "FuseAction",
    "GenerateLLVMPatchAction",
    "GeneralizeAction",
    "GeneratePassAction",
    "GenerateRuntimeHooksAction",
    "GenerateXDSLDialectAction",
    "InspectAction",
    "InsertCopyAction",
    "LegalAction",
    "NoopAction",
    "Observation",
    "RequestSemanticsAction",
    "RequestTransferAnalysisAction",
    "RequestVerificationAction",
    "RegionInfo",
    "RollbackAction",
    "SearchKernelAction",
    "SetDtypeAction",
    "SolveAction",
    "StepInfo",
    "StepResult",
    "TileAction",
]
