import numpy as np, sapien.core as sapien
import sapien as _s; print("sapien", _s.__version__)
engine = sapien.Engine()
renderer = sapien.SapienRenderer()
engine.set_renderer(renderer)
scene = engine.create_scene()
scene.set_timestep(1/100)
scene.add_ground(0)
b = scene.create_actor_builder()
b.add_box_collision(half_size=[0.1]*3); b.add_box_visual(half_size=[0.1]*3, color=[1,0,0])
box = b.build(); box.set_pose(sapien.Pose([0,0,0.5]))
scene.set_ambient_light([0.5,0.5,0.5]); scene.add_directional_light([0,1,-1],[1,1,1])
cam = scene.add_camera("c", 128, 128, 1.0, 0.1, 100)
cam.set_pose(sapien.Pose([-1,0,1], [0.9238795,0,0.3826834,0]))
for _ in range(10): scene.step()
scene.update_render(); cam.take_picture()
rgba = cam.get_float_texture("Color")
img = (rgba[...,:3]*255).astype(np.uint8)
print("RENDER OK", img.shape, "mean px", img.mean().round(2), "nonzero frac", (img>0).mean().round(3))
import imageio; imageio.imwrite("sapien_smoke.png", img)
