"""Zephyr ``main.c`` generator for the Saturn OPU ConvNet bring-up.

Real Python file (no shell-heredoc string escaping). Bakes a golden
input tensor into the generated ``main.c`` as a C array, emits a Zephyr
app that copies it into the input buffer, runs ``compgen_invoke``, and
hex-dumps the output bytes over UART. A companion host script parses
the UART log and diffs against ``golden_outputs.pt``.

Lives in ``extensions/zephyr`` because it's a Zephyr-specific overlay
helper — the same family as ``overlay.py``. Keeping it as a Python
module (not a template file) because the generated C is short enough
(~50 lines) that a template adds more indirection than value, and the
input-blob encoding wants Python-side control.
"""

from __future__ import annotations

from pathlib import Path


def _c_byte_array(data: bytes, name: str, *, width: int = 32) -> str:
    rows = []
    for start in range(0, len(data), width):
        chunk = data[start : start + width]
        rows.append("    " + ", ".join(f"0x{b:02x}" for b in chunk))
    body = ",\n".join(rows)
    return f"static const uint8_t {name}[] __attribute__((aligned(16))) = {{\n{body}\n}};\n"


def emit_convnet_main_c(
    out_path: Path,
    *,
    golden_input_bytes: bytes,
    arena_bytes: int = 1 << 20,
) -> Path:
    """Write a Zephyr ``main.c`` that runs CompGen's ConvNet end-to-end.

    Args:
        out_path: Destination ``main.c`` path. Usually
            ``<zephyr_root>/samples/compgen_convnet/src/main.c``.
        golden_input_bytes: Raw little-endian float32 bytes of the
            golden input tensor (must match ``COMPGEN_MODEL_INPUT_BYTES``
            for the target model). This is embedded into the ELF so
            Spike has a deterministic input without filesystem IO.
        arena_bytes: Size of the activation arena baked into BSS. Must
            be ≥ the lowered model's ``arena_bytes``.

    Returns:
        ``out_path`` for convenience.
    """
    input_blob = _c_byte_array(golden_input_bytes, "compgen_input_bytes")
    source = f"""/* SPDX-License-Identifier: Apache-2.0 */
/* Auto-generated by compgen.extensions.zephyr.convnet_main.
 *
 * End-to-end Zephyr harness for the Saturn OPU ConvNet bring-up:
 *   1. Copy the baked-in golden input into the runtime's input buffer.
 *   2. Call compgen_init / compgen_invoke.
 *   3. Hex-dump the 64 output bytes over UART. A host Python script
 *      reconstructs the float32 outputs and diffs them against
 *      golden_outputs.pt with np.allclose(rtol=1e-3, atol=1e-3).
 *   4. Exit Spike cleanly via sys_reboot(SYS_REBOOT_COLD) so the
 *      outer timeout doesn't fire.
 */

#include <stdio.h>
#include <string.h>
#include <zephyr/kernel.h>
#include <zephyr/sys/reboot.h>
#include "compgen_model.h"

{input_blob}

static uint8_t compgen_arena[{arena_bytes}u] __attribute__((aligned(16)));
static uint8_t compgen_input[COMPGEN_MODEL_INPUT_BYTES] __attribute__((aligned(16)));
static uint8_t compgen_output[COMPGEN_MODEL_OUTPUT_BYTES] __attribute__((aligned(16)));

int main(void) {{
    printf("compgen: boot in=%zu out=%zu blob_in=%zu arena=%zu\\n",
           (size_t)COMPGEN_MODEL_INPUT_BYTES,
           (size_t)COMPGEN_MODEL_OUTPUT_BYTES,
           sizeof(compgen_input_bytes),
           sizeof(compgen_arena));
    fflush(stdout);

    memcpy(compgen_input, compgen_input_bytes, sizeof(compgen_input_bytes));

    int rc = compgen_init(compgen_arena, sizeof(compgen_arena));
    printf("compgen: init rc=%d\\n", rc);
    fflush(stdout);

    uint32_t t0 = k_cycle_get_32();
    rc = compgen_invoke(compgen_input, sizeof(compgen_input),
                        compgen_output, sizeof(compgen_output));
    uint32_t t1 = k_cycle_get_32();
    printf("compgen: invoke rc=%d dt_cycles=%u\\n", rc, (unsigned)(t1 - t0));
    fflush(stdout);

    /* Dump the full output buffer as hex; the host reconstructs floats. */
    printf("compgen: out_hex=");
    for (size_t i = 0; i < sizeof(compgen_output); ++i) {{
        printf("%02x", compgen_output[i]);
    }}
    printf("\\ncompgen: done\\n");
    fflush(stdout);

    compgen_shutdown();
    sys_reboot(SYS_REBOOT_COLD);
    return 0;
}}
"""
    out_path.write_text(source)
    return out_path


__all__ = ["emit_convnet_main_c"]
