"""Zephyr overlay generator for CompGen bundles.

Produces a ``samples/<name>/`` directory inside a local clone of
``ucb-bar/zephyr-chipyard-sw`` that links a CompGen-produced static
library + model blob into a Zephyr ``app``. The generated app runs on
``spike_riscv64`` (for functional bring-up) and later on
FireSim/``SaturnOPUConfig`` (for OPU RTL verification) without any
source changes — only the board argument to ``west build`` differs.

Design constraints:
    - All working memory comes from statically allocated arenas placed
      in ``input_data_sec`` — no ``k_malloc``, no picolibc heap churn.
    - The CompGen C ABI (``compgen_init``/``compgen_invoke``/
      ``compgen_shutdown``) is the only surface the Zephyr app sees.
      Keeps the app agnostic to how the model was compiled.
    - Mirrors the layout of
      ``zephyr-chipyard-sw/samples/executorch/executor_runner/`` so
      Chipyard developers already familiar with that sample need no
      training to read ours.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path
from textwrap import dedent


@dataclass(frozen=True)
class ZephyrOverlayOptions:
    """Options controlling overlay emission.

    Attributes:
        sample_name: Directory name under ``samples/`` (e.g.
            ``"compgen_convnet"``).
        project_name: CMake ``project()`` name.
        board: Default Zephyr board (``"spike_riscv64"`` is the default
            wiring in ``zephyr-chipyard-sw@dev``).
        arena_bytes: Size of the static activation/scratch arena in
            ``input_data_sec`` (default 8 MiB — convnet goldens fit
            comfortably).
        input_shape_comment: Human-readable description of the input
            shape written into ``src/main.c`` for diagnostics.
        output_shape_comment: Human-readable description of the output
            shape.
        smp: Whether to enable ``CONFIG_SMP``.
        mp_max_num_cpus: Max CPUs for SMP (ignored if ``smp=False``).
        enable_rvv: Enable the ``+v`` RISC-V vector extension in
            Zephyr's Kconfig.
        model_input_bytes: Runtime input buffer size in bytes (used to
            size the embedded input-blob section).
        model_output_bytes: Runtime output buffer size in bytes.
    """

    sample_name: str = "compgen_convnet"
    project_name: str = "compgen_convnet"
    board: str = "spike_riscv64"
    arena_bytes: int = 64 * 1024  # small default; overlay caller sizes per model
    input_shape_comment: str = "unknown"
    output_shape_comment: str = "unknown"
    smp: bool = False
    mp_max_num_cpus: int = 1
    enable_rvv: bool = True
    model_input_bytes: int = 0
    model_output_bytes: int = 0


@dataclass(frozen=True)
class OverlayPaths:
    """Absolute paths to every file the overlay writes."""

    root: Path
    cmake_lists: Path
    prj_conf: Path
    custom_sections_ld: Path
    main_c: Path
    compgen_lib: Path
    model_blob: Path
    model_header: Path
    input_blob: Path | None = None


@dataclass(frozen=True)
class OverlayResult:
    """Return value of :func:`emit_overlay`."""

    paths: OverlayPaths
    build_command: str
    run_commands: dict[str, str] = field(default_factory=dict)


def _prj_conf(options: ZephyrOverlayOptions) -> str:
    lines = [
        "# Auto-generated by compgen.extensions.zephyr.overlay. Do not edit by hand.",
        "CONFIG_MAIN_STACK_SIZE=32768",
        "CONFIG_THREAD_STACK_INFO=y",
        "CONFIG_GNU_C_EXTENSIONS=y",
        "CONFIG_STD_C17=y",
        "CONFIG_PICOLIBC=y",
        "CONFIG_COMMON_LIBC_MALLOC=y",
        "CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=1048576",
        "CONFIG_FPU=y",
    ]
    if options.smp:
        lines += [
            "CONFIG_SMP=y",
            f"CONFIG_MP_MAX_NUM_CPUS={options.mp_max_num_cpus}",
            "CONFIG_DYNAMIC_THREAD=y",
            "CONFIG_SCHED_CPU_MASK=y",
        ]
    else:
        lines += [
            "CONFIG_SMP=n",
            "CONFIG_MP_MAX_NUM_CPUS=1",
        ]
    if options.enable_rvv:
        # RVV requires a Zephyr-supported V extension Kconfig. The V config
        # guard that the Zephyr SDK's SOC definitions expose may not exist
        # on all boards (e.g. spike_riscv64's rocketchip_virt_riscv64 SoC).
        # We silently skip the line rather than generating a build-breaking
        # setting; callers can add it back via an overlay prj.conf.
        pass
    lines.append("")
    return "\n".join(lines)


def _custom_sections_ld_unused() -> str:  # noqa: N802 — kept for docs
    """Retained for reference; no longer emitted.

    Earlier iterations added custom-sections.ld via
    ``zephyr_linker_sources(DATA_SECTIONS …)`` and placed the arena /
    blob in dedicated sections. On ``spike_riscv64`` this tripped the
    Zephyr linker's ``--orphan-handling=warn`` guard and overflowed the
    ``IDT_LIST`` region. Plain BSS placement (no named sections)
    sidesteps the problem without losing any functionality.
    """
    return _custom_sections_ld_legacy()


def _custom_sections_ld_legacy() -> str:
    # Mirror zephyr-chipyard-sw/samples/executorch/executor_runner/custom-sections.ld
    # with section names renamed to compgen_*. Zephyr's
    # zephyr_linker_sources(DATA_SECTIONS ...) splices this into the
    # data region between .data and .bss, inside GROUP_DATA_LINK_IN so
    # it lives in RAM at runtime but loads from ROM.
    return dedent(
        """\
        /* SPDX-License-Identifier: Apache-2.0 */
        /* Auto-generated by compgen.extensions.zephyr.overlay. */

        SECTION_DATA_PROLOGUE(_COMPGEN_SECTIONS,,)
        {
            . = ALIGN(16);
            __compgen_section_start = .;
            KEEP(*(".got"));
            . = ALIGN(16);
            KEEP(*(".got.plt"));
            . = ALIGN(16);
            KEEP(*("input_data_sec"));
            . = ALIGN(16);
            KEEP(*("compgen_model_sec"));
            . = ALIGN(16);
            KEEP(*("compgen_arena_sec"));
            . = ALIGN(16);
            KEEP(*("compgen_input_sec"));
            . = ALIGN(16);
            KEEP(*(".tbss"));
            __compgen_section_end = ALIGN(4);
        } GROUP_DATA_LINK_IN(RAMABLE_REGION, ROMABLE_REGION)
        """
    )


def _cmake_lists(options: ZephyrOverlayOptions) -> str:
    # Matches the Zephyr hello_world sample shape plus a prebuilt
    # imported library holding the CompGen runtime + ukernels. No
    # custom linker sections — placement uses BSS/.rodata defaults.
    return dedent(
        f"""\
        # SPDX-License-Identifier: Apache-2.0
        # Auto-generated by compgen.extensions.zephyr.overlay.

        cmake_minimum_required(VERSION 3.20.0)

        find_package(Zephyr REQUIRED HINTS $ENV{{ZEPHYR_BASE}})
        project({options.project_name})

        add_library(compgen_model STATIC IMPORTED GLOBAL)
        set_target_properties(compgen_model PROPERTIES
            IMPORTED_LOCATION ${{CMAKE_CURRENT_SOURCE_DIR}}/libcompgen_model.a
            INTERFACE_INCLUDE_DIRECTORIES ${{CMAKE_CURRENT_SOURCE_DIR}}
        )

        target_link_libraries(app PRIVATE compgen_model)
        target_sources(app PRIVATE
            src/main.c
            model_blob.c
        )
        target_include_directories(app PRIVATE ${{CMAKE_CURRENT_SOURCE_DIR}})
        """
    )


def _main_c(options: ZephyrOverlayOptions) -> str:
    # The main function uses printf (picolibc) + sys_reboot — the same
    # pattern Zephyr's hello_world sample on spike_riscv64 uses to flush
    # output through HTIF and exit cleanly. Prior revisions used printk
    # + named linker sections; both caused orphan-section placement
    # failures on spike_riscv64 (arena landed in IDT_LIST). Plain BSS
    # avoids the whole class of issues.
    in_bytes = max(options.model_input_bytes, 16)
    out_bytes = max(options.model_output_bytes, 16)
    return dedent(
        f"""\
        /* SPDX-License-Identifier: Apache-2.0 */
        /* Auto-generated by compgen.extensions.zephyr.overlay. */

        #include <stdint.h>
        #include <stddef.h>
        #include <stdio.h>
        #include <zephyr/kernel.h>
        #include <zephyr/sys/reboot.h>

        #include "compgen_model.h"

        /* Input shape: {options.input_shape_comment} */
        /* Output shape: {options.output_shape_comment} */

        /* Plain BSS placement; Zephyr's default RAM region is large enough. */
        #define COMPGEN_ARENA_BYTES {options.arena_bytes}u
        static uint8_t compgen_arena[COMPGEN_ARENA_BYTES] __attribute__((aligned(16)));
        static uint8_t compgen_input[{in_bytes}] __attribute__((aligned(16)));
        static uint8_t compgen_output[{out_bytes}] __attribute__((aligned(16)));

        /* Zephyr-native PAL overrides of the weak defaults in libcompgen_model.a. */
        void compgen_pal_log(int level, const char *msg)
        {{
            (void)level;
            printf("compgen: %s\\n", msg);
        }}

        uint64_t compgen_pal_time_ns(void)
        {{
            return (uint64_t)k_cycle_get_32() * NSEC_PER_SEC
                   / sys_clock_hw_cycles_per_sec();
        }}

        void compgen_pal_abort(void)
        {{
            printf("compgen: abort\\n");
            fflush(stdout);
            sys_reboot(SYS_REBOOT_COLD);
        }}

        int main(void)
        {{
            printf("compgen: starting sample '{options.sample_name}' "
                   "board='{options.board}' in=%zu out=%zu\\n",
                   (size_t)COMPGEN_MODEL_INPUT_BYTES,
                   (size_t)COMPGEN_MODEL_OUTPUT_BYTES);
            fflush(stdout);

            int rc = compgen_init(compgen_arena, sizeof(compgen_arena));
            if (rc != 0) {{
                printf("compgen: init failed (%d)\\n", rc);
                fflush(stdout);
                sys_reboot(SYS_REBOOT_COLD);
                return rc;
            }}

            rc = compgen_invoke(compgen_input, sizeof(compgen_input),
                                compgen_output, sizeof(compgen_output));
            if (rc != 0) {{
                printf("compgen: invoke failed (%d)\\n", rc);
                compgen_shutdown();
                fflush(stdout);
                sys_reboot(SYS_REBOOT_COLD);
                return rc;
            }}

            printf("compgen: invoke ok magic=0x%02x out_bytes=%u\\n",
                   compgen_output[0], (unsigned)sizeof(compgen_output));
            printf("compgen: out[0..16]=");
            for (size_t i = 0; i < 16 && i < sizeof(compgen_output); ++i) {{
                printf("%02x ", compgen_output[i]);
            }}
            printf("\\ncompgen: done\\n");
            fflush(stdout);

            compgen_shutdown();
            sys_reboot(SYS_REBOOT_COLD);
            return 0;
        }}
        """
    )


def emit_overlay(
    bundle_dir: Path,
    zephyr_root: Path,
    options: ZephyrOverlayOptions = ZephyrOverlayOptions(),
) -> OverlayResult:
    """Emit a Zephyr sample overlay into ``zephyr_root/samples/<name>/``.

    Args:
        bundle_dir: Directory containing the CompGen embedded-runtime
            artifacts (``libcompgen_model.a``, ``model_blob.c``,
            ``compgen_model.h``). Must already exist and contain all
            three files.
        zephyr_root: Path to a local clone of
            ``ucb-bar/zephyr-chipyard-sw``. The overlay is written to
            ``<zephyr_root>/samples/<options.sample_name>/``.
        options: Overlay configuration. Defaults target
            ``spike_riscv64`` with 8 MiB arena + RVV enabled.

    Returns:
        :class:`OverlayResult` describing every file written plus a
        ready-to-run ``west build`` command line.

    Raises:
        FileNotFoundError: If any required CompGen artifact is missing
            from ``bundle_dir`` or ``zephyr_root`` is not a Zephyr
            sample tree.
    """
    bundle_dir = Path(bundle_dir).resolve()
    zephyr_root = Path(zephyr_root).resolve()

    required = {
        "libcompgen_model.a": bundle_dir / "libcompgen_model.a",
        "model_blob.c": bundle_dir / "model_blob.c",
        "compgen_model.h": bundle_dir / "compgen_model.h",
    }
    missing = [name for name, path in required.items() if not path.exists()]
    if missing:
        raise FileNotFoundError(
            f"Bundle {bundle_dir} is missing required artifact(s): {sorted(missing)}"
        )

    samples_dir = zephyr_root / "samples"
    if not samples_dir.is_dir():
        raise FileNotFoundError(
            f"{zephyr_root} does not look like a zephyr-chipyard-sw clone "
            f"(missing samples/ directory)"
        )

    overlay_root = samples_dir / options.sample_name
    src_dir = overlay_root / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    cmake_lists = overlay_root / "CMakeLists.txt"
    prj_conf = overlay_root / "prj.conf"
    custom_sections = overlay_root / "custom-sections.ld"
    main_c = src_dir / "main.c"
    compgen_lib = overlay_root / "libcompgen_model.a"
    model_blob = overlay_root / "model_blob.c"
    model_header = overlay_root / "compgen_model.h"
    input_blob = None
    input_blob_src = bundle_dir / "input_blob.c"
    if input_blob_src.exists():
        input_blob = overlay_root / "input_blob.c"
        shutil.copy2(input_blob_src, input_blob)

    cmake_lists.write_text(_cmake_lists(options))
    prj_conf.write_text(_prj_conf(options))
    # custom_sections.ld is still emitted for documentation / future
    # use, but no longer referenced by CMakeLists.txt. Overlays that
    # want named sections can re-add a zephyr_linker_sources() call.
    custom_sections.write_text(_custom_sections_ld_legacy())
    main_c.write_text(_main_c(options))
    shutil.copy2(required["libcompgen_model.a"], compgen_lib)
    shutil.copy2(required["model_blob.c"], model_blob)
    shutil.copy2(required["compgen_model.h"], model_header)

    build_cmd = (
        f"west build -p -b {options.board} samples/{options.sample_name}/"
    )
    run_commands = {
        "spike": "spike --isa=rv64gcv build/zephyr/zephyr.elf",
        "firesim": (
            "firesim runworkload -c "
            f"deploy/workloads/{options.sample_name}.json"
        ),
    }

    return OverlayResult(
        paths=OverlayPaths(
            root=overlay_root,
            cmake_lists=cmake_lists,
            prj_conf=prj_conf,
            custom_sections_ld=custom_sections,
            main_c=main_c,
            compgen_lib=compgen_lib,
            model_blob=model_blob,
            model_header=model_header,
            input_blob=input_blob,
        ),
        build_command=build_cmd,
        run_commands=run_commands,
    )


__all__ = [
    "OverlayPaths",
    "OverlayResult",
    "ZephyrOverlayOptions",
    "emit_overlay",
]
