/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 25
#define FLOWC_N_LANES 14

static const int flowc_e9_deps[] = { 2 };
static const int flowc_e16_deps[] = { 1 };
static const int flowc_e19_deps[] = { 7 };
static const int flowc_e23_deps[] = { 12 };
static const int flowc_e24_deps[] = { 21 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.000000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 1, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 0.000000, 13.267000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 1, 103, 0, 102 },
    { 2, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 0.000000, 13.909000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 2, 103, 0, 102 },
    { 3, "dronet", 0, 0, "qnn_graph", "dronet_full", "cpu", 5, 0.107000, 6.998000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_dronet_full_hta__Cpu.bin", "dronet_full_hta", 0, 3, 24, 0, 23 },
    { 4, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 7.105000, 0.107000, 0, NULL, 3, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 5, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 10.000000, 0.107000, 0, NULL, 4, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 6, "dronet", 1, 0, "qnn_graph", "dronet_full", "dsp", 6, 13.267000, 0.645000, 0, NULL, 1, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 4, 24, 0, 23 },
    { 7, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 13.909000, 13.909000, 0, NULL, 2, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 5, 103, 0, 102 },
    { 8, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 15.000000, 0.107000, 0, NULL, 5, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 9, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 16.012000, 15.377000, 1, flowc_e9_deps, 6, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 6, 146, 103, 248 },
    { 10, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 20.788000, 0.107000, 0, NULL, 8, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 11, "dronet", 2, 0, "qnn_graph", "dronet_full", "cpu", 5, 20.895000, 6.998000, 0, NULL, 8, "CPU", "libQnnCpu.so", "ctx_dronet_full_hta__Cpu.bin", "dronet_full_hta", 0, 3, 24, 0, 23 },
    { 12, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 27.818000, 13.909000, 0, NULL, 2, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 7, 103, 0, 102 },
    { 13, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 27.893000, 0.107000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 14, "mlp_control", 6, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 30.000000, 0.107000, 0, NULL, 13, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 15, "dronet", 3, 0, "qnn_graph", "dronet_full", "dsp", 6, 31.389000, 0.645000, 0, NULL, 6, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 4, 24, 0, 23 },
    { 16, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 32.034000, 15.377000, 1, flowc_e16_deps, 9, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 1, 146, 103, 248 },
    { 17, "mlp_control", 7, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 35.000000, 0.107000, 0, NULL, 14, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 18, "mlp_control", 8, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 40.000000, 0.107000, 0, NULL, 17, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 0, 7, 0, 6 },
    { 19, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "cpu", 5, 40.107000, 39.464000, 1, flowc_e19_deps, 18, "CPU", "libQnnCpu.so", "ctx_yolov8n_head__Cpu.bin", "yolov8n_HTA_split_seg101", 0, 8, 146, 103, 248 },
    { 20, "dronet", 4, 0, "qnn_graph", "dronet_full", "hta", 7, 41.727000, 2.030000, 0, NULL, 12, "HTA", "libQnnHta.so", "ctx_dronet_full_hta__Hta.bin", "dronet_full_hta", 1, 9, 24, 0, 23 },
    { 21, "yolov8n_e", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 43.757000, 13.909000, 0, NULL, 12, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 10, 103, 0, 102 },
    { 22, "mlp_control", 9, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 47.411000, 0.589000, 0, NULL, 15, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 11, 7, 0, 6 },
    { 23, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 48.000000, 15.377000, 1, flowc_e23_deps, 16, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 12, 146, 103, 248 },
    { 24, "yolov8n_e", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 64.194000, 15.377000, 1, flowc_e24_deps, 23, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 13, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "cpu|mlp_control",
    "dsp|yolov8n_c",
    "hta|yolov8n_a",
    "cpu|dronet",
    "dsp|dronet",
    "hta|yolov8n_d",
    "dsp|yolov8n_a",
    "hta|yolov8n_b",
    "cpu|yolov8n_d",
    "hta|dronet",
    "hta|yolov8n_e",
    "dsp|mlp_control",
    "dsp|yolov8n_b",
    "dsp|yolov8n_e",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 5, 6, 7, 4, 6, 7, 6, 7, 5, 7, 7, 6, 6, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 526, 200, 200, 2000, 200, 200, 200, 200, 2000, 200, 200, 200, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 40, 0, 0, 40, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "4,5",
    "6",
    "7",
    "4,5",
    "6",
    "7",
    "6",
    "7",
    "4,5",
    "7",
    "7",
    "6",
    "6",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
