/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 15
#define FLOWC_N_LANES 5

static const int flowc_e3_deps[] = { 2, 0 };
static const int flowc_e9_deps[] = { 5, 6 };
static const int flowc_e13_deps[] = { 10, 12 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 0.129000, 1.568000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 1, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 0.649000, 0.589000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 1, 7, 0, 6 },
    { 2, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 1.238000, 0.459000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 3, "fused_split", 0, 2, "qnn_graph", "fused_tail", "dsp", 6, 1.697000, 4.303000, 2, flowc_e3_deps, 1, "DSP", "libQnnDsp.so", "ctx_fused_tail_from_conv__Dsp.bin", "fused_tail_from_conv", 1, 2, 10, 4, 15 },
    { 4, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 6.893000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 5, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 8.530010, 0.931000, 0, NULL, 0, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 6, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 9.069010, 0.392000, 0, NULL, 3, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 2, 2, 6, 7 },
    { 7, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 9.461010, 0.589000, 0, NULL, 3, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 1, 7, 0, 6 },
    { 8, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 12.000000, 0.107000, 0, NULL, 4, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 9, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 12.107000, 0.354000, 2, flowc_e9_deps, 4, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 4, 10, 4, 15 },
    { 10, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 16.000000, 0.931000, 0, NULL, 5, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 11, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 16.911000, 0.589000, 0, NULL, 7, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 1, 7, 0, 6 },
    { 12, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 16.931000, 1.568000, 0, NULL, 10, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 13, "fused_split", 2, 2, "qnn_graph", "fused_tail", "cpu", 5, 19.646000, 0.354000, 2, flowc_e13_deps, 9, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 4, 10, 4, 15 },
    { 14, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 20.000000, 0.107000, 0, NULL, 9, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "hta|fused_split",
    "dsp|mlp_control",
    "dsp|fused_split",
    "cpu|mlp_control",
    "cpu|fused_split",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 7, 6, 6, 5, 4 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 200, 114, 1276, 1884 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 0, 0, 40, 40 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "7",
    "6",
    "6",
    "4,5",
    "4,5",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
