"""End-to-end Saturn OPU ConvNet pipeline driver.

One Python entry point that produces:

* An embedded bundle (lowered forward + weights + runtime copy)
  via :mod:`compgen.runtime.embedded`.
* A Zephyr sample overlay with golden input baked into ``main.c``
  via :mod:`compgen.extensions.zephyr.convnet_main`.

Does **not** invoke the Zephyr SDK or Spike — those are toolchain
concerns the shell wrapper handles. This module's job is to produce
every source file deterministically from Python, so the pipeline is
scriptable and testable without a C toolchain.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

import torch

from compgen.extensions.zephyr.convnet_main import emit_convnet_main_c
from compgen.runtime.embedded import (
    EmbeddedOptions,
    LoweredModel,
    emit_embedded,
    lower_cnn_to_c,
)


@dataclass
class E2ESpikeArtifacts:
    bundle_dir: Path
    zephyr_sample_dir: Path
    lowered: LoweredModel
    golden_input_bytes: bytes


def _load_golden_input(path: Path) -> torch.Tensor:
    loaded = torch.load(path)
    if isinstance(loaded, (tuple, list)):
        loaded = loaded[0]
    return loaded


def build_e2e_artifacts(
    model_fixture_module: str,
    bundle_dir: Path,
    zephyr_root: Path,
    *,
    sample_name: str = "compgen_convnet",
    golden_input_path: Path | None = None,
) -> E2ESpikeArtifacts:
    """Produce the full pipeline source tree.

    Args:
        model_fixture_module: Python module with ``build_model()`` and
            ``default_inputs()`` returning a ``nn.Module`` in ``eval``.
        bundle_dir: Where to write the embedded bundle (cleared if it
            already exists).
        zephyr_root: Path to a ``zephyr-chipyard-sw`` clone; the
            overlay lands in ``zephyr_root/samples/<sample_name>/``.
        sample_name: Directory name for the Zephyr overlay.
        golden_input_path: Optional path to a saved input tensor. When
            present, those bytes are baked into ``main.c``. Otherwise
            the fixture's ``default_inputs()`` is used.
    """
    import importlib

    mod = importlib.import_module(model_fixture_module)
    model = mod.build_model()
    if golden_input_path is not None:
        inp = _load_golden_input(golden_input_path)
    else:
        inp = mod.default_inputs()[0]
    sample_input_shape = tuple(inp.shape[1:])  # drop batch

    # ------------------------------------------------------------------
    # Lower + emit embedded bundle
    # ------------------------------------------------------------------
    if bundle_dir.exists():
        shutil.rmtree(bundle_dir)
    bundle_dir.mkdir(parents=True)
    lowered = lower_cnn_to_c(
        model, sample_input_shape=sample_input_shape, model_name=sample_name,
    )
    emit_embedded(
        bundle_dir,
        lowered_model=lowered,
        options=EmbeddedOptions(
            model_name=sample_name,
            version="e2e-spike",
            cross_compiler="riscv64-zephyr-elf-gcc",
            archiver="riscv64-zephyr-elf-ar",
            march="rv64imafdc_zicsr_zifencei",
            mabi="lp64d",
            mcpu_features="+m,+a,+f,+d,+c,+zicsr,+zifencei",
        ),
    )

    # ------------------------------------------------------------------
    # Zephyr overlay
    # ------------------------------------------------------------------
    overlay_dir = zephyr_root / "samples" / sample_name
    if overlay_dir.exists():
        shutil.rmtree(overlay_dir)
    (overlay_dir / "src").mkdir(parents=True)

    # CMakeLists.txt: straight Zephyr app that links against the
    # pre-built static library from bundle_dir + includes the runtime
    # header search path so <compgen/types.h> resolves.
    cmake = overlay_dir / "CMakeLists.txt"
    cmake.write_text(
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# Auto-generated by compgen.runtime.embedded.e2e_spike.\n"
        "cmake_minimum_required(VERSION 3.20.0)\n"
        "find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})\n"
        f"project({sample_name})\n"
        "\n"
        "add_library(compgen_model STATIC IMPORTED GLOBAL)\n"
        "set_target_properties(compgen_model PROPERTIES\n"
        "    IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/libcompgen_model.a\n"
        "    INTERFACE_INCLUDE_DIRECTORIES ${CMAKE_CURRENT_SOURCE_DIR}\n"
        ")\n"
        "target_link_libraries(app PRIVATE compgen_model)\n"
        "target_sources(app PRIVATE src/main.c model_blob.c)\n"
        "target_include_directories(app PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})\n"
    )
    (overlay_dir / "prj.conf").write_text("# nothing\n")

    # Copy model_blob (app re-links it) + the public header.
    # ``libcompgen_model.a`` is built by the toolchain step after this
    # Python driver returns — the shell wrapper copies it into the
    # overlay once cross-compile finishes.
    shutil.copy2(bundle_dir / "model_blob.c", overlay_dir / "model_blob.c")
    shutil.copy2(bundle_dir / "compgen_model.h", overlay_dir / "compgen_model.h")
    shutil.copytree(bundle_dir / "compgen", overlay_dir / "compgen")

    # Bake the golden input into main.c.
    golden_bytes = inp.detach().cpu().numpy().astype("<f4").tobytes()
    assert len(golden_bytes) == lowered.input_bytes, (
        f"golden input is {len(golden_bytes)} B but lowered expects {lowered.input_bytes}"
    )
    emit_convnet_main_c(
        overlay_dir / "src" / "main.c",
        golden_input_bytes=golden_bytes,
        arena_bytes=max(lowered.arena_bytes, 1 << 20),
    )

    return E2ESpikeArtifacts(
        bundle_dir=bundle_dir,
        zephyr_sample_dir=overlay_dir,
        lowered=lowered,
        golden_input_bytes=golden_bytes,
    )


__all__ = ["E2ESpikeArtifacts", "build_e2e_artifacts"]
