"""Embedded C ABI runtime emitter for CompGen bundles.

Emits the three artifacts the Zephyr overlay links against:

* ``compgen_model.h`` — stable C ABI (init/invoke/shutdown + PAL hooks).
* ``model_blob.c`` — embedded byte array for model weights/constants,
  placed in the ``compgen_model_sec`` linker section.
* ``compgen_model.c`` — dispatch shell that consumes the arena and
  calls the Exo-generated ukernels (linked in separately). For
  bring-up, a reference implementation is emitted that copies inputs
  through a torch-equivalent scalar fallback; the Exo lane replaces
  the inner call once lands.

A Makefile is also emitted so the source tree builds into
``libcompgen_model.a`` with a cross-compiler via ``make ARCH=riscv64``.
The Python emitter itself does not run the toolchain — tests and the
CLI invoke it explicitly.
"""

from __future__ import annotations

import logging
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from compgen.kernels.providers.exo_riscv_opu import UkernelEmission

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class EmbeddedOptions:
    """Configuration for the embedded emitter.

    Attributes:
        model_name: Logical model name embedded into headers / blob
            symbols. Must be a valid C identifier.
        input_bytes: Flattened input tensor size in bytes.
        output_bytes: Flattened output tensor size in bytes.
        cross_compiler: ``CC`` for the generated Makefile. The default
            matches the Zephyr SDK's RISC-V elf toolchain.
        mcpu_features: ``-mcpu`` feature string for the cross-compiler.
        version: Version string stamped into the runtime so developers
            can diff what they built.
    """

    model_name: str = "compgen_model"
    input_bytes: int = 0
    output_bytes: int = 0
    cross_compiler: str = "riscv64-unknown-elf-gcc"
    archiver: str = "riscv64-unknown-elf-ar"
    mcpu_features: str = "+m,+a,+f,+d,+c,+v,+zvl128b"
    march: str = "rv64gcv_zvl128b"
    mabi: str = "lp64d"
    version: str = "0.0.1-saturn-opu-bringup"


@dataclass(frozen=True)
class EmbeddedArtifacts:
    """Paths to every file :func:`emit_embedded` produces."""

    output_dir: Path
    header: Path
    blob_source: Path
    runtime_source: Path
    makefile: Path
    ukernel_sources: tuple[Path, ...] = ()
    kernel_contracts: Path | None = None
    forward_source: Path | None = None
    ops_header: Path | None = None
    ops_source: Path | None = None
    arena_bytes: int = 0


_HEADER_TEMPLATE = """\
/* SPDX-License-Identifier: Apache-2.0 */
/* Auto-generated by compgen.runtime.embedded. Do not edit by hand. */
/* model: {model_name}   version: {version} */

#ifndef COMPGEN_MODEL_H
#define COMPGEN_MODEL_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {{
#endif

/* Canonical input/output byte sizes at compile time. Kept as macros so
 * callers can size static arenas without linking the runtime first. */
#define COMPGEN_MODEL_INPUT_BYTES  ((size_t){input_bytes}u)
#define COMPGEN_MODEL_OUTPUT_BYTES ((size_t){output_bytes}u)

/* Initialize the runtime. ``arena`` supplies working memory for
 * activations and scratch buffers; must be aligned to 16 bytes.
 * Returns 0 on success, negative errno on failure. Safe to call once
 * per process; subsequent calls after ``compgen_shutdown`` reset
 * state. */
int compgen_init(void *arena, size_t arena_size);

/* Run the model end-to-end. ``in`` holds exactly
 * ``COMPGEN_MODEL_INPUT_BYTES`` of input; ``out`` must have capacity
 * for ``COMPGEN_MODEL_OUTPUT_BYTES``. Returns 0 on success. */
int compgen_invoke(const void *in, size_t in_size,
                   void *out, size_t out_size);

/* Release runtime resources. Idempotent. */
void compgen_shutdown(void);

/* PAL callbacks. Defaults are weak in libcompgen_model.a; the embedder
 * (e.g. Zephyr app) overrides them at link time. */
void compgen_pal_log(int level, const char *msg);
uint64_t compgen_pal_time_ns(void);
void compgen_pal_abort(void);

/* Access to the embedded weights blob. Exposed for diagnostics only;
 * ``compgen_init`` binds the blob into the runtime automatically. */
extern const uint8_t compgen_model_blob[];
extern const size_t compgen_model_blob_size;

#ifdef __cplusplus
}}
#endif

#endif /* COMPGEN_MODEL_H */
"""


_BLOB_TEMPLATE = """\
/* SPDX-License-Identifier: Apache-2.0 */
/* Auto-generated by compgen.runtime.embedded. Do not edit by hand. */
/* model: {model_name}   blob_bytes: {blob_bytes} */

#include <stdint.h>
#include <stddef.h>

/*
 * Weights blob. The Zephyr bring-up ran into orphan-section placement
 * issues when a named section was used (``--orphan-handling=warn``
 * dropped it into IDT_LIST which overflowed). Emitting into the
 * default ``.rodata`` keeps the blob linkable on any target and lets
 * Zephyr's linker script handle placement — custom placement can be
 * layered on top via a board-specific overlay linker snippet.
 */
__attribute__((aligned(16)))
const uint8_t compgen_model_blob[] = {{
{blob_bytes_c_array}
}};

const size_t compgen_model_blob_size = sizeof(compgen_model_blob);
"""


_RUNTIME_TEMPLATE = """\
/* SPDX-License-Identifier: Apache-2.0 */
/* Auto-generated by compgen.runtime.embedded. Do not edit by hand. */
/* model: {model_name}   version: {version} */

#include <stdint.h>
#include <stddef.h>
#include <string.h>

#include "compgen_model.h"

{forward_decl}

/* Weak PAL defaults: host may override at link time. The Zephyr overlay
 * ships strong symbols backed by printk / k_cycle_get_32 / k_panic. */
__attribute__((weak)) void compgen_pal_log(int level, const char *msg) {{
    (void)level; (void)msg;
}}
__attribute__((weak)) uint64_t compgen_pal_time_ns(void) {{ return 0u; }}
__attribute__((weak)) void compgen_pal_abort(void) {{ for (;;) {{}} }}

struct compgen_runtime_state {{
    uint8_t *arena;
    size_t arena_size;
    int initialized;
}};

static struct compgen_runtime_state g_state;

int compgen_init(void *arena, size_t arena_size) {{
    if (arena == NULL || arena_size == 0u) {{
        return -22; /* -EINVAL */
    }}
    if (((uintptr_t)arena & 0xFu) != 0u) {{
        return -22; /* arena must be 16-byte aligned */
    }}
    g_state.arena = (uint8_t *)arena;
    g_state.arena_size = arena_size;
    g_state.initialized = 1;
    compgen_pal_log(0, "compgen_init: ok");
    return 0;
}}

int compgen_invoke(const void *in, size_t in_size,
                   void *out, size_t out_size) {{
    if (!g_state.initialized) {{
        return -1;
    }}
    if (in == NULL || out == NULL) {{
        return -22;
    }}
    if (in_size < COMPGEN_MODEL_INPUT_BYTES ||
        out_size < COMPGEN_MODEL_OUTPUT_BYTES) {{
        return -7; /* -E2BIG */
    }}

{invoke_body}
}}

void compgen_shutdown(void) {{
    g_state.initialized = 0;
    g_state.arena = NULL;
    g_state.arena_size = 0u;
    compgen_pal_log(0, "compgen_shutdown: ok");
}}
"""


_PLACEHOLDER_INVOKE = """\
    /*
     * Placeholder dispatch: no lowered forward was supplied. Zeros the
     * output and stamps a magic byte so the Zephyr harness still sees
     * the call chain complete. When ``emit_embedded(lowered_model=…)``
     * is given a :class:`LoweredModel`, this block is replaced with a
     * direct call into ``compgen_model_forward``.
     */
    memset(out, 0, COMPGEN_MODEL_OUTPUT_BYTES);
    if (COMPGEN_MODEL_OUTPUT_BYTES > 0u) {
        ((uint8_t *)out)[0] = 0xCEu;
    }
    (void)in;
    return 0;
"""


_LOWERED_INVOKE = """\
    /* Dispatch into the lowered model forward. Input and output are
     * raw byte buffers; we reinterpret as float32 here so the forward
     * itself stays typed. */
    int rc = (int)compgen_model_forward(
        (const float *)in, (float *)out, g_state.arena, g_state.arena_size);
    return rc;
"""


_MAKEFILE_TEMPLATE = """\
# Auto-generated by compgen.runtime.embedded. Do not edit by hand.
# Build libcompgen_model.a with the RISC-V elf toolchain.

CC      ?= {cross_compiler}
AR      ?= {archiver}
ARCH    ?= riscv64
MARCH   ?= {march}
MABI    ?= {mabi}
CFLAGS  ?= -O2 -g -ffreestanding -fno-builtin -Wall -Wextra \\
           -march=$(MARCH) -mabi=$(MABI) -I.

SRCS := compgen_model.c model_blob.c
OBJS := $(SRCS:.c=.o)
TARGET := libcompgen_model.a

all: $(TARGET)

$(TARGET): $(OBJS)
\t$(AR) rcs $@ $^

%.o: %.c compgen_model.h
\t$(CC) $(CFLAGS) -c $< -o $@

clean:
\trm -f $(OBJS) $(TARGET)

.PHONY: all clean
"""


def _format_blob_bytes(data: bytes, width: int = 16) -> str:
    """Render bytes as ``0xHH, 0xHH, ...`` comma-separated hex, wrapped."""
    if not data:
        # Keep an explicit zero byte so the symbol is not zero-length
        # (some toolchains place zero-length arrays in .bss which defeats
        # the ``compgen_model_sec`` attribute).
        return "    0x00"
    rows = []
    for start in range(0, len(data), width):
        row = ", ".join(f"0x{b:02x}" for b in data[start : start + width])
        rows.append("    " + row)
    return ",\n".join(rows)


class EmbeddedEmitter:
    """Emit embedded runtime artifacts into an output directory."""

    def __init__(self, options: EmbeddedOptions | None = None) -> None:
        self._options = options or EmbeddedOptions()

    def emit(
        self,
        output_dir: str | Path,
        model_blob: bytes = b"",
        ukernels: Sequence[UkernelEmission] | None = None,
        lowered_model: Any = None,
    ) -> EmbeddedArtifacts:
        """Write all source files into ``output_dir``.

        Args:
            output_dir: Target directory (created if missing).
            model_blob: Byte string with the model weights / constants
                to embed. The blob is placed into ``compgen_model_sec``
                and referenced by ``compgen_model_blob``. May be empty
                for kernel-only smoke tests.
            ukernels: Optional sequence of :class:`UkernelEmission`
                objects from :mod:`compgen.kernels.providers.exo_riscv_opu`.
                Each produces one ``kernels/<name>.c`` file and its
                declaration appears in ``compgen_model.h``. The
                Makefile's ``SRCS`` is extended to compile them into
                ``libcompgen_model.a``.
            lowered_model: Optional :class:`LoweredModel` from
                :func:`compgen.runtime.embedded.lower_cnn_to_c`. When
                supplied, the emitter writes out the lowered forward
                C source + the compgen ops library, and ``compgen_invoke``
                dispatches into ``compgen_model_forward`` instead of the
                placeholder. ``model_blob`` is overridden by the lowered
                model's packed weights, and ``input_bytes`` /
                ``output_bytes`` in :class:`EmbeddedOptions` are replaced
                to match the lowered model's input/output sizes.

        Returns:
            :class:`EmbeddedArtifacts` with the absolute path of every
            file written.
        """
        out = Path(output_dir).resolve()
        out.mkdir(parents=True, exist_ok=True)

        opts = self._options
        if lowered_model is not None:
            # The lowered model's authoritative sizes override the options
            # so callers cannot forget to pass matching values.
            opts = EmbeddedOptions(
                model_name=lowered_model.name,
                input_bytes=lowered_model.input_bytes,
                output_bytes=lowered_model.output_bytes,
                cross_compiler=opts.cross_compiler,
                archiver=opts.archiver,
                mcpu_features=opts.mcpu_features,
                march=opts.march,
                mabi=opts.mabi,
                version=opts.version,
            )
            model_blob = lowered_model.weights_blob
        kernels: tuple[UkernelEmission, ...] = tuple(ukernels or ())

        if kernels:
            kernel_decls = "\n".join("/* Ukernel: " + k.name + " */\n" + k.header_decl for k in kernels)
            extra_decls = f"\n\n/* Exo-generated ukernels */\n{kernel_decls}\n"
        else:
            extra_decls = ""

        header_path = out / "compgen_model.h"
        header_path.write_text(
            _HEADER_TEMPLATE.format(
                model_name=opts.model_name,
                version=opts.version,
                input_bytes=opts.input_bytes,
                output_bytes=opts.output_bytes,
            )
            + extra_decls
        )

        blob_path = out / "model_blob.c"
        blob_path.write_text(
            _BLOB_TEMPLATE.format(
                model_name=opts.model_name,
                blob_bytes=len(model_blob),
                blob_bytes_c_array=_format_blob_bytes(model_blob),
            )
        )

        forward_decl = ""
        invoke_body = _PLACEHOLDER_INVOKE
        if lowered_model is not None:
            forward_decl = (
                '#include "compgen/types.h"\n'
                "cg_status_t compgen_model_forward(const float *input_f32, "
                "float *output_f32, void *arena, size_t arena_size);"
            )
            invoke_body = _LOWERED_INVOKE

        runtime_path = out / "compgen_model.c"
        runtime_path.write_text(
            _RUNTIME_TEMPLATE.format(
                model_name=opts.model_name,
                version=opts.version,
                forward_decl=forward_decl,
                invoke_body=invoke_body,
            )
        )

        forward_src_path: Path | None = None
        ops_header_path: Path | None = None
        ops_src_path: Path | None = None
        if lowered_model is not None:
            # Copy the foundational runtime's real headers + sources
            # into the bundle under ``compgen/`` so the generated
            # forward can use ``#include "compgen/ops.h"`` with no
            # build-time search-path juggling. The runtime tree on
            # disk (``runtime/include/compgen/*`` and ``runtime/src/*``)
            # is the single source of truth.
            import shutil

            runtime_root = Path(__file__).resolve().parents[3].parent / "runtime"
            # ↑ python/compgen/runtime/embedded/emitter.py -> repo root -> runtime/
            include_dst = out / "compgen"
            include_dst.mkdir(exist_ok=True)
            for name in ("types.h", "arena.h", "ops.h"):
                src = runtime_root / "include" / "compgen" / name
                if not src.exists():
                    raise FileNotFoundError(f"compgen foundational runtime header missing: {src}")
                shutil.copy2(src, include_dst / name)
            for name in ("arena.c", "ops.c"):
                src = runtime_root / "src" / name
                if not src.exists():
                    raise FileNotFoundError(f"compgen foundational runtime source missing: {src}")
                shutil.copy2(src, out / name)
            ops_header_path = include_dst / "ops.h"
            ops_src_path = out / "ops.c"
            forward_src_path = out / "compgen_model_forward.c"
            forward_src_path.write_text(lowered_model.forward_c_source)

        ukernel_paths: list[Path] = []
        kernels_dir = out / "kernels"
        if kernels:
            kernels_dir.mkdir(exist_ok=True)
            for k in kernels:
                path = kernels_dir / f"{k.name}.c"
                path.write_text(k.c_source)
                ukernel_paths.append(path)

        kernel_contracts_path: Path | None = None
        if kernels:
            from compgen.kernels.providers.exo_riscv_opu import kernel_contract_yaml

            kernel_contracts_path = out / "kernel_contracts.yaml"
            kernel_contracts_path.write_text(kernel_contract_yaml(kernels))

        extra_srcs = " ".join(f"kernels/{k.name}.c" for k in kernels)
        srcs_line = "compgen_model.c model_blob.c"
        if lowered_model is not None:
            # Foundational runtime (copied into the bundle) + the
            # model-specific forward.
            srcs_line = f"{srcs_line} arena.c ops.c compgen_model_forward.c"
        if extra_srcs:
            srcs_line = f"{srcs_line} {extra_srcs}"

        makefile_path = out / "Makefile"
        makefile_text = _MAKEFILE_TEMPLATE.format(
            cross_compiler=opts.cross_compiler,
            archiver=opts.archiver,
            march=opts.march,
            mabi=opts.mabi,
        )
        if extra_srcs:
            makefile_text = makefile_text.replace(
                "SRCS := compgen_model.c model_blob.c",
                f"SRCS := {srcs_line}",
            )
        makefile_path.write_text(makefile_text)

        logger.info(
            "embedded_emitter_wrote",
            extra={
                "output_dir": str(out),
                "input_bytes": opts.input_bytes,
                "output_bytes": opts.output_bytes,
                "blob_bytes": len(model_blob),
                "ukernels": [k.name for k in kernels],
            },
        )

        return EmbeddedArtifacts(
            output_dir=out,
            header=header_path,
            blob_source=blob_path,
            runtime_source=runtime_path,
            makefile=makefile_path,
            ukernel_sources=tuple(ukernel_paths),
            kernel_contracts=kernel_contracts_path,
            forward_source=forward_src_path,
            ops_header=ops_header_path,
            ops_source=ops_src_path,
            arena_bytes=(lowered_model.arena_bytes if lowered_model is not None else 0),
        )


def emit_embedded(
    output_dir: str | Path,
    *,
    model_blob: bytes = b"",
    options: EmbeddedOptions | None = None,
    ukernels: Sequence[UkernelEmission] | None = None,
    lowered_model: Any = None,
) -> EmbeddedArtifacts:
    """Convenience wrapper around :class:`EmbeddedEmitter`."""
    return EmbeddedEmitter(options).emit(
        output_dir,
        model_blob=model_blob,
        ukernels=ukernels,
        lowered_model=lowered_model,
    )


__all__ = [
    "EmbeddedArtifacts",
    "EmbeddedEmitter",
    "EmbeddedOptions",
    "emit_embedded",
]
