#!/usr/bin/env python3
"""Generate a Flow C binding manifest for smolvlm_vision from the REAL context
inventory on the board, not from the profile CSVs.

This exists because the profile data misrepresents HTA. `gen/profile/HTA/.../
smolvlm_vision_v3` reports a time for all 49 segments, but the board holds
zero `ctx_dsp_seg_NN__Hta.bin` -- HTA can only run the extracted Conv1x1
sub-models (`*_conv1x1`), never a whole segment and never a Tanh trampoline.
A binding built from the CSVs would therefore declare backends that cannot be
staged, and Flow C's capability check would (correctly) reject it.

Backends per tile are taken from which `ctx_<name>__<Backend>.bin` actually
exist, so the manifest cannot claim more than the board can run.

    python3 gen_smolvla_binding.py --ctx-list /tmp/smolvla_ctx.txt --granularity segment
"""
import argparse, json, re, sys
from collections import defaultdict

BE = {"Cpu": "cpu", "Dsp": "dsp", "Hta": "hta"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ctx-list", required=True)
    ap.add_argument("--granularity", choices=["segment", "bundle"], default="segment",
                    help="segment = the 49 whole slices (no HTA anywhere); "
                         "bundle = also expose the extracted conv1x1 / tramp parts, "
                         "which is the only decomposition that reaches HTA")
    ap.add_argument("--out", default="bindings/smolvlm_vision.json")
    a = ap.parse_args()

    avail = defaultdict(dict)
    for line in open(a.ctx_list):
        m = re.match(r"ctx_(.+)__(Cpu|Dsp|Hta)\.bin$", line.strip())
        if m:
            avail[m.group(1)][BE[m.group(2)]] = line.strip()

    whole = re.compile(r"^(cpu_seg_\d+|dsp_seg_\d+)$")
    if a.granularity == "segment":
        names = sorted(n for n in avail if whole.match(n))
    else:
        names = sorted(avail)

    def order(n):
        m = re.match(r"(cpu|dsp)_seg_(\d+)", n)
        idx = int(m.group(2)) if m else 999
        # the pipeline alternates dsp_seg_i -> cpu_seg_i
        return (idx, 0 if n.startswith("dsp_seg") else 1, n)
    names.sort(key=order)

    bindings = []
    for i, n in enumerate(names):
        b = {"id": i, "name": n,
             "ops": {"from_partition": {"group": i}},
             "backends": {k: {"ctx": v, "graph": n} for k, v in sorted(avail[n].items())}}
        if i:
            b["depends_on"] = [i - 1]
        bindings.append(b)

    hta_capable = [b["name"] for b in bindings if "hta" in b["backends"]]
    man = {
        "network": "smolvlm_vision",
        "ir": {"source": "onnx:smolvlm_vision_v3", "quant": "int8",
               "graph_json": "gen/qnn_vmfb/smolvlm_vision_v3/qrb5165_v66/CPU/"
                             "smolvlm_vision_v3.int8/smolvlm_vision_v3.int8_dispatch_graph.json"},
        "_comment": (
            f"Generated by gen_smolvla_binding.py --granularity {a.granularity} from the "
            "context binaries actually present on the board, NOT from the profile CSVs. "
            "The CSVs report an HTA time for all 49 segments, but no ctx_dsp_seg_NN__Hta.bin "
            "exists: HTA runs only the extracted Conv1x1 sub-models. At segment granularity "
            "NO tile reaches HTA, which is the honest position and is why the published "
            "1083.6 ms is not realizable at this granularity. Use --granularity bundle to "
            "expose the conv1x1 tiles that HTA can actually take."),
        "bindings": bindings,
    }
    with open(a.out, "w") as f:
        json.dump(man, f, indent=1)
    print(f"  wrote {a.out}: {len(bindings)} tiles")
    cnt = defaultdict(int)
    for b in bindings:
        cnt[",".join(sorted(b["backends"]))] += 1
    for k, v in sorted(cnt.items()):
        print(f"    {v:>4} tiles with backends [{k}]")
    print(f"    tiles that can reach HTA: {len(hta_capable)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
