/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 57
#define FLOWC_N_LANES 17

static const int flowc_e6_deps[] = { 2, 0 };
static const int flowc_e11_deps[] = { 10, 7 };
static const int flowc_e15_deps[] = { 4 };
static const int flowc_e17_deps[] = { 12, 14 };
static const int flowc_e23_deps[] = { 22, 19 };
static const int flowc_e29_deps[] = { 26, 27 };
static const int flowc_e30_deps[] = { 16 };
static const int flowc_e35_deps[] = { 31, 33 };
static const int flowc_e39_deps[] = { 21 };
static const int flowc_e41_deps[] = { 40, 38 };
static const int flowc_e46_deps[] = { 44, 43 };
static const int flowc_e48_deps[] = { 3 };
static const int flowc_e53_deps[] = { 50, 49 };
static const int flowc_e55_deps[] = { 32 };
static const int flowc_e56_deps[] = { 52 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 0.000000, 1.568000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 1, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.000000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 2, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 0.000000, 0.459000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 3, "vint", 0, 0, "qnn_graph", "vint_encoders", "dsp", 6, 0.459000, 14.213000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_vint_encoders__Dsp.bin", "vint_encoders", 1, 3, 539, 0, 538 },
    { 4, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 1.680000, 13.909000, 0, NULL, 0, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 5, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 5.000000, 0.107000, 0, NULL, 1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 6, "fused_split", 0, 2, "qnn_graph", "fused_tail", "cpu", 5, 6.646000, 0.354000, 2, flowc_e6_deps, 5, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 7, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 10.000000, 0.014000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 5, 2, 6, 7 },
    { 8, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 10.014000, 0.107000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 9, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 15.000000, 0.589000, 0, NULL, 3, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 10, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 15.589000, 0.459000, 0, NULL, 3, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 11, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 16.646000, 0.354000, 2, flowc_e11_deps, 8, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 12, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 20.000000, 0.459000, 0, NULL, 10, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 13, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 20.000000, 0.107000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 14, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 20.000000, 1.568000, 0, NULL, 4, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 15, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 20.459000, 15.377000, 1, flowc_e15_deps, 10, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 7, 146, 103, 248 },
    { 16, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 21.568000, 13.909000, 0, NULL, 4, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 8, 103, 0, 102 },
    { 17, "fused_split", 2, 2, "qnn_graph", "fused_tail", "cpu", 5, 26.646000, 0.354000, 2, flowc_e17_deps, 13, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 18, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 27.000000, 0.107000, 0, NULL, 13, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 19, "fused_split", 3, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 30.000000, 0.014000, 0, NULL, 18, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 5, 2, 6, 7 },
    { 20, "mlp_control", 6, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 32.893000, 0.107000, 0, NULL, 19, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 21, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 36.091000, 13.909000, 0, NULL, 16, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 9, 103, 0, 102 },
    { 22, "fused_split", 3, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 36.187000, 0.459000, 0, NULL, 15, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 23, "fused_split", 3, 2, "qnn_graph", "fused_tail", "cpu", 5, 36.646000, 0.354000, 2, flowc_e23_deps, 20, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 24, "mlp_control", 7, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 37.893000, 0.107000, 0, NULL, 23, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 25, "mlp_control", 8, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 42.411000, 0.107000, 0, NULL, 24, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 26, "fused_split", 4, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 44.692000, 0.459000, 0, NULL, 22, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 27, "fused_split", 4, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 46.053000, 0.392000, 0, NULL, 26, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 2, 2, 6, 7 },
    { 28, "mlp_control", 9, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 46.445000, 0.589000, 0, NULL, 26, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 29, "fused_split", 4, 2, "qnn_graph", "fused_tail", "cpu", 5, 46.646000, 0.354000, 2, flowc_e29_deps, 25, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 30, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 47.034000, 15.377000, 1, flowc_e30_deps, 27, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 10, 146, 103, 248 },
    { 31, "fused_split", 5, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 50.000000, 0.931000, 0, NULL, 21, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 32, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 50.931000, 13.909000, 0, NULL, 21, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 11, 103, 0, 102 },
    { 33, "fused_split", 5, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 52.879000, 0.014000, 0, NULL, 29, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 5, 2, 6, 7 },
    { 34, "mlp_control", 10, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 52.893000, 0.107000, 0, NULL, 29, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 35, "fused_split", 5, 2, "qnn_graph", "fused_tail", "cpu", 5, 56.646000, 0.354000, 2, flowc_e35_deps, 34, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 36, "mlp_control", 11, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 57.000000, 0.107000, 0, NULL, 34, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 37, "mlp_control", 12, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 62.411000, 0.589000, 0, NULL, 30, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 38, "fused_split", 6, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 64.231000, 0.392000, 0, NULL, 37, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 2, 2, 6, 7 },
    { 39, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 64.623000, 15.377000, 1, flowc_e39_deps, 37, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 12, 146, 103, 248 },
    { 40, "fused_split", 6, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 64.840000, 0.931000, 0, NULL, 31, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 41, "fused_split", 6, 2, "qnn_graph", "fused_tail", "cpu", 5, 66.646000, 0.354000, 2, flowc_e41_deps, 36, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 42, "mlp_control", 13, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 67.000000, 0.107000, 0, NULL, 36, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 43, "fused_split", 7, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 70.000000, 1.568000, 0, NULL, 40, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 44, "fused_split", 7, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 71.568000, 0.931000, 0, NULL, 43, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 45, "mlp_control", 14, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 72.392000, 0.107000, 0, NULL, 42, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 46, "fused_split", 7, 2, "qnn_graph", "fused_tail", "cpu", 5, 74.646000, 0.354000, 2, flowc_e46_deps, 45, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 5, 10, 4, 15 },
    { 47, "mlp_control", 15, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 75.000000, 0.107000, 0, NULL, 45, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 48, "vint", 0, 1, "qnn_graph", "vint_decoder", "cpu", 5, 78.801000, 37.826000, 1, flowc_e48_deps, 47, "CPU", "libQnnCpu.so", "ctx_vint_decoder_fp32__Cpu.bin", "vint_decoder", 0, 13, 66, 539, 604 },
    { 49, "fused_split", 8, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 80.000000, 0.392000, 0, NULL, 39, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 2, 2, 6, 7 },
    { 50, "fused_split", 8, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 80.050000, 0.931000, 0, NULL, 44, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 51, "mlp_control", 16, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 80.392000, 0.589000, 0, NULL, 39, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 52, "yolov8n_e", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 80.981000, 13.909000, 0, NULL, 44, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 14, 103, 0, 102 },
    { 53, "fused_split", 8, 2, "qnn_graph", "fused_tail", "dsp", 6, 80.981000, 4.303000, 2, flowc_e53_deps, 49, "DSP", "libQnnDsp.so", "ctx_fused_tail_from_conv__Dsp.bin", "fused_tail_from_conv", 1, 2, 10, 4, 15 },
    { 54, "mlp_control", 17, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 85.284000, 0.589000, 0, NULL, 53, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 55, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 85.873000, 15.377000, 1, flowc_e55_deps, 53, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 15, 146, 103, 248 },
    { 56, "yolov8n_e", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 101.250000, 15.377000, 1, flowc_e56_deps, 54, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 16, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "hta|fused_split",
    "cpu|mlp_control",
    "dsp|fused_split",
    "dsp|vint",
    "hta|yolov8n_a",
    "cpu|fused_split",
    "dsp|mlp_control",
    "dsp|yolov8n_a",
    "hta|yolov8n_b",
    "hta|yolov8n_c",
    "dsp|yolov8n_b",
    "hta|yolov8n_d",
    "dsp|yolov8n_c",
    "cpu|vint",
    "hta|yolov8n_e",
    "dsp|yolov8n_d",
    "dsp|yolov8n_e",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 7, 5, 6, 6, 7, 4, 6, 6, 7, 7, 6, 7, 6, 5, 7, 6, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 651, 200, 200, 200, 838, 200, 200, 200, 200, 200, 200, 200, 2000, 200, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 40, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "7",
    "4,5",
    "6",
    "6",
    "7",
    "4,5",
    "6",
    "6",
    "7",
    "7",
    "6",
    "7",
    "6",
    "4,5",
    "7",
    "6",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
