"""Baremetal C/C++ source emission from ModelProgram.

Generates a complete, cross-compilable C project that runs a compiled
model on a RISC-V host + accelerator system.  The generated code handles:

- Hardware initialization
- Weight loading (DMA from embedded data or file)
- Kernel dispatch loop (host → accelerator → host)
- Data transfer sequencing
- Optional golden data verification

All generated files use string templates (no Jinja2 dependency).
"""

from __future__ import annotations

from pathlib import Path

import structlog

from compgen.runtime.program_builder import ModelProgram

logger = structlog.get_logger()


class BaremetalEmitter:
    """Generate a complete baremetal C project from a ModelProgram.

    Args:
        deployment: ``"bare_metal"`` for raw C or ``"zephyr"`` for Zephyr RTOS.
    """

    def __init__(self, deployment: str = "bare_metal") -> None:
        self._deployment = deployment

    def emit(self, program: ModelProgram, output_dir: str | Path) -> Path:
        """Generate all C source files for the program.

        Args:
            program: The assembled multi-device program.
            output_dir: Directory to write generated files.

        Returns:
            Path to the output directory.
        """
        out = Path(output_dir)
        out.mkdir(parents=True, exist_ok=True)
        (out / "kernels").mkdir(exist_ok=True)

        self._emit_memory_map_h(program, out)
        self._emit_npu_driver_h(program, out)
        self._emit_npu_driver_c(program, out)
        self._emit_weights_h(program, out)
        self._emit_main_c(program, out)
        self._emit_kernel_files(program, out)
        self._emit_linker_ld(program, out)
        self._emit_makefile(program, out)

        logger.info(
            "baremetal_emitted",
            output_dir=str(out),
            deployment=self._deployment,
            host_kernels=len(program.host_kernels),
            device_kernels=len(program.device_kernels),
        )
        return out

    # ------------------------------------------------------------------
    # memory_map.h
    # ------------------------------------------------------------------

    def _emit_memory_map_h(self, program: ModelProgram, out: Path) -> None:
        layout = program.memory_layout
        defines = layout.to_c_defines() if layout else "/* No memory layout */"

        content = f"""\
#ifndef MEMORY_MAP_H
#define MEMORY_MAP_H

/*
 * Memory map for {program.name}
 * Auto-generated by CompGen — DO NOT EDIT
 *
 * Host kernels:   {len(program.host_kernels)}
 * Device kernels: {len(program.device_kernels)}
 * Total kernels:  {len(program.execution_order)}
 */

{defines}

#endif /* MEMORY_MAP_H */
"""
        (out / "memory_map.h").write_text(content)

    # ------------------------------------------------------------------
    # npu_driver.h
    # ------------------------------------------------------------------

    def _emit_npu_driver_h(self, program: ModelProgram, out: Path) -> None:
        # Enumerate kernel IDs from unique patterns
        patterns = sorted(set(k.pattern_id for k in program.device_kernels))
        enum_entries = ",\n    ".join(f"KERNEL_{p.upper()} = {i}" for i, p in enumerate(patterns))

        content = f"""\
#ifndef NPU_DRIVER_H
#define NPU_DRIVER_H

/*
 * NPU dispatch driver for {program.name}
 * Auto-generated by CompGen — DO NOT EDIT
 *
 * Target backends implement npu_driver.c with hardware-specific
 * register writes, DMA commands, and synchronization.
 */

#include <stdint.h>
#include <stddef.h>

/* Initialize NPU hardware */
void npu_init(void);

/* DMA operations */
void npu_dma_write(uint32_t dst_addr, const void *src, size_t size);
void npu_dma_read(void *dst, uint32_t src_addr, size_t size);
void npu_dma_wait(void);

/* Kernel dispatch */
typedef enum {{
    {enum_entries}
}} kernel_id_t;

void npu_dispatch_kernel(kernel_id_t kernel,
                         uint32_t input_addr,
                         uint32_t weight_addr,
                         uint32_t output_addr);
void npu_wait(void);

/* Shutdown */
void npu_shutdown(void);

#endif /* NPU_DRIVER_H */
"""
        (out / "npu_driver.h").write_text(content)

    # ------------------------------------------------------------------
    # npu_driver.c (scaffold — target backend fills in real implementation)
    # ------------------------------------------------------------------

    def _emit_npu_driver_c(self, program: ModelProgram, out: Path) -> None:
        content = f"""\
/*
 * NPU driver scaffold for {program.name}
 * Auto-generated by CompGen — REPLACE WITH HARDWARE IMPLEMENTATION
 *
 * This file provides stub implementations. The target backend
 * (e.g., targets/backends/npu/) generates the real driver with
 * hardware-specific register writes and DMA commands.
 */

#include "npu_driver.h"
#include <string.h>

void npu_init(void) {{
    /* TODO: Initialize NPU hardware registers */
    /* Example: write to MMIO control register */
}}

void npu_dma_write(uint32_t dst_addr, const void *src, size_t size) {{
    /* TODO: Program DMA channel for host → device transfer */
    /* Scaffold: direct memory copy (works in simulation) */
    memcpy((void *)(uintptr_t)dst_addr, src, size);
}}

void npu_dma_read(void *dst, uint32_t src_addr, size_t size) {{
    /* TODO: Program DMA channel for device → host transfer */
    memcpy(dst, (const void *)(uintptr_t)src_addr, size);
}}

void npu_dma_wait(void) {{
    /* TODO: Poll DMA status register until complete */
}}

void npu_dispatch_kernel(kernel_id_t kernel,
                         uint32_t input_addr,
                         uint32_t weight_addr,
                         uint32_t output_addr) {{
    /* TODO: Write kernel parameters to NPU command registers */
    /* TODO: Trigger kernel execution */
    (void)kernel;
    (void)input_addr;
    (void)weight_addr;
    (void)output_addr;
}}

void npu_wait(void) {{
    /* TODO: Wait for NPU kernel completion */
    /* Example: poll status register or wait for interrupt */
}}

void npu_shutdown(void) {{
    /* TODO: Shutdown NPU hardware */
}}
"""
        (out / "npu_driver.c").write_text(content)

    # ------------------------------------------------------------------
    # weights.h
    # ------------------------------------------------------------------

    def _emit_weights_h(self, program: ModelProgram, out: Path) -> None:
        declarations = []
        for init in program.initialization:
            c_name = init.buffer.name.upper().replace(".", "_")
            declarations.append(
                f"extern const uint8_t {c_name}_DATA[];\n#define {c_name}_DATA_SIZE {init.buffer.size_bytes}"
            )

        content = f"""\
#ifndef WEIGHTS_H
#define WEIGHTS_H

/*
 * Weight declarations for {program.name}
 * Auto-generated by CompGen — DO NOT EDIT
 */

#include <stdint.h>

{chr(10).join(declarations)}

#endif /* WEIGHTS_H */
"""
        (out / "weights.h").write_text(content)

    # ------------------------------------------------------------------
    # main.c
    # ------------------------------------------------------------------

    def _emit_main_c(self, program: ModelProgram, out: Path) -> None:
        # Build dispatch sequence
        dispatch_lines = []
        for kid in program.execution_order:
            kernel = next(
                (k for k in program.host_kernels + program.device_kernels if k.kernel_id == kid),
                None,
            )
            if kernel is None:
                continue

            if kernel.device == "cpu":
                dispatch_lines.append(f"    /* CPU: {kernel.kernel_id} ({kernel.pattern_id}) */")
                dispatch_lines.append(f"    // cpu_{kernel.pattern_id}(...);  /* TODO: implement */")
            else:
                dispatch_lines.append(f"    /* NPU: {kernel.kernel_id} ({kernel.pattern_id}) */")
                pattern_upper = kernel.pattern_id.upper()
                # Use first input/output addresses if available
                in_name = kernel.inputs[0].name.upper().replace(".", "_") + "_ADDR" if kernel.inputs else "0"
                wt_name = kernel.inputs[1].name.upper().replace(".", "_") + "_ADDR" if len(kernel.inputs) > 1 else "0"
                out_name = kernel.outputs[0].name.upper().replace(".", "_") + "_ADDR" if kernel.outputs else "0"
                dispatch_lines.append(
                    f"    npu_dispatch_kernel(KERNEL_{pattern_upper}, {in_name}, {wt_name}, {out_name});"
                )
                dispatch_lines.append("    npu_wait();")
            dispatch_lines.append("")

        dispatch_body = "\n".join(dispatch_lines)

        # Weight loading
        weight_loads = []
        for init in program.initialization:
            c_name = init.buffer.name.upper().replace(".", "_")
            weight_loads.append(f"    npu_dma_write({c_name}_ADDR, {c_name}_DATA, {c_name}_DATA_SIZE);")
        weight_body = "\n".join(weight_loads) if weight_loads else "    /* No weights to load */"

        content = f"""\
/*
 * Main program for {program.name}
 * Auto-generated by CompGen — DO NOT EDIT
 *
 * Host kernels:   {len(program.host_kernels)}
 * Device kernels: {len(program.device_kernels)}
 * Execution order: {len(program.execution_order)} steps
 */

#include "memory_map.h"
#include "weights.h"
#include "npu_driver.h"

int main(void) {{
    /* 1. Initialize NPU */
    npu_init();

    /* 2. Load weights to device memory */
{weight_body}
    npu_dma_wait();

    /* 3. Execute model (dispatch loop) */
{dispatch_body}

    /* 4. Shutdown */
    npu_shutdown();

    return 0;
}}
"""
        (out / "main.c").write_text(content)

    # ------------------------------------------------------------------
    # Kernel files
    # ------------------------------------------------------------------

    def _emit_kernel_files(self, program: ModelProgram, out: Path) -> None:
        for kernel in program.device_kernels:
            if kernel.code:
                ext = {"npu_asm": ".S", "c": ".c", "python": ".py"}.get(kernel.language, ".txt")
                filename = f"{kernel.kernel_id}{ext}"
                (out / "kernels" / filename).write_text(kernel.code)

    # ------------------------------------------------------------------
    # Linker script
    # ------------------------------------------------------------------

    def _emit_linker_ld(self, program: ModelProgram, out: Path) -> None:
        # Build MEMORY block from layout regions
        memory_entries = []
        if program.memory_layout:
            for name, region in program.memory_layout.regions.items():
                c_name = name.upper()
                memory_entries.append(
                    f"    {c_name} (rwx) : ORIGIN = 0x{region.base_addr:08X}, LENGTH = 0x{region.size_bytes:X}"
                )

        memory_block = (
            "\n".join(memory_entries)
            if memory_entries
            else ("    DRAM (rwx) : ORIGIN = 0x80000000, LENGTH = 0x1000000")
        )

        content = f"""\
/*
 * Linker script for {program.name}
 * Auto-generated by CompGen
 * Compatible with chipyard HTIF interface
 */

OUTPUT_ARCH("riscv")
ENTRY(_start)

MEMORY {{
{memory_block}
}}

SECTIONS {{
    . = 0x80000000;

    .text : {{
        *(.text.init)
        *(.text .text.*)
    }}

    .rodata : {{
        *(.rodata .rodata.*)
    }}

    .data : {{
        *(.data .data.*)
    }}

    .bss : {{
        __bss_start = .;
        *(.bss .bss.*)
        *(COMMON)
        __bss_end = .;
    }}

    /* HTIF section for chipyard/FireSim communication */
    .htif ALIGN(0x40) : {{
        PROVIDE(__tohost = .);
        LONG(0);
        LONG(0);
        PROVIDE(__fromhost = .);
        LONG(0);
        LONG(0);
    }}

    /* Stack */
    . = ALIGN(16);
    __stack_bottom = .;
    . += 0x6000;  /* 24 KB stack */
    __stack_top = .;

    /* Heap */
    __heap_start = .;
    . += 0x20000;  /* 128 KB heap */
    __heap_end = .;

    _end = .;
}}
"""
        (out / "linker.ld").write_text(content)

    # ------------------------------------------------------------------
    # Makefile
    # ------------------------------------------------------------------

    def _emit_makefile(self, program: ModelProgram, out: Path) -> None:
        kernel_srcs = []
        for kernel in program.device_kernels:
            if kernel.code:
                ext = {"npu_asm": ".S", "c": ".c"}.get(kernel.language, ".c")
                kernel_srcs.append(f"kernels/{kernel.kernel_id}{ext}")

        kernel_src_list = " \\\n    ".join(kernel_srcs) if kernel_srcs else ""

        content = f"""\
# Makefile for {program.name}
# Auto-generated by CompGen
# Cross-compiles for RISC-V (chipyard compatible)

CROSS_COMPILE ?= riscv64-unknown-elf-
CC = $(CROSS_COMPILE)gcc
LD = $(CROSS_COMPILE)ld
OBJDUMP = $(CROSS_COMPILE)objdump
OBJCOPY = $(CROSS_COMPILE)objcopy

CFLAGS = -march=rv64gc -mabi=lp64d -O2 -Wall -nostdlib -nostartfiles
LDFLAGS = -T linker.ld

TARGET = {program.name}

SRCS = main.c npu_driver.c {kernel_src_list}
OBJS = $(SRCS:.c=.o)
OBJS := $(OBJS:.S=.o)

.PHONY: all clean dump

all: $(TARGET).elf $(TARGET).bin

$(TARGET).elf: $(OBJS)
\t$(CC) $(CFLAGS) $(LDFLAGS) -o $@ $^

$(TARGET).bin: $(TARGET).elf
\t$(OBJCOPY) -O binary $< $@

%.o: %.c
\t$(CC) $(CFLAGS) -c -o $@ $<

%.o: %.S
\t$(CC) $(CFLAGS) -c -o $@ $<

dump: $(TARGET).elf
\t$(OBJDUMP) -d $< > $(TARGET).dump

clean:
\trm -f $(OBJS) $(TARGET).elf $(TARGET).bin $(TARGET).dump
"""
        (out / "Makefile").write_text(content)


__all__ = ["BaremetalEmitter"]
