/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 23
#define FLOWC_N_LANES 12

static const int flowc_e4_deps[] = { 0, 1 };
static const int flowc_e10_deps[] = { 2 };
static const int flowc_e11_deps[] = { 7, 8 };
static const int flowc_e14_deps[] = { 5 };
static const int flowc_e18_deps[] = { 17, 15 };
static const int flowc_e20_deps[] = { 12 };
static const int flowc_e22_deps[] = { 21 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 0.000000, 1.115000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 1, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 0.000000, 0.142000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 2, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 0.000000, 13.191000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 2, 103, 0, 102 },
    { 3, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.142000, 0.065000, 0, NULL, 1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 4, "fused_split", 0, 2, "qnn_graph", "fused_tail", "cpu", 5, 1.115000, 1.374000, 2, flowc_e4_deps, 3, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 5, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 1.115000, 13.951000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 6, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 7.000000, 0.065000, 0, NULL, 4, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 7, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 14.000000, 0.759000, 0, NULL, 2, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 5, 4, 0, 3 },
    { 8, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 14.000000, 0.142000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 9, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 14.142000, 0.065000, 0, NULL, 8, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 10, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 14.759000, 17.468000, 1, flowc_e10_deps, 2, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 2, 146, 103, 248 },
    { 11, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 14.759000, 1.374000, 2, flowc_e11_deps, 9, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 12, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 15.066000, 13.951000, 0, NULL, 0, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 6, 103, 0, 102 },
    { 13, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 21.000000, 0.065000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 14, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "cpu", 5, 21.065000, 52.166000, 1, flowc_e14_deps, 11, "CPU", "libQnnCpu.so", "ctx_yolov8n_head__Cpu.bin", "yolov8n_HTA_split_seg101", 0, 7, 146, 103, 248 },
    { 15, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 29.017000, 0.954000, 0, NULL, 12, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 16, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 32.227000, 0.668000, 0, NULL, 7, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 8, 7, 0, 6 },
    { 17, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 32.895000, 0.759000, 0, NULL, 16, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 5, 4, 0, 3 },
    { 18, "fused_split", 2, 2, "qnn_graph", "fused_tail", "dsp", 6, 33.654000, 3.429000, 2, flowc_e18_deps, 16, "DSP", "libQnnDsp.so", "ctx_fused_tail_from_conv__Dsp.bin", "fused_tail_from_conv", 1, 5, 10, 4, 15 },
    { 19, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 37.083000, 0.668000, 0, NULL, 18, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 8, 7, 0, 6 },
    { 20, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 37.751000, 17.468000, 1, flowc_e20_deps, 19, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 9, 146, 103, 248 },
    { 21, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 41.268000, 13.951000, 0, NULL, 15, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 10, 103, 0, 102 },
    { 22, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 55.219000, 17.468000, 1, flowc_e22_deps, 19, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 11, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "hta|fused_split",
    "cpu|fused_split",
    "dsp|yolov8n_d",
    "cpu|mlp_control",
    "hta|yolov8n_c",
    "dsp|fused_split",
    "hta|yolov8n_a",
    "cpu|yolov8n_c",
    "dsp|mlp_control",
    "dsp|yolov8n_a",
    "hta|yolov8n_b",
    "dsp|yolov8n_b",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 7, 5, 6, 4, 7, 6, 7, 5, 6, 6, 7, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 189, 200, 1714, 200, 189, 200, 2000, 200, 200, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 40, 0, 40, 0, 0, 0, 40, 0, 0, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "7",
    "4,5",
    "6",
    "4,5",
    "7",
    "6",
    "7",
    "4,5",
    "6",
    "6",
    "7",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
