"""Materialize a user-space extension workspace from a gap_action_queue entry.

For one selected gap (chosen by ``gap_id``), build a directory under
``.crg-artifacts/extensions/<gap_kind>/<extension_id>/`` containing:

- ``gap_record.json`` — frozen byte-for-byte copy of the queue entry
- ``extension_contract.json`` — what the agent must fill, what verify checks
- ``reference.py`` — ground-truth callable (read-only)
- ``extension.py`` — **the only file the agent fills** (initial stub)
- ``manifest.yaml`` — extension metadata
- ``tests/test_extension.py`` — autogenerated differential tests
- ``results/`` — empty; verify writes here later

Locked files are sha256'd at materialize time and re-checked at verify
time so the agent can't sneak edits into them.

This module **never invokes an LLM**. The deterministic fill is a
separate step (``agent_decomp_fill``) so the materialize/verify/register
loop can be exercised on its own.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import yaml

from compgen.graph_compilation.hashing import sha256_file

_SANITIZE_RE = re.compile(r"[^A-Za-z0-9_]")

# Files locked at materialize time. ``manifest.yaml`` is intentionally
# absent: the agent (or Claude Code) updates it during the
# fill → verify → register loop. ``extension_contract.json`` is also
# absent because it carries the locked-files audit and including it
# in its own list would be a self-reference.
_LOCKED_FILES = ("gap_record.json", "reference.py", "README.md")
# Locked test file name (canonical per the 04 spec).
_TESTS_FILES = ("tests/test_extension_correctness.py",)
# Number of frozen (input, expected) test cases generated at materialize
# time. Drives ``inputs/case_NN.pt`` + ``expected/case_NN.pt`` and the
# test loop in ``test_extension_correctness.py``. Kept small (8) so
# materialize stays fast even for 6-model matrices.
_FROZEN_CASE_COUNT = 8


# --------------------------------------------------------------------------- #
# Schemas
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class ExtensionContract:
    schema_version: str
    extension_id: str
    gap_id: str
    gap_kind: str
    action: str
    fx_target: str
    target_id: str
    fillable_files: tuple[str, ...]
    locked_files: tuple[str, ...]
    locked_files_sha256: dict[str, str]
    verification: dict[str, Any]
    created_at_utc: str
    # 04 spec additions: contract is self-describing without re-reading
    # gap_record.json. Lets verify-extension and register-extension run
    # offline against just this file.
    semantic_name: str = ""
    slug: str = ""
    shape_signature: dict[str, Any] = field(default_factory=dict)
    dtype_signature: dict[str, Any] = field(default_factory=dict)
    required_evidence: tuple[str, ...] = ()
    allowed_actions: tuple[str, ...] = ()

    def to_dict(self) -> dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "extension_id": self.extension_id,
            "gap_id": self.gap_id,
            "gap_kind": self.gap_kind,
            "action": self.action,
            "fx_target": self.fx_target,
            "target_id": self.target_id,
            "semantic_name": self.semantic_name,
            "slug": self.slug,
            "fillable_files": list(self.fillable_files),
            "locked_files": list(self.locked_files),
            "locked_files_sha256": dict(self.locked_files_sha256),
            "verification": self.verification,
            "shape_signature": self.shape_signature,
            "dtype_signature": self.dtype_signature,
            "required_evidence": list(self.required_evidence),
            "allowed_actions": list(self.allowed_actions),
            "created_at_utc": self.created_at_utc,
        }


@dataclass
class MaterializeResult:
    extension_id: str          # canonical: <kind>__<slug>__<target>__<sha8>
    extension_dir: Path        # filesystem path; .name is the short path_stem
    path_stem: str             # short form (no kind prefix); on-disk dir name
    gap_record: dict[str, Any]
    contract: ExtensionContract
    artifacts: dict[str, Path] = field(default_factory=dict)


# --------------------------------------------------------------------------- #
# Extension ID + path generation
# --------------------------------------------------------------------------- #


def _sanitize(s: str) -> str:
    return _SANITIZE_RE.sub("_", s).strip("_")[:64] or "unnamed"


def _short_hash(payload: str) -> str:
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:8]


def make_extension_id(gap: dict[str, Any], target_id: str) -> str:
    """Stable, human-readable extension ID.

    Format: ``<sanitized_fx_target>__<target_id>__<sha8>``. The sha8 is
    over the canonical-JSON of the gap record so two materializations
    of the same gap produce the same ID, and a different shape/dtype
    signature produces a different ID.
    """
    fx_target_sanitized = _sanitize(gap.get("fx_target", "unknown"))
    target_sanitized = _sanitize(target_id)
    canonical = json.dumps(
        {
            "gap_kind": gap.get("gap_kind"),
            "fx_target": gap.get("fx_target"),
            "shape_signature": gap.get("shape_signature", {}),
            "dtype_signature": gap.get("dtype_signature", {}),
            "target_id": target_id,
        },
        sort_keys=True,
        separators=(",", ":"),
    )
    return f"{fx_target_sanitized}__{target_sanitized}__{_short_hash(canonical)}"


def extension_dir_for(gap: dict[str, Any], target_id: str, extensions_root: Path) -> Path:
    return (
        Path(extensions_root)
        / gap["gap_kind"]
        / make_extension_id(gap, target_id)
    )


# --------------------------------------------------------------------------- #
# Materialize a workspace
# --------------------------------------------------------------------------- #


def materialize_extension(
    gap: dict[str, Any],
    *,
    target_id: str,
    extensions_root: Path,
    overwrite: bool = False,
) -> MaterializeResult:
    """Build the workspace for one gap. Caller picks which gap to materialize.

    The returned :class:`MaterializeResult` carries the generated paths
    so the next step (``agent_decomp_fill``) knows where to write
    ``extension.py``.
    """
    extensions_root = Path(extensions_root).resolve()
    extension_dir = extension_dir_for(gap, target_id, extensions_root)
    if extension_dir.exists() and not overwrite:
        # Idempotent: if a workspace already exists with the same ID,
        # the gap_record content matches by construction (the ID is
        # content-derived). Just return the existing layout.
        return _reload_existing(extension_dir, gap)

    if extension_dir.exists():
        import shutil
        shutil.rmtree(extension_dir)
    extension_dir.mkdir(parents=True)
    (extension_dir / "tests").mkdir()
    (extension_dir / "results").mkdir()
    (extension_dir / "inputs").mkdir()
    (extension_dir / "expected").mkdir()

    # The canonical extension_id is the FULL ``<kind>__<slug>__<target>__<sha8>``
    # form produced by ``gap_naming.extension_id``. The on-disk directory name
    # is the SHORT form (no kind prefix) because the parent dir already carries
    # the kind — that's a *path_stem*, not the canonical id. Every extension_id
    # field in materialized artifacts MUST use the canonical form so downstream
    # consumers (registry, gap_action_queue, verify report, manifest) all agree.
    from compgen.graph_compilation.gap_naming import extension_id as _canonical_extension_id

    extension_id = _canonical_extension_id(
        gap_kind=gap["gap_kind"],
        fx_target=gap["fx_target"],
        target_id=target_id,
        shape_signature=gap.get("shape_signature", {}),
        dtype_signature=gap.get("dtype_signature", {}),
    )
    path_stem = extension_dir.name  # short form, used only as a filesystem name

    # 1. gap_record.json — frozen copy.
    gap_record_path = extension_dir / "gap_record.json"
    gap_record_text = json.dumps(gap, indent=2, sort_keys=True)
    gap_record_path.write_text(gap_record_text + "\n", encoding="utf-8")

    # 2. reference.py
    reference_path = extension_dir / "reference.py"
    reference_path.write_text(_render_reference(gap), encoding="utf-8")

    # 3. manifest.yaml — EDITABLE. Agent updates ``status`` from ``draft``
    #    to ``verified`` during the fill → verify → register loop.
    manifest_path = extension_dir / "manifest.yaml"
    manifest_path.write_text(_render_manifest(gap, extension_id, target_id), encoding="utf-8")

    # 4. tests/test_extension_correctness.py — runnable harness that loads
    #    the frozen (inputs/expected) cases and runs the differential check.
    tests_path = extension_dir / "tests" / "test_extension_correctness.py"
    tests_path.write_text(_render_correctness_tests(gap), encoding="utf-8")

    # 5. extension.py — STUB. Agent fills.
    extension_path = extension_dir / "extension.py"
    extension_path.write_text(_render_extension_stub(gap), encoding="utf-8")

    # 5b. README.md — agent-facing instructions. LOCKED.
    readme_path = extension_dir / "README.md"
    readme_path.write_text(_render_readme(gap, extension_id, target_id), encoding="utf-8")

    # 5c. inputs/case_NN.pt + expected/case_NN.pt — frozen test data.
    #     Each pair is a (random-but-seeded inputs tuple, reference output)
    #     captured by *running* the reference at materialize time. Verify
    #     uses these in addition to fresh random trials.
    frozen_cases = _generate_frozen_cases(gap, extension_dir)

    # 6. extension_contract.json — sha256 of every locked file we just wrote.
    locked_keys = list(_LOCKED_FILES) + list(_TESTS_FILES)
    # Add every frozen-case file under inputs/ + expected/ to the locked set
    # so an agent who edits them gets caught.
    for case_path in sorted(extension_dir.rglob("inputs/*")):
        locked_keys.append(case_path.relative_to(extension_dir).as_posix())
    for case_path in sorted(extension_dir.rglob("expected/*")):
        locked_keys.append(case_path.relative_to(extension_dir).as_posix())
    locked = {rel: sha256_file(extension_dir / rel) for rel in locked_keys}
    contract = ExtensionContract(
        schema_version="extension_contract_v1",
        extension_id=extension_id,
        gap_id=gap["gap_id"],
        gap_kind=gap["gap_kind"],
        action=_pick_default_action(gap),
        fx_target=gap["fx_target"],
        target_id=target_id,
        fillable_files=("extension.py", "manifest.yaml"),
        locked_files=tuple(locked_keys),
        locked_files_sha256=locked,
        verification={
            "num_random_inputs": 100,
            "frozen_cases": frozen_cases,
            "rtol": 1e-5,
            "atol": 1e-5,
            "seed": 0,
        },
        # Domain-specific descriptive fields (from the gap record) so the
        # contract is self-contained for downstream verify/register tools.
        semantic_name=gap.get("semantic_name", gap["fx_target"]),
        slug=gap.get("slug", _sanitize(gap["fx_target"])),
        shape_signature=gap.get("shape_signature", {}),
        dtype_signature=gap.get("dtype_signature", {}),
        required_evidence=tuple(gap.get("required_evidence", [])),
        allowed_actions=tuple(gap.get("allowed_actions", [])),
        created_at_utc=_utcnow(),
    )
    contract_path = extension_dir / "extension_contract.json"
    contract_path.write_text(
        json.dumps(contract.to_dict(), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    artifacts = {
        "gap_record": gap_record_path,
        "extension_contract": contract_path,
        "reference": reference_path,
        "manifest": manifest_path,
        "tests": tests_path,
        "extension": extension_path,
    }
    return MaterializeResult(
        extension_id=extension_id,
        extension_dir=extension_dir,
        path_stem=path_stem,
        gap_record=gap,
        contract=contract,
        artifacts=artifacts,
    )


def _reload_existing(extension_dir: Path, gap: dict[str, Any]) -> MaterializeResult:
    contract_path = extension_dir / "extension_contract.json"
    contract_obj = json.loads(contract_path.read_text(encoding="utf-8"))
    contract = ExtensionContract(
        schema_version=contract_obj["schema_version"],
        extension_id=contract_obj["extension_id"],
        gap_id=contract_obj["gap_id"],
        gap_kind=contract_obj["gap_kind"],
        action=contract_obj["action"],
        fx_target=contract_obj["fx_target"],
        target_id=contract_obj["target_id"],
        fillable_files=tuple(contract_obj["fillable_files"]),
        locked_files=tuple(contract_obj["locked_files"]),
        locked_files_sha256=dict(contract_obj["locked_files_sha256"]),
        verification=contract_obj["verification"],
        created_at_utc=contract_obj["created_at_utc"],
    )
    artifacts = {
        "gap_record": extension_dir / "gap_record.json",
        "extension_contract": contract_path,
        "reference": extension_dir / "reference.py",
        "manifest": extension_dir / "manifest.yaml",
        "tests": extension_dir / "tests" / "test_extension_correctness.py",
        "extension": extension_dir / "extension.py",
    }
    return MaterializeResult(
        # Trust the contract's stored extension_id (canonical full form)
        # over the directory name (short path_stem).
        extension_id=contract_obj["extension_id"],
        extension_dir=extension_dir,
        path_stem=extension_dir.name,
        gap_record=gap,
        contract=contract,
        artifacts=artifacts,
    )


# --------------------------------------------------------------------------- #
# File templates
# --------------------------------------------------------------------------- #


def _pick_default_action(gap: dict[str, Any]) -> str:
    """Choose the simplest valid action from the gap's allowed list.

    For ``unsupported_op`` we always pick ``decompose_to_supported_ops``
    when available — that's the agent action this milestone implements.
    """
    allowed = gap.get("allowed_actions", [])
    for preferred in ("decompose_to_supported_ops", "create_payload_lowering_extension"):
        if preferred in allowed:
            return preferred
    return allowed[0] if allowed else "keep_as_fallback"


# Mapping for Dynamo built-in targets that don't have a clean ``torch.ops.*``
# resolution. These are the canonical Python callables Dynamo records when
# tracing pre-decomposition graphs. The mapping is small and additive — when
# Claude Code (or a human) hits a fx_target outside this set, the reference
# raises with a clear message rather than fabricating a wrong answer.
_DYNAMO_BUILTIN_REFERENCES: dict[str, str] = {
    "<built-in function linear>": "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.linear(*args)",
    "<built-in function gelu>": "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.gelu(*args)",
    "<built-in function relu>": "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.relu(*args)",
    "<built-in function tanh>": "import torch as _t\n\ndef _impl(*args):\n    return _t.tanh(*args)",
    "<built-in function matmul>": "import torch as _t\n\ndef _impl(*args):\n    return _t.matmul(*args)",
    "<built-in function softmax>": (
        "import torch.nn.functional as F\n\n"
        "def _impl(x, dim=-1, *args):\n"
        "    return F.softmax(x, dim=dim)"
    ),
    "<built-in method conv2d of type object>": (
        "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.conv2d(*args)"
    ),
    "<function batch_norm>": (
        "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.batch_norm(*args)"
    ),
    "<function relu>": "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.relu(*args)",
    "<function embedding>": (
        "import torch.nn.functional as F\n\ndef _impl(*args):\n    return F.embedding(*args)"
    ),
    "<built-in method tanh of type object>": "import torch as _t\n\ndef _impl(*args):\n    return _t.tanh(*args)",
}


def _resolve_reference_body(fx_target: str) -> tuple[str, str]:
    """Pick a `(body, imports)` pair so reference.py invokes the original op.

    Three handled cases:

    - ``crgtoy.*`` — the canonical test custom op; load the test model
      file (which registers ``torch.ops.crgtoy.*`` as a side effect)
      and call it.
    - ``aten.<op>[.<overload>]`` — directly dispatch through
      ``torch.ops.aten``; works for every traced aten op.
    - ``<built-in function|method ...>`` — Dynamo's pre-decomposition
      Python callables; resolved through :data:`_DYNAMO_BUILTIN_REFERENCES`.

    Anything else falls through to a ``NotImplementedError`` body so
    we don't fabricate behavior for unknown targets — a Claude Code
    agent will see a clear error and can either supply a matching
    reference patch or skip that workspace.
    """
    if fx_target.startswith("crgtoy."):
        op_name = fx_target.removeprefix("crgtoy.").removesuffix(".default")
        repo_root = Path(__file__).resolve().parents[3]
        model_path = repo_root / "tests" / "graph_compilation" / "models" / "custom_unsupported_op.py"
        prelude = (
            "# Importing the model file registers ``torch.ops.crgtoy.*`` as a\n"
            "# side effect. The path was baked in at materialize time.\n"
            f"_MODEL_PATH = Path({str(model_path)!r})\n"
            "if _MODEL_PATH.exists():\n"
            "    spec = importlib.util.spec_from_file_location('crg_unsupported_model', _MODEL_PATH)\n"
            "    if spec and spec.loader:\n"
            "        mod = importlib.util.module_from_spec(spec)\n"
            "        sys.modules.setdefault('crg_unsupported_model', mod)\n"
            "        spec.loader.exec_module(mod)\n"
        )
        body = f"return torch.ops.crgtoy.{op_name}(*args)"
        imports = (
            "import importlib.util\n"
            "import sys\n"
            "from pathlib import Path\n\n"
            "import torch\n\n"
            f"{prelude}\n"
        )
        return body, imports

    if fx_target.startswith("aten."):
        # ``aten.linear.default`` / ``aten.relu.default`` / ``aten.<x>``
        # both ``torch.ops.aten.X.default`` and ``torch.ops.aten.X`` are
        # callable; the explicit overload dispatch is what FXImporter
        # produces, so we pass straight through.
        path = fx_target.removeprefix("aten.")
        body = f"return torch.ops.aten.{path}(*args)"
        imports = "import torch\n\n"
        return body, imports

    if fx_target in _DYNAMO_BUILTIN_REFERENCES:
        impl = _DYNAMO_BUILTIN_REFERENCES[fx_target]
        body = "return _impl(*args)"
        imports = "import torch\n\n" + impl + "\n\n"
        return body, imports

    body = (
        "raise NotImplementedError(\n"
        f"    \"reference for {fx_target!r} has no built-in resolution; \"\n"
        "    \"add a mapping in compgen.graph_compilation.extension_materialize\"\n"
        ")"
    )
    return body, "import torch\n\n"


def _generate_frozen_cases(gap: dict[str, Any], extension_dir: Path) -> dict[str, Any]:
    """Run the reference at materialize time and freeze (input, expected) pairs.

    The reference module was just written to ``reference.py``. We import
    it from disk (NOT through the running interpreter's module cache),
    sample ``_FROZEN_CASE_COUNT`` random input tuples per the gap's
    shape/dtype signature, and save matching ``inputs/case_NN.pt`` and
    ``expected/case_NN.pt`` files.

    Returns metadata describing the frozen set so the contract carries
    a count + per-case sha256 for the locked-files audit.

    If the reference cannot be loaded or invoked (rare — most commonly
    when ``_render_reference`` fell into the NotImplementedError branch
    for an unknown target), we return ``{"count": 0, "reason": ...}``
    and the verifier falls back to fresh random sampling at verify time.
    """
    import importlib.util
    import sys as _sys

    import torch as _torch

    reference_path = extension_dir / "reference.py"
    spec = importlib.util.spec_from_file_location(
        f"crg_ext_ref_at_materialize_{extension_dir.name}", reference_path
    )
    if spec is None or spec.loader is None:
        return {"count": 0, "reason": "could not import reference.py"}
    module = importlib.util.module_from_spec(spec)
    _sys.modules[spec.name] = module
    try:
        spec.loader.exec_module(module)
    except Exception as exc:
        return {"count": 0, "reason": f"reference import failed: {type(exc).__name__}: {exc}"}
    reference = getattr(module, "reference", None)
    if reference is None:
        return {"count": 0, "reason": "reference.py has no `reference` callable"}

    in_shapes = gap.get("shape_signature", {}).get("inputs", [])
    in_dtypes = gap.get("dtype_signature", {}).get("inputs", [])
    if not in_shapes:
        return {"count": 0, "reason": "no input shape signature on the gap"}

    dtype_map = {
        "torch.float32": _torch.float32,
        "torch.float": _torch.float32,
        "torch.float64": _torch.float64,
        "torch.float16": _torch.float16,
        "torch.bfloat16": _torch.bfloat16,
        "torch.int32": _torch.int32,
        "torch.int64": _torch.int64,
    }

    inputs_dir = extension_dir / "inputs"
    expected_dir = extension_dir / "expected"

    cases_meta: list[dict[str, Any]] = []
    seed = 0
    for i in range(_FROZEN_CASE_COUNT):
        gen = _torch.Generator()
        gen.manual_seed(seed + i)
        args: list[Any] = []
        for j, raw_shape in enumerate(in_shapes):
            shape = [int(s) if isinstance(s, int) else 1 for s in raw_shape]
            dtype_str = in_dtypes[j] if j < len(in_dtypes) else "torch.float32"
            dtype = dtype_map.get(dtype_str, _torch.float32)
            if dtype.is_floating_point:
                t = _torch.randn(shape, generator=gen, dtype=dtype)
            elif dtype == _torch.bool:
                t = (_torch.rand(shape, generator=gen) > 0.5)
            else:
                # Integer indices — small range for the embedding/index ops.
                t = _torch.randint(0, 8, shape, generator=gen, dtype=dtype)
            args.append(t)

        try:
            with _torch.no_grad():
                expected = reference(*args)
        except Exception as exc:
            # Reference can't be evaluated for this kind of gap; bail
            # on frozen cases entirely. Verify will fall back to random
            # sampling without expected ground truth.
            return {
                "count": 0,
                "reason": f"reference invocation failed on case {i}: {type(exc).__name__}: {exc}",
            }

        in_path = inputs_dir / f"case_{i:02d}.pt"
        out_path = expected_dir / f"case_{i:02d}.pt"
        _torch.save(tuple(args), in_path)
        _torch.save(expected, out_path)
        cases_meta.append(
            {
                "index": i,
                "inputs": in_path.relative_to(extension_dir).as_posix(),
                "expected": out_path.relative_to(extension_dir).as_posix(),
            }
        )

    return {"count": len(cases_meta), "cases": cases_meta, "seed": seed}


def _render_reference(gap: dict[str, Any]) -> str:
    """Reference function: invokes the original op as ground truth.

    For ``unsupported_op`` gaps the reference is the live torch op
    itself. Locked: the agent never edits this file.

    For ``crgtoy::*`` ops we import the canonical test-model module
    eagerly (it carries the op registration as an import side effect)
    so the verifier can call ``torch.ops.crgtoy.<op>`` even when the
    workspace runs in a process that hasn't otherwise touched the
    test fixtures.
    """
    fx_target = gap["fx_target"]
    body, imports = _resolve_reference_body(fx_target)
    return (
        '"""Ground-truth reference for the gap. LOCKED — do not edit."""\n\n'
        "from __future__ import annotations\n\n"
        f"{imports}\n"
        "def reference(*args: torch.Tensor) -> torch.Tensor:\n"
        "    \"\"\"Invoke the original (unmodified) operator.\"\"\"\n"
        f"    {body}\n"
    )


def _render_extension_stub(gap: dict[str, Any]) -> str:
    """Initial extension.py — agent overwrites this with a real impl.

    The stub raises ``NotImplementedError`` so verify cleanly fails
    until an agent fill (deterministic or LLM-driven) completes.
    """
    fx_target = gap["fx_target"]
    return (
        f'"""Agent-filled extension for ``{fx_target}``.\n\n'
        f"This file is the **only** file the agent edits. Locked siblings\n"
        f"(reference.py, manifest.yaml, tests/) are sha256'd in\n"
        f"extension_contract.json::locked_files_sha256 and re-checked at\n"
        f"verify time.\n\n"
        f'gap_id: {gap["gap_id"]}\n'
        f'fx_target: {fx_target}\n'
        f'gap_kind: {gap["gap_kind"]}\n'
        '"""\n\n'
        "from __future__ import annotations\n\n"
        "import torch\n\n\n"
        "def extension(*args: torch.Tensor) -> torch.Tensor:\n"
        "    \"\"\"Replacement implementation. Must match reference within tolerance.\"\"\"\n"
        f'    raise NotImplementedError(\n'
        f'        "agent has not filled extension for {fx_target}"\n'
        f'    )\n'
    )


def _render_readme(gap: dict[str, Any], extension_id: str, target_id: str) -> str:
    """Author-facing instructions. Designed to be read by Claude Code.

    The README is intentionally explicit: it tells the editing agent
    exactly which file to touch, what the function signature must be,
    and which CLI command to run to verify. The verifier runs locked-files
    audit + 100 random differential trials; the agent doesn't need to
    write its own tests.
    """
    fx_target = gap["fx_target"]
    gap_kind = gap["gap_kind"]
    in_shapes = gap.get("shape_signature", {}).get("inputs", [])
    out_shapes = gap.get("shape_signature", {}).get("outputs", [])
    in_dtypes = gap.get("dtype_signature", {}).get("inputs", [])
    out_dtypes = gap.get("dtype_signature", {}).get("outputs", [])

    shapes_block_lines = ["### Inputs"]
    for i, sh in enumerate(in_shapes):
        dt = in_dtypes[i] if i < len(in_dtypes) else "?"
        shapes_block_lines.append(f"- arg{i}: shape={sh} dtype={dt}")
    shapes_block_lines.append("\n### Outputs")
    for i, sh in enumerate(out_shapes):
        dt = out_dtypes[i] if i < len(out_dtypes) else "?"
        shapes_block_lines.append(f"- out{i}: shape={sh} dtype={dt}")
    shapes_block = "\n".join(shapes_block_lines)

    return f"""# Extension workspace: `{extension_id}`

This workspace was materialized from gap `{gap.get("gap_id")}` of kind `{gap_kind}`,
targeting fx op **`{fx_target}`** on target `{target_id}`.

## What you (or Claude Code) need to do

You may edit **only** `extension.py` and `manifest.yaml`. Every other file
(``gap_record.json``, ``reference.py``, ``README.md``, ``inputs/*``,
``expected/*``, ``tests/*``) is locked — sha256'd in
``extension_contract.json::locked_files_sha256``. Editing a locked file
will fail the verifier's ``locked_files_audit`` check.

Replace the ``NotImplementedError`` body in ``extension.py`` with a real
implementation. Update ``manifest.yaml::status`` from ``draft`` to
``verified`` once the verifier reports ``pass``.

The function must have signature:

```python
def extension(*args: torch.Tensor) -> torch.Tensor: ...
```

and must be **mathematically equivalent** to `reference.py::reference` over
the inputs described below.

## Op signature

{shapes_block}

## Verifying your fill

```bash
python -m compgen.graph_compilation extension verify --extension {extension_id}
```

This runs:

1. A locked-files audit (every file other than `extension.py` and
   `results/*` must hash to its materialize-time value).
2. 100 random differential trials: random tensors with the shapes/dtypes
   above are passed to both `reference.reference(...)` and
   `extension.extension(...)`, and `max_abs_error` / `max_rel_error` must
   stay within `extension_contract.json::verification.{{rtol,atol}}`.

The verifier writes `results/verification.json`. Status `pass` means
you're done.

## Registering after verify passes

```bash
python -m compgen.graph_compilation extension register \\
  --extension {extension_id} \\
  --registry .crg-artifacts/extensions/registry.yaml
```

After registering, re-running `gap-discovery --extension-registry <path>` on
the upstream lowering run will report this target as closed and exclude
it from the queue.

## Rules

- Only edit `extension.py`.
- Don't import from `compgen.graph_compilation.*` — keep your impl
  self-contained and depend only on `torch` / `torch.nn.functional` /
  numpy stdlib.
- If you cannot decompose the op into supported primitives, leave a
  clear `NotImplementedError(\"reason\")` — verify will fail loudly and
  no false closure will be registered.

## Reference behavior

See `reference.py` (locked). For `crgtoy.*` targets, the reference is the
live torch op; your job is to express the same computation in terms of
ops that `compgen.ir.payload.import_fx.FXImporter` already lowers (linear,
matmul, gelu, relu, conv2d, batch_norm, layer_norm, softmax, etc.).
"""


def _render_manifest(gap: dict[str, Any], extension_id: str, target_id: str) -> str:
    """Editable YAML metadata.

    Starts as ``status: draft``. The agent (or Claude Code) updates
    ``status`` to ``verified`` after the verifier reports ``pass``,
    and Extension Closure's register step writes the verified-at
    timestamp.
    """
    obj: dict[str, Any] = {
        "schema_version": "extension_manifest_v1",
        "extension_id": extension_id,
        "gap_id": gap["gap_id"],
        "gap_kind": gap["gap_kind"],
        "fx_target": gap["fx_target"],
        "target_id": target_id,
        "status": "draft",
        "last_verified_at_utc": None,
        "last_verified_status": None,
        "registered_at_utc": None,
        "shape_signature": gap.get("shape_signature", {}),
        "dtype_signature": gap.get("dtype_signature", {}),
    }
    return yaml.safe_dump(obj, sort_keys=True, default_flow_style=False)


def _render_correctness_tests(gap: dict[str, Any]) -> str:
    """Differential test harness. LOCKED.

    Runs two layers of check, in order:

    1. **Locked-files audit** via
       ``compgen.graph_compilation.extension_verify.run_verify`` — proves
       only ``extension.py`` (and ``manifest.yaml``) changed since
       materialize.
    2. **Frozen-case differential** — loads every ``inputs/case_NN.pt``
       and ``expected/case_NN.pt``, runs ``extension(*inputs)``, and
       compares against the saved expected output within the contract's
       rtol/atol.

    The frozen-case loop is what the spec calls for: a runnable
    pytest target that initially fails with ``NotImplementedError``
    coming from ``extension.py`` (not from broken paths or imports).
    """
    return (
        '"""Differential correctness test for the agent-filled extension. LOCKED."""\n\n'
        "from __future__ import annotations\n\n"
        "import importlib.util\n"
        "import json\n"
        "import sys\n"
        "from pathlib import Path\n\n"
        "import torch\n\n"
        "from compgen.graph_compilation.extension_verify import run_verify\n\n\n"
        "_WORKSPACE = Path(__file__).resolve().parent.parent\n"
        "_CONTRACT = json.loads((_WORKSPACE / 'extension_contract.json').read_text(encoding='utf-8'))\n\n\n"
        "def _load_extension():\n"
        "    spec = importlib.util.spec_from_file_location(\n"
        "        f'crg_correctness_{_WORKSPACE.name}', _WORKSPACE / 'extension.py'\n"
        "    )\n"
        "    assert spec and spec.loader, 'extension.py is not loadable'\n"
        "    m = importlib.util.module_from_spec(spec)\n"
        "    sys.modules[spec.name] = m\n"
        "    spec.loader.exec_module(m)\n"
        "    assert hasattr(m, 'extension'), 'extension.py has no `extension` callable'\n"
        "    return m.extension\n\n\n"
        "def _diff_max(actual, expected):\n"
        "    if isinstance(actual, (tuple, list)) and isinstance(expected, (tuple, list)):\n"
        "        ma, mr = 0.0, 0.0\n"
        "        for a, e in zip(actual, expected):\n"
        "            sma, smr = _diff_max(a, e)\n"
        "            ma, mr = max(ma, sma), max(mr, smr)\n"
        "        return ma, mr\n"
        "    if not (isinstance(actual, torch.Tensor) and isinstance(expected, torch.Tensor)):\n"
        "        return (0.0, 0.0) if actual == expected else (float('inf'), float('inf'))\n"
        "    if actual.shape != expected.shape:\n"
        "        return float('inf'), float('inf')\n"
        "    diff = (actual.detach() - expected.detach()).abs()\n"
        "    if diff.numel() == 0:\n"
        "        return 0.0, 0.0\n"
        "    denom = expected.detach().abs().clamp_min(1e-12)\n"
        "    return float(diff.max().item()), float((diff / denom).max().item())\n\n\n"
        "def test_locked_files_audit() -> None:\n"
        "    \"\"\"The agent must not edit anything except extension.py and manifest.yaml.\"\"\"\n"
        "    result = run_verify(_WORKSPACE)\n"
        "    assert result.locked_audit_status == 'pass', result.locked_audit_violations\n\n\n"
        "def test_extension_matches_frozen_cases() -> None:\n"
        "    \"\"\"Run extension on every frozen (input, expected) pair.\"\"\"\n"
        "    extension = _load_extension()\n"
        "    cases = _CONTRACT['verification'].get('frozen_cases', {}).get('cases', [])\n"
        "    if not cases:\n"
        "        # Reference couldn't be evaluated at materialize time;\n"
        "        # the run_verify path uses fresh random sampling instead.\n"
        "        result = run_verify(_WORKSPACE)\n"
        "        assert result.status == 'pass', result.detail\n"
        "        return\n"
        "    rtol = float(_CONTRACT['verification'].get('rtol', 1e-5))\n"
        "    atol = float(_CONTRACT['verification'].get('atol', 1e-5))\n"
        "    for case in cases:\n"
        "        in_t = torch.load(_WORKSPACE / case['inputs'], weights_only=False)\n"
        "        exp_t = torch.load(_WORKSPACE / case['expected'], weights_only=False)\n"
        "        if not isinstance(in_t, (tuple, list)):\n"
        "            in_t = (in_t,)\n"
        "        with torch.no_grad():\n"
        "            actual = extension(*in_t)\n"
        "        ma, mr = _diff_max(actual, exp_t)\n"
        "        assert ma <= atol and mr <= rtol, (\n"
        "            f\"case {case['index']}: max_abs={ma} > atol={atol} or max_rel={mr} > rtol={rtol}\"\n"
        "        )\n"
    )


def _utcnow() -> str:
    return datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
