"""Export golden data to framework-agnostic formats (.pt, .npy).

Saves golden test cases in a standard directory structure that any
kernel development tool can consume, independent of PyTorch.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import numpy as np
import torch

from compgen.kernels.golden.generator import GoldenTestCase


def export_golden_data(
    test_cases: list[GoldenTestCase],
    output_dir: str | Path,
    formats: list[str] | None = None,
) -> Path:
    """Export golden test cases to disk.

    Creates the standard artifact structure::

        output_dir/
            <pattern_id>/
                golden_<variant>/
                    inputs/
                        <name>.pt / <name>.npy
                    expected_output.pt / expected_output.npy
                    shape_info.json

    Args:
        test_cases: List of golden test cases to export.
        output_dir: Root directory for golden data.
        formats: Export formats (default: ``["pt", "npy"]``).

    Returns:
        Path to the output directory.
    """
    if formats is None:
        formats = ["pt", "npy"]

    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    for tc in test_cases:
        tc_dir = out / tc.pattern_id / f"golden_{tc.variant_name}"
        inputs_dir = tc_dir / "inputs"
        inputs_dir.mkdir(parents=True, exist_ok=True)

        # Save inputs
        for name, tensor in tc.inputs.items():
            if "pt" in formats:
                torch.save(tensor, inputs_dir / f"{name}.pt")
            if "npy" in formats:
                np.save(inputs_dir / f"{name}.npy", tensor.float().numpy())

        # Save expected output
        if tc.expected_output is not None:
            if "pt" in formats:
                torch.save(tc.expected_output, tc_dir / "expected_output.pt")
            if "npy" in formats:
                np.save(tc_dir / "expected_output.npy", tc.expected_output.float().numpy())

        # Save metadata
        (tc_dir / "shape_info.json").write_text(json.dumps(
            tc.metadata, indent=2, default=str,
        ))

    return out


def export_test_harness(
    test_case: GoldenTestCase,
    output_dir: str | Path,
) -> Path:
    """Export an autocomp-compatible test harness for a golden test case.

    Creates ``test_harness.py`` that autocomp can use directly:
    - ``get_inputs()`` loads golden inputs
    - ``reference()`` runs the golden reference
    - ``check_correctness()`` validates kernel output

    Args:
        test_case: The golden test case.
        output_dir: Directory to write the harness.

    Returns:
        Path to the test harness file.
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    input_names = list(test_case.inputs.keys())
    input_loads = "\n    ".join(
        f'{name} = torch.load(golden_dir / "inputs" / "{name}.pt", weights_only=True)'
        for name in input_names
    )
    input_args = ", ".join(input_names)

    harness = f'''"""Autocomp test harness for pattern: {test_case.pattern_id}
Variant: {test_case.variant_name}
Params: {test_case.params}

Generated by CompGen. Golden data verified at generation time.
"""
import torch
from pathlib import Path

GOLDEN_DIR = Path(__file__).parent / "golden_{test_case.variant_name}"


def get_inputs():
    """Load golden inputs."""
    golden_dir = GOLDEN_DIR
    {input_loads}
    return ({input_args},)


def get_expected_output():
    """Load golden expected output."""
    return torch.load(GOLDEN_DIR / "expected_output.pt", weights_only=True)


def check_correctness(kernel_output, atol=1e-2, rtol=1e-2):
    """Check kernel output against golden data."""
    expected = get_expected_output()
    return torch.allclose(kernel_output.float(), expected.float(), atol=atol, rtol=rtol)


if __name__ == "__main__":
    inputs = get_inputs()
    expected = get_expected_output()
    print(f"Pattern: {test_case.pattern_id}")
    print(f"Input shapes: {{[tuple(t.shape) for t in inputs]}}")
    print(f"Expected output shape: {{expected.shape}}")
    print(f"Expected output dtype: {{expected.dtype}}")
'''

    harness_path = out / "test_harness.py"
    harness_path.write_text(harness)
    return harness_path


__all__ = ["export_golden_data", "export_test_harness"]
