"""Dynamic-scheduler megakernel emitter (Algorithm 2 of the ETC paper).

Sibling of :mod:`compgen.ir.tile.lower_megakernel` (static scheduler).
Consumes an annotated ``event.graph`` whose policy is ``dynamic`` and
emits a persistent Triton kernel that

    * Maintains a global ready queue in GPU global memory (head + tail
      atomic int32 counters and a ``(MAX_QUEUE, 2)`` slot pool).
    * Pre-seeds the queue with every task that has no ``in_edges``.
    * Each program (== one SM) loops:

          slot = atomic_add(queue_head, 1)
          if slot >= TOTAL_TASKS: break
          while slot >= atomic_load(queue_tail): pass
          (task_id, task_kind) = queue_pool[slot]
          dispatch into _run_<func>(...)
          for each out_edge of this task:
              old = atomic_add(E + ev, -decrement)
              if old == decrement:
                  # event just triggered -- push every consumer for this event
                  for each consumer of ev:
                      tail = atomic_add(queue_tail, 1)
                      queue_pool[tail] = (consumer_task_id, consumer_kind)

This is faithful to ETC §3.2 + Appendix A (push/pop) and the
*early-push* optimisation Appendix E (pushing a consumer the moment its
producer is dispatched is supported via ``early_push=True`` -- see
:class:`DynamicMegakernelLoweringSpec`).

Bodies passed to this emitter must be **pure compute** -- they do not
contain ``tl.atomic_add`` / ``while`` event-coordination logic; the
emitter inserts that automatically based on the IR's ``in_edges`` /
``out_edges``.  This is the second half of the paper's "scheduling
transformation rewrites the body" claim.
"""

from __future__ import annotations

import json
import textwrap
from dataclasses import dataclass, field
from typing import Any

from xdsl.dialects.builtin import IntegerAttr, StringAttr

from compgen.ir.event.attrs import EventTensorTypeAttr
from compgen.ir.event.ops import (
    CallDeviceOp,
    EventTensorOp,
    GraphOp,
)


_SCHEDULE_ATTR = "compgen.static_schedule"


@dataclass(frozen=True)
class DynamicDeviceFunctionSpec:
    """Pure-compute body for one device function under dynamic scheduling.

    The body must NOT perform any ``event.notify`` or ``event.wait`` --
    that synchronisation is auto-generated by the emitter from the IR's
    out_edges / in_edges.

    Attributes:
        name:        device-function symbol matching ``CallDeviceOp.device_func``.
        body_source: indented Triton source for the body (without signature).
                     May reference any data pointer, any constexpr, and
                     ``task_id`` (the int task coordinate).
    """

    name: str
    body_source: str


@dataclass(frozen=True)
class DynamicMegakernelLoweringSpec:
    """Caller-supplied wiring for the dynamic-scheduler emitter."""

    data_pointers: tuple[str, ...] = ()
    constexpr_args: tuple[str, ...] = ()
    device_functions: tuple[DynamicDeviceFunctionSpec, ...] = ()
    early_push: bool = False
    num_warps: int = 4
    num_stages: int = 2


@dataclass(frozen=True)
class DynamicMegakernelLoweringResult:
    """Result of dynamic-mode lowering.

    Attributes:
        kernel_name:     name of the emitted ``@triton.jit`` function.
        kernel_source:   full Python source (with @triton.jit decorator).
        launch_config:   ``{"grid": int, "num_warps": int, ...}``.
        event_layout:    one entry per event tensor.
        device_function_table: ``{kind_int -> device_func_name}``.
        initial_queue:   the (task_id, kind) entries that must be present
                         in ``queue_pool`` when the kernel launches
                         (i.e. tasks with no in_edges).
        consumer_table:  ``{(event_name, event_index) -> [(consumer_task_id, kind), ...]}``
                         indexed by event coord so distinct event indices
                         fire independent consumers (required for
                         dynamic-scheduler correctness).
        total_tasks:     total task count -- the kernel exits once
                         ``queue_head`` reaches this many pops.
        diagnostics:     non-fatal warnings.
    """

    kernel_name: str
    kernel_source: str
    launch_config: dict[str, Any] = field(default_factory=dict)
    event_layout: list[dict[str, Any]] = field(default_factory=list)
    device_function_table: dict[int, str] = field(default_factory=dict)
    initial_queue: list[tuple[int, int]] = field(default_factory=list)
    consumer_table: dict[tuple[str, int], list[tuple[int, int]]] = field(default_factory=dict)
    total_tasks: int = 0
    diagnostics: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# IR walks
# ---------------------------------------------------------------------------


def _event_layout(graph: GraphOp) -> list[dict[str, Any]]:
    layout: list[dict[str, Any]] = []
    for op in graph.body.ops:
        if not isinstance(op, EventTensorOp):
            continue
        et: EventTensorTypeAttr = op.event_type
        shape = [d.value.data for d in et.shape.data if isinstance(d, IntegerAttr)]
        size = 1
        for d in shape:
            size *= max(d, 1)
        layout.append(
            {
                "name": op.sym_name.data,
                "shape": shape,
                "size": size,
                "wait_count": op.wait_count.value.data,
                "scope": et.scope.data,
                "counter_dtype": et.counter_dtype.data,
            },
        )
    return layout


def _kernel_name(graph: GraphOp) -> str:
    return f"megakernel_dyn_{graph.sym_name.data}"


@dataclass
class _TaskInfo:
    """Per-task metadata gathered from CallDeviceOps."""

    task_id: int
    kind: int
    device_func: str
    in_edges: list[tuple[str, int]]   # (event_name, linear_index)
    out_edges: list[tuple[str, int, int]]  # (event_name, linear_index, decrement)


def _coord_index(coord: Any) -> int | None:
    """Best-effort literal coordinate -- only supports literal integers."""
    parts: list[int] = []
    for el in coord.indices.data:
        s = el.data if hasattr(el, "data") else str(el)
        try:
            parts.append(int(s.strip()))
        except ValueError:
            return None
    if not parts:
        return 0
    # Linearise multi-d coords later; for Phase B MVP we use 1D events.
    if len(parts) > 1:
        return None
    return parts[0]


def _gather_tasks(
    graph: GraphOp,
    func_to_kind: dict[str, int],
) -> list[_TaskInfo]:
    """Build per-task in/out-edge metadata.

    Phase B MVP: literal integer coords only.  Symbolic / einsum coords
    are deferred to Phase B.3 (event.update / event.trigger lowering).
    """
    tasks: list[_TaskInfo] = []
    for call in graph.body.walk():
        if not isinstance(call, CallDeviceOp):
            continue
        func = call.device_func.root_reference.data
        kind = func_to_kind[func]

        # task_shape -> task_id range.  Phase B MVP: 1D shapes.
        dims = [
            d.value.data
            for d in call.task_shape.data
            if isinstance(d, IntegerAttr)
        ]
        n_tasks = 1
        for d in dims:
            n_tasks *= max(d, 1)

        # Per-task in/out edges: if the user provided one EventCoordAttr
        # per task position, distribute them.  Else, every task shares
        # the same edge list.
        def _per_task_edges(
            attr: Any, expected: int,
        ) -> list[list[tuple[str, int]]]:
            if attr is None:
                return [[] for _ in range(n_tasks)]
            entries = list(attr.data)
            if len(entries) == expected:
                # one edge per task
                out: list[list[tuple[str, int]]] = []
                for c in entries:
                    if hasattr(c, "event_ref"):
                        idx = _coord_index(c)
                        if idx is None:
                            raise ValueError(
                                "Phase B dynamic scheduler MVP only supports "
                                "literal integer event coords."
                            )
                        out.append([(c.event_ref.data, idx)])
                    else:
                        out.append([])
                return out
            else:
                shared: list[tuple[str, int]] = []
                for c in entries:
                    if hasattr(c, "event_ref"):
                        idx = _coord_index(c)
                        if idx is None:
                            raise ValueError(
                                "Phase B dynamic scheduler MVP only supports "
                                "literal integer event coords."
                            )
                        shared.append((c.event_ref.data, idx))
                return [list(shared) for _ in range(n_tasks)]

        in_edges_per_task = _per_task_edges(call.in_edges, n_tasks)
        out_edges_per_task = _per_task_edges(call.out_edges, n_tasks)

        for tid in range(n_tasks):
            outs: list[tuple[str, int, int]] = []
            for c in (call.out_edges.data if call.out_edges is not None else []):
                pass  # handled below
            # Pull decrements from the original coord attrs in order.
            for slot, edge in enumerate(out_edges_per_task[tid]):
                ev_name, linear_idx = edge
                # Default decrement = 1 unless the original coord said otherwise.
                # (Phase B MVP: every coord uses decrement 1.)
                outs.append((ev_name, linear_idx, 1))

            tasks.append(
                _TaskInfo(
                    task_id=tid,
                    kind=kind,
                    device_func=func,
                    in_edges=list(in_edges_per_task[tid]),
                    out_edges=outs,
                ),
            )
    return tasks


def _build_consumer_table(
    tasks: list[_TaskInfo],
) -> dict[tuple[str, int], list[tuple[int, int]]]:
    """For each event coordinate, list the (task_id, kind) consumers.

    A consumer of event coordinate ``(E, i)`` is any task whose in_edges
    include ``(E, i)``.  When the counter at ``E[i]`` hits zero, the
    dispatch loop pushes exactly those consumers -- *not* every consumer
    of ``E``.  Indexing by the full coord is required for correctness:
    in dynamic mode, distinct event indices fire independent consumers.
    """
    table: dict[tuple[str, int], list[tuple[int, int]]] = {}
    seen: dict[tuple[str, int], set[tuple[int, int]]] = {}
    for t in tasks:
        for ev_name, idx in t.in_edges:
            key = (ev_name, idx)
            entry = (t.task_id, t.kind)
            if entry not in seen.setdefault(key, set()):
                table.setdefault(key, []).append(entry)
                seen[key].add(entry)
    return table


def _initial_queue(tasks: list[_TaskInfo]) -> list[tuple[int, int]]:
    """Tasks with no in_edges get pushed onto the queue at launch."""
    return [(t.task_id, t.kind) for t in tasks if not t.in_edges]


def _signature_args(
    data_pointers: tuple[str, ...],
    event_names: list[str],
    constexpr_args: tuple[str, ...],
) -> tuple[str, str]:
    decl: list[str] = []
    call: list[str] = []
    for ptr in data_pointers:
        decl.append(ptr)
        call.append(ptr)
    for ev in event_names:
        decl.append(f"{ev}_ptr")
        call.append(f"{ev}_ptr")
    for ce in constexpr_args:
        decl.append(f"{ce}: tl.constexpr")
        call.append(ce)
    return ", ".join(decl), ", ".join(call)


def _emit_post_dispatch(
    tasks: list[_TaskInfo],
    consumer_table: dict[tuple[str, int], list[tuple[int, int]]],
    event_layout: list[dict[str, Any]],
) -> str:
    """Emit the per-(kind, task_id) post-body push-consumer logic.

    Each task instance gets its own conditional block, dispatched via
    ``if task_kind == K and task_id == T:`` chains.  This is fine for
    Phase B MVP scale (hundreds of tasks); a future optimisation can
    table-drive it via tl.load on a precomputed dispatch table.
    """
    if not tasks:
        return "        pass  # no tasks"

    # Build per-task index for cheap lookup.
    by_kind_task: dict[tuple[int, int], _TaskInfo] = {}
    for t in tasks:
        by_kind_task[(t.kind, t.task_id)] = t

    lines: list[str] = []
    first = True
    for (kind, tid), t in by_kind_task.items():
        if not t.out_edges:
            continue
        keyword = "if" if first else "elif"
        first = False
        lines.append(f"        {keyword} (task_kind == {kind}) and (task_id == {tid}):")
        for ev_name, linear_idx, decrement in t.out_edges:
            lines.append(
                f"            old = tl.atomic_add({ev_name}_ptr + {linear_idx}, -{decrement})"
            )
            # Push only the consumers waiting on THIS event coordinate.
            consumers = consumer_table.get((ev_name, linear_idx), [])
            if consumers:
                lines.append(f"            if old == {decrement}:")
                for c_tid, c_kind in consumers:
                    # MPMC ring-buffer push:
                    # 1) reserve a unique slot via QUEUE_TAIL_PTR (write counter)
                    # 2) write the payload to QUEUE_POOL_PTR
                    # 3) publish via atomic store on QUEUE_VALID_PTR[slot] -- this
                    #    provides release semantics so consumers that load the
                    #    valid flag with acquire semantics see the payload.
                    lines.append(
                        f"                slot = tl.atomic_add(QUEUE_TAIL_PTR + 0, 1)"
                    )
                    lines.append(
                        f"                tl.store(QUEUE_POOL_PTR + slot * 2 + 0, {c_tid})"
                    )
                    lines.append(
                        f"                tl.store(QUEUE_POOL_PTR + slot * 2 + 1, {c_kind})"
                    )
                    lines.append(
                        f"                tl.atomic_xchg(QUEUE_VALID_PTR + slot, 1)"
                    )
    if first:
        lines.append("        pass  # no out_edges on any task")
    return "\n".join(lines)


def _emit_dispatch_branches(
    funcs: list[str],
    func_to_kind: dict[str, int],
    call_args: str,
) -> str:
    branches: list[str] = []
    for k, fn in enumerate(funcs):
        kind = func_to_kind[fn]
        keyword = "elif" if k else "if"
        branches.append(f"        {keyword} task_kind == {kind}:")
        branches.append(f"            _run_{fn}(task_id, {call_args})")
    if not branches:
        branches = ["        pass  # no tasks"]
    return "\n".join(branches)


def lower_megakernel_dynamic(
    graph: GraphOp,
    spec: DynamicMegakernelLoweringSpec,
) -> DynamicMegakernelLoweringResult:
    """Lower an ``event.graph`` with policy=dynamic into persistent Triton.

    Requires the graph to have ``policy='dynamic'`` and (optionally) a
    ``compgen.static_schedule`` annotation -- the dynamic emitter reads
    only the graph structure + the user-supplied :class:`spec`.
    """
    if graph.policy.policy.data != "dynamic":
        raise ValueError(
            f"lower_megakernel_dynamic requires policy='dynamic', "
            f"got policy={graph.policy.policy.data!r}"
        )

    events = _event_layout(graph)
    event_names = [e["name"] for e in events]
    funcs = sorted({
        op.device_func.root_reference.data
        for op in graph.body.walk()
        if isinstance(op, CallDeviceOp)
    })
    func_to_kind = {fn: i for i, fn in enumerate(funcs)}

    tasks = _gather_tasks(graph, func_to_kind)
    consumer_table = _build_consumer_table(tasks)
    initial_queue = _initial_queue(tasks)
    total_tasks = len(tasks)

    by_name = {df.name: df for df in spec.device_functions}
    body_table: dict[str, DynamicDeviceFunctionSpec] = {}
    for fn in funcs:
        body_table[fn] = by_name.get(
            fn, DynamicDeviceFunctionSpec(name=fn, body_source="pass"),
        )

    dispatch_decl, dispatch_call = _signature_args(
        spec.data_pointers, event_names, spec.constexpr_args,
    )
    dispatch_branches = _emit_dispatch_branches(funcs, func_to_kind, dispatch_call)
    post_dispatch = _emit_post_dispatch(tasks, consumer_table, events)
    kernel_name = _kernel_name(graph)

    lines: list[str] = []
    lines.append("import triton")
    lines.append("import triton.language as tl")
    lines.append("")
    lines.append("# --- per-device-function bodies (pure compute, no event ops) ---")
    for fn in funcs:
        body = body_table[fn]
        lines.append("@triton.jit")
        lines.append(f"def _run_{fn}(task_id, {dispatch_decl}):")
        body_text = textwrap.dedent(body.body_source).strip("\n")
        if not body_text.strip():
            body_text = "pass"
        lines.append(textwrap.indent(body_text, "    "))
        lines.append("")

    # Megakernel signature.
    mk_decl: list[str] = []
    for ptr in spec.data_pointers:
        mk_decl.append(ptr)
    for ev in event_names:
        mk_decl.append(f"{ev}_ptr")
    mk_decl.append("QUEUE_POOL_PTR")
    mk_decl.append("QUEUE_HEAD_PTR")
    mk_decl.append("QUEUE_TAIL_PTR")
    mk_decl.append("QUEUE_VALID_PTR")
    for ce in spec.constexpr_args:
        mk_decl.append(f"{ce}: tl.constexpr")
    mk_decl.append("SM_COUNT: tl.constexpr")
    mk_decl.append("TOTAL_TASKS: tl.constexpr")
    mk_decl.append("MAX_QUEUE: tl.constexpr")

    lines.append("# --- persistent megakernel: dynamic on-GPU scheduler ---")
    lines.append("@triton.jit")
    lines.append(f"def {kernel_name}(")
    for part in mk_decl:
        lines.append(f"    {part},")
    lines.append("):")
    lines.append('    """Persistent megakernel emitted by ETC Algorithm 2.')
    lines.append("")
    lines.append("    grid = (SM_COUNT,); each program pops tasks from the global")
    lines.append("    queue, runs them, and pushes consumers when their event triggers.")
    lines.append('    """')
    lines.append("    # Each SM repeatedly pops a task slot and dispatches.")
    lines.append("    # Triton forbids 'return' inside loops -- use a done flag.")
    lines.append("    done = 0")
    lines.append("    while done == 0:")
    lines.append("        slot = tl.atomic_add(QUEUE_HEAD_PTR + 0, 1)")
    lines.append("        if slot >= TOTAL_TASKS:")
    lines.append("            done = 1")
    lines.append("        else:")
    lines.append("            # Acquire-load: spin until producer publishes valid[slot]=1.")
    lines.append("            # This is paired with the producer's atomic_xchg release on")
    lines.append("            # QUEUE_VALID_PTR + slot, so the regular tl.load below sees")
    lines.append("            # the payload writes that preceded the release.")
    lines.append("            valid = tl.atomic_or(QUEUE_VALID_PTR + slot, 0)")
    lines.append("            while valid == 0:")
    lines.append("                valid = tl.atomic_or(QUEUE_VALID_PTR + slot, 0)")
    lines.append("            task_id   = tl.load(QUEUE_POOL_PTR + slot * 2 + 0)")
    lines.append("            task_kind = tl.load(QUEUE_POOL_PTR + slot * 2 + 1)")
    # Dispatch + post-dispatch must live inside the `else` arm.
    for body_line in dispatch_branches.splitlines():
        # Add 4 spaces of extra indent to push everything inside `else:`.
        lines.append("    " + body_line)
    lines.append("            # --- post-dispatch: notify out_edges + push consumers ---")
    for body_line in post_dispatch.splitlines():
        lines.append("    " + body_line)
    lines.append("")

    kernel_source = "\n".join(lines)

    sm_count = (
        graph.sm_count.value.data
        if graph.sm_count is not None
        else min(8, max(1, total_tasks))
    )

    return DynamicMegakernelLoweringResult(
        kernel_name=kernel_name,
        kernel_source=kernel_source,
        launch_config={
            "grid": int(sm_count),
            "num_warps": spec.num_warps,
            "num_stages": spec.num_stages,
        },
        event_layout=events,
        device_function_table={func_to_kind[fn]: fn for fn in funcs},
        initial_queue=initial_queue,
        consumer_table=consumer_table,
        total_tasks=total_tasks,
    )


__all__ = [
    "DynamicDeviceFunctionSpec",
    "DynamicMegakernelLoweringResult",
    "DynamicMegakernelLoweringSpec",
    "lower_megakernel_dynamic",
]
