"""Generate xDSL dialect scaffolding from a declarative spec."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class DialectOperandSpec:
    name: str
    type_expr: str


@dataclass(frozen=True)
class DialectResultSpec:
    name: str
    type_expr: str


@dataclass(frozen=True)
class DialectOpSpec:
    name: str
    operands: tuple[DialectOperandSpec, ...] = ()
    results: tuple[DialectResultSpec, ...] = ()
    traits: tuple[str, ...] = ()
    summary: str = ""


@dataclass(frozen=True)
class DialectSpec:
    name: str
    python_module: str
    ops: tuple[DialectOpSpec, ...] = ()
    doc: str = ""


def _coerce_dialect_spec(spec: DialectSpec | dict[str, Any]) -> DialectSpec:
    if isinstance(spec, DialectSpec):
        return spec
    ops = []
    for op in spec.get("ops", []):
        operands = tuple(
            DialectOperandSpec(name=str(item["name"]), type_expr=str(item["type_expr"]))
            for item in op.get("operands", [])
        )
        results = tuple(
            DialectResultSpec(name=str(item["name"]), type_expr=str(item["type_expr"]))
            for item in op.get("results", [])
        )
        ops.append(
            DialectOpSpec(
                name=str(op["name"]),
                operands=operands,
                results=results,
                traits=tuple(str(item) for item in op.get("traits", [])),
                summary=str(op.get("summary", "")),
            )
        )
    return DialectSpec(
        name=str(spec["name"]),
        python_module=str(spec.get("python_module", spec["name"])),
        ops=tuple(ops),
        doc=str(spec.get("doc", "")),
    )


def generate_xdsl_dialect(spec: DialectSpec | dict[str, Any]) -> dict[str, str]:
    """Emit xDSL dialect scaffolding files for a declarative dialect spec."""

    spec = _coerce_dialect_spec(spec)
    module_lines = [
        '"""Generated xDSL dialect scaffolding."""',
        "",
        "from __future__ import annotations",
        "",
        "from xdsl.ir import Dialect",
        "from xdsl.irdl import IRDLOperation, irdl_op_definition, operand_def, result_def",
        "from xdsl.traits import Pure",
        "",
    ]

    op_names: list[str] = []
    for op in spec.ops:
        class_name = "".join(piece.capitalize() for piece in op.name.split("_")) + "Op"
        op_names.append(class_name)
        module_lines.append("@irdl_op_definition")
        module_lines.append(f"class {class_name}(IRDLOperation):")
        module_lines.append(f'    name = "{spec.name}.{op.name}"')
        for operand in op.operands:
            module_lines.append(f"    {operand.name} = operand_def({operand.type_expr})")
        for result in op.results:
            module_lines.append(f"    {result.name} = result_def({result.type_expr})")
        if "Pure" in op.traits:
            module_lines.append("    traits = frozenset((Pure(),))")
        if op.summary:
            module_lines.append(f'    __doc__ = "{op.summary}"')
        module_lines.append("")

    dialect_name = "".join(piece.capitalize() for piece in spec.python_module.split("_"))
    module_lines.append(f"{dialect_name} = Dialect(")
    module_lines.append(f'    "{spec.name}",')
    module_lines.append(f"    [{', '.join(op_names)}],")
    module_lines.append("    [],")
    module_lines.append(")")
    module_lines.append("")

    init_lines = [
        '"""Generated xDSL dialect package."""',
        "",
        f"from .dialect import {dialect_name}",
        "",
        f'__all__ = ["{dialect_name}"]',
    ]
    readme_lines = [
        f"# {spec.name} xDSL Dialect",
        "",
        spec.doc or "Generated by CompGen from a declarative dialect spec.",
        "",
        "## Ops",
    ]
    for op in spec.ops:
        readme_lines.append(f"- `{spec.name}.{op.name}`: {op.summary or 'generated op scaffold'}")

    return {
        "__init__.py": "\n".join(init_lines) + "\n",
        "dialect.py": "\n".join(module_lines) + "\n",
        "README.md": "\n".join(readme_lines) + "\n",
    }


__all__ = [
    "DialectOpSpec",
    "DialectOperandSpec",
    "DialectResultSpec",
    "DialectSpec",
    "generate_xdsl_dialect",
]
