"""C++ host plan executor emitter (, Phase G).

Phase G companion to :mod:`compgen.runtime.glue_emit.c11_baremetal`
for the **CUDA host** path. Same shape as (the §12 Dream-1 emit
target), but the emit is C++ (``.cpp``) and the driver baked into the
emit is ``"cuda"`` instead of ``"cpu_sync"``. The push-constants block
follows the libcompgen_rt CUDA executable contract:

::

    [grid_x, grid_y, grid_z, block_x, block_y, block_z]  // 6 × uint32

(see ``cg_rt_executable_create_cuda_ptx`` in compgen_rt.h). The emit
calls only ``cg_rt_*`` and ``compgen_kernel_*`` externs; the
ABI-conformance gate rejects any emit that calls ``cudaMalloc``,
``cuLaunchKernel``, or any other vendor primitive directly.

The differential acceptance is against the Python CUDA emitter
. Both consume the same plan, both must produce the same
``cg_rt_command_buffer_dispatch`` sequence with the same kernel
arguments. The D6 plan-refinement gate codifies the
"every plan op corresponds to one emit launch in the right order"
invariant.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from compgen.runtime.execution_plan import ExecutionPlan
from compgen.runtime.glue_emit.c11_baremetal import (
    _PLAN_VIOLATION_CODES,
    _render_dispatch_block,
    _render_header,
    _render_io_assertions,
)
from compgen.runtime.glue_emit.plan_assertions import (
    collect_region_assertions,
)
from compgen.runtime.glue_emit.python_sync import (
    _read_yaml_or_json_plan,
    _topological_region_order,
)


_CPP_EMIT_SCHEMA_VERSION = "plan_executor_cpp_host_manifest_v1"


@dataclass(frozen=True)
class CppHostGlueEmitResult:
    out_dir: Path
    executor_path: Path
    header_path: Path
    manifest_path: Path
    overall: str
    bound_regions: tuple[str, ...]
    unbound_regions: tuple[str, ...]
    plan_violation_codes: dict[str, int]


def _utcnow() -> str:
    return datetime.now(tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def _render_cpp_executor_source(
    *,
    plan: ExecutionPlan,
    plan_path: str,
    region_order: list[str],
    region_assertions: list[Any],
) -> str:
    """Render the full generated_plan_executor.cpp body for CUDA host."""
    bindings_by_region = {
        b.region_id: b for b in plan.region_kernel_bindings
    }
    unbound = [r for r in region_order if r not in bindings_by_region]
    unbound_check = ""
    if unbound:
        first = unbound[0]
        unbound_check = (
            "    /* Plan declared region(s) M-46 could not bind. */\n"
            "    status->code = COMPGEN_PLAN_VIOLATION_UNBOUND_REGION;\n"
            f'    status->detail = "region {first!r} has no certified '
            f'kernel binding (M-46)";\n'
            "    return status->code;\n"
        )

    io_assertions = _render_io_assertions(region_assertions)
    dispatch_block, externs = _render_dispatch_block(
        region_order=region_order,
        bindings_by_region=bindings_by_region,
    )
    extern_decls = "\n".join(
        f'extern "C" cg_rt_executable_t *{sym};' for sym in externs
    ) or '/* no bound regions — no kernel externs */'

    return f'''/* Auto-generated by M-89 (compgen.runtime.glue_emit.cpp_host).
 *
 * Workload : {plan.workload}
 * Target   : {plan.target}
 * Source   : {plan_path}
 *
 * DO NOT EDIT — regenerate by re-running ``--stop-after glue-emit``.
 *
 * This is the §12 Dream-1 emitted Layer-1 plan executor, CUDA host
 * variant. It calls the libcompgen_rt ABI (cg_rt_*) only; no CUDA
 * primitive is referenced directly. The M-91 ABI-conformance gate
 * grep-checks the emitted source for non-cg_rt_ externs.
 */

#include <cstddef>
#include <cstdint>
#include <cstring>

extern "C" {{
#include "compgen_rt/compgen_rt.h"
}}
#include "generated_plan_executor.h"

/* Kernel pack externs (one per bound region). M-49 supplies a TU
 * that defines each of these as a cg_rt_executable_t * obtained
 * via cg_rt_executable_create_cuda_ptx() at module-init time. */
{extern_decls}

/* Driver name baked into the emit. M-89: cuda. */
static const char *const COMPGEN_DRIVER_NAME = "cuda";

extern "C" int compgen_run(const compgen_io_t *io,
                           compgen_status_t   *status) {{
    if (status == nullptr) {{
        return COMPGEN_PLAN_VIOLATION_IO_NULL;
    }}
    status->code = 0;
    status->rt_status = 0;
    status->detail = nullptr;

    if (io == nullptr) {{
        status->code = COMPGEN_PLAN_VIOLATION_IO_NULL;
        status->detail = "io pointer is NULL";
        return status->code;
    }}

{unbound_check}{io_assertions}

    cg_rt_instance_t       *instance       = nullptr;
    cg_rt_device_t         *device         = nullptr;
    cg_rt_command_buffer_t *command_buffer = nullptr;
    cg_rt_semaphore_t      *signal_sem     = nullptr;
    cg_rt_status_t          rt_status      = 0;

    /* CUDA push-constants layout: 6 × uint32 = grid_x, grid_y, grid_z,
     * block_x, block_y, block_z. M-49 binding map populates these. */
    uint32_t push_constants[6] = {{1, 1, 1, 64, 1, 1}};
    cg_rt_buffer_t *bindings[32] = {{nullptr}};
    size_t          n_bindings   = 0;

    rt_status = cg_rt_instance_create(COMPGEN_DRIVER_NAME, &instance);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_instance_create failed (cuda)";
        return status->code;
    }}
    rt_status = cg_rt_device_open(instance, 0, &device);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_device_open failed";
        goto cleanup;
    }}
    rt_status = cg_rt_command_buffer_create(device, &command_buffer);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_command_buffer_create failed";
        goto cleanup;
    }}
    rt_status = cg_rt_command_buffer_begin(command_buffer);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_command_buffer_begin failed";
        goto cleanup;
    }}

{dispatch_block}

    rt_status = cg_rt_command_buffer_end(command_buffer);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_command_buffer_end failed";
        goto cleanup;
    }}

    rt_status = cg_rt_semaphore_create(device, 0, &signal_sem);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_semaphore_create failed";
        goto cleanup;
    }}
    {{
        cg_rt_semaphore_point_t signal_point;
        signal_point.semaphore = signal_sem;
        signal_point.value = 1;
        rt_status = cg_rt_queue_submit(device, 0, nullptr, 0,
                                       &signal_point, 1, command_buffer);
        if (rt_status != 0) {{
            status->code = rt_status; status->rt_status = rt_status;
            status->detail = "cg_rt_queue_submit failed";
            goto cleanup;
        }}
    }}
    rt_status = cg_rt_semaphore_wait(signal_sem, 1, CG_RT_TIMEOUT_INFINITE);
    if (rt_status != 0) {{
        status->code = rt_status; status->rt_status = rt_status;
        status->detail = "cg_rt_semaphore_wait failed";
        goto cleanup;
    }}

cleanup:
    if (signal_sem)     cg_rt_semaphore_destroy(signal_sem);
    if (command_buffer) cg_rt_command_buffer_destroy(command_buffer);
    if (device)         cg_rt_device_close(device);
    if (instance)       cg_rt_instance_destroy(instance);

    (void)push_constants; (void)bindings; (void)n_bindings;

    return status->code;
}}
'''


def emit_cpp_host_executor(run_dir: Path) -> CppHostGlueEmitResult:
    """Read the plan from disk, render the C++ host executor +
    header (the same header emits — the ABI is identical), and
    persist them under ``06_glue_emit/``. The C++ source coexists
    with the C source in the same directory so an operator can pick
    either backend at build time.
    """
    run_dir = Path(run_dir).resolve()
    plan_path = run_dir / "05_execution_plan" / "execution_plan.yaml"
    if not plan_path.exists():
        plan_path = run_dir / "05_execution_plan" / "execution_plan.json"
    if not plan_path.exists():
        raise FileNotFoundError(
            f"M-46 execution plan not found at "
            f"{run_dir / '05_execution_plan'}; run --stop-after "
            f"execution-plan-emit first"
        )
    plan_dict = _read_yaml_or_json_plan(plan_path)
    plan = ExecutionPlan.from_dict(plan_dict)

    region_order = _topological_region_order(plan)
    bound = tuple(b.region_id for b in plan.region_kernel_bindings)
    placement_regions = tuple(rp.region_id for rp in plan.region_placement)
    unbound = tuple(r for r in placement_regions if r not in bound)

    bindings_dicts = [
        {
            "region_id": b.region_id, "status": "bound",
            "contract_hash": b.contract_hash,
            "certificate_path": b.certificate_path,
        }
        for b in plan.region_kernel_bindings
    ]
    region_assertions = collect_region_assertions(
        run_dir=run_dir, bindings=bindings_dicts,
    )

    out_dir = run_dir / "06_glue_emit"
    out_dir.mkdir(parents=True, exist_ok=True)

    rel_plan = str(plan_path.relative_to(run_dir))
    header_path = out_dir / "generated_plan_executor.h"
    # The header is identical across (ABI is shared);
    # we only (re)write it if it doesn't already exist so the C and
    # C++ emit modes are co-installable.
    if not header_path.exists():
        header_path.write_text(
            _render_header(
                workload=plan.workload,
                target=plan.target,
                plan_path=rel_plan,
            ),
            encoding="utf-8",
        )

    executor_path = out_dir / "generated_plan_executor.cpp"
    executor_path.write_text(
        _render_cpp_executor_source(
            plan=plan,
            plan_path=rel_plan,
            region_order=region_order,
            region_assertions=region_assertions,
        ),
        encoding="utf-8",
    )

    manifest_path = out_dir / "plan_executor_cpp_host_manifest.json"
    plan_violation_codes = {name: val for name, val in _PLAN_VIOLATION_CODES}
    manifest_path.write_text(
        json.dumps({
            "schema_version": _CPP_EMIT_SCHEMA_VERSION,
            "generated_at_utc": _utcnow(),
            "workload": plan.workload,
            "target": plan.target,
            "executor_kind": "cpp_host",
            "executor_path": str(executor_path.relative_to(run_dir)),
            "header_path": str(header_path.relative_to(run_dir)),
            "source_plan_path": rel_plan,
            "bound_regions": list(bound),
            "unbound_regions": list(unbound),
            "region_order": region_order,
            "plan_violation_codes": plan_violation_codes,
            "abi": {
                "driver_name": "cuda",
                "uses_only_cg_rt": True,
                "kernel_extern_prefix": "compgen_kernel_",
                "push_constants_layout": "u32[6]:grid_xyz,block_xyz",
            },
            "kernel_bindings": [
                {
                    "region_id": b.region_id,
                    "contract_hash": b.contract_hash,
                    "certificate_path": b.certificate_path,
                    "kernel_artifact": b.kernel_artifact,
                    "dispatch_model": b.dispatch_model,
                }
                for b in plan.region_kernel_bindings
            ],
        }, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    overall = "pass" if bound else "skipped"
    return CppHostGlueEmitResult(
        out_dir=out_dir,
        executor_path=executor_path,
        header_path=header_path,
        manifest_path=manifest_path,
        overall=overall,
        bound_regions=bound,
        unbound_regions=unbound,
        plan_violation_codes=plan_violation_codes,
    )
