#!/usr/bin/env python3
"""One page listing every measured run and replayed arm, with what distinguishes it.

There are 30 XPU-RT solver arms, 13 further board points, 74 ROS 2 entries, 85 replayed cadence
traces and 70 figure sidecars. Each registry is authoritative for its own column and none of them
answers the question a reader actually has: *what is the difference between this run and the one next
to it, and which figure draws it?* This generates that, from the registries themselves, so it cannot
drift from them.

    scripts/run_index.py [--out docs/Artifact/run_index.md] [--check]

`--check` regenerates in memory and exits non-zero if the committed page is stale, so the page is a
derived artifact rather than a document someone has to remember to update.
"""
from __future__ import annotations

import argparse
import collections
import glob
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "scripts"))


def figures_by_trace():
    """ctrl_trace -> the figure stems that replay it, from the sidecars."""
    out = collections.defaultdict(set)
    for m in glob.glob(os.path.join(REPO, "results/codesign_feedback/refined/*_metrics.json")):
        try:
            d = json.load(open(m))
        except Exception:
            continue
        A = d.get("A") if isinstance(d, dict) else None
        if not isinstance(A, dict):
            continue
        stem = os.path.basename(m).replace("_metrics.json", "")
        for k in ("xpu_trace", "ros_trace"):
            if A.get(k):
                out[A[k]].add(stem)
    return out


def board_recipe(arm):
    """(executed table, how it was produced) for one XPU-RT arm, from its own run manifest.

    The manifest of every arm names the schedule that ran, and the schedule's name says which of the
    two board recipes produced it: `fig_<tag>_<solver>_clamped.json` comes from the stage-2 pair
    (solve_stage2_hard then board_stage2), `scheduled_<spec>_..._clamped.json` from a direct solve
    carried through the codegen contract by board_partitioned30. Deriving it here means the index
    cannot claim a recipe the run did not use.
    """
    import glob as _g, json as _j
    m = sorted(_g.glob(os.path.join(REPO, "results/codesign_feedback/xpurt_long",
                                    f"manifest_{arm}1_other_run1.json")))
    if not m:
        return "", ""
    d = _j.load(open(m[0]))
    tbl = os.path.basename(d.get("schedule_relpath") or d.get("schedule") or "")
    if tbl.startswith("fig_") and "_clamped" in tbl:
        tag = tbl[len("fig_"):].split("_cpsat")[0].split("_greedy")[0]
        return tbl, f"`solve_stage2_hard.sh <spec> {tag}` then `board_stage2.sh {tag} <spec>`"
    if tbl.startswith("scheduled_"):
        spec = tbl[len("scheduled_"):].split("_cpsat")[0].split("_greedy")[0]
        return tbl, (f"`run_xpurt_schedule.py --networks-json data/toplevel/{spec}.json` then "
                     f"`board_partitioned30.sh <table> {arm.rstrip('r')} gen/mb_shard_nav`")
    return tbl, ""


def render():
    import measured_timing as MT
    import figure_constants as FC

    figs = figures_by_trace()
    trace_of = collections.defaultdict(list)          # derive key -> traces replaying that arm
    for t, a in FC.ARM_BY_TRACE.items():
        if a.derive:
            trace_of[(a.derive[0], a.derive[1])].append(t)

    L = ["# Run index — every measured arm, and what makes it different",
         "",
         "Generated by `scripts/run_index.py` from the registries themselves; `--check` fails if this",
         "page and the registries disagree. It answers one question the per-registry files do not:",
         "given two runs, what changed, and which figure draws each.",
         "",
         "`chain` is camera→control on the K1. `gap` is the control-output period, so `1000/gap` is the",
         "command rate a flight replays. **Latency and cadence are separate switches** — an arm can have",
         "a fast chain and a slow command rate, which is the whole subject of the showdown figures.",
         ""]

    # ---- XPU-RT -----------------------------------------------------------------
    L += ["## 1. XPU-RT board arms", "",
          "One row per solved-and-executed table. The differences that matter are the camera period the",
          "spec was solved for, whether the placement was given or left to the solver, and whether",
          "convolution went to the IME.", "",
          "| arm | what it is | chain ms | gap ms | rate Hz | frames late | replayed as | drawn in |",
          "|---|---|---|---|---|---|---|---|"]
    for k in sorted(MT.SOLVER_ARMS):
        v = MT.SOLVER_ARMS[k]
        ts = sorted(trace_of.get(("SOLVER_ARMS", k), []))
        fs = sorted({f for t in ts for f in figs.get(t, ())})
        gap = v.get("ctrl_gap_mean_ms")
        L.append(f"| `{k}` | {v.get('solver', '—')} | {v.get('chain_ms', '—')} | {gap or '—'} | "
                 f"{f'{1000.0 / gap:.0f}' if gap else '—'} | {v.get('frames_late', '—')} | "
                 f"{', '.join('`' + t + '`' for t in ts) or '—'} | {', '.join(fs) or '—'} |")

    pts = getattr(MT, "XPURT_POINTS", {})
    if pts:
        L += ["", "### 1b. Further board points", "",
              "Measured the same way but not part of a solver sweep — ablations and one-off arms.", "",
              "| point | chain ms | note |", "|---|---|---|"]
        for k in sorted(pts):
            v = pts[k]
            note = v.get("solver") or v.get("note") or "—"
            L.append(f"| `{k}` | {v.get('chain_ms', '—')} | {note} |")

    L += ["", "### 1c. Reproducing an XPU-RT arm", "",
          "Each row is derived from that arm's own run manifest, so it names the table the board",
          "actually executed rather than the one a document remembers. `<spec>` is the workload under",
          "`data/toplevel/`; §1 says which camera rate each arm was solved for.", "",
          "| arm | executed table | tracked | how it was produced |", "|---|---|---|---|"]
    import subprocess as _sp
    for k in sorted(MT.SOLVER_ARMS):
        tbl, how = board_recipe(k)
        if not tbl:
            continue
        rel = f"schedules/{tbl}"
        tr = _sp.run(["git", "-C", REPO, "ls-files", "--error-unmatch", rel],
                     capture_output=True).returncode == 0
        L.append(f"| `{k}` | `{tbl}` | {'yes' if tr else 'no'} | {how or '—'} |")

    # ---- ROS 2 ------------------------------------------------------------------
    L += ["", "## 2. ROS 2 board arms", "",
          "Layout (which node on which hart, how many processes, chained or timer control) is in",
          "[`ros_arms_catalog.md`](../Baselines/ros_arms_catalog.md), which is generated from the run manifests. Here",
          "is what each arm *measured*, so two rows can be compared directly.", "",
          "| arm | camera Hz | chain→goal ms | gap ms | rate Hz | replayed as | drawn in |",
          "|---|---|---|---|---|---|---|"]
    rows = []
    for (arm, hz), v in MT.ROS_VANILLA.items():
        rows.append((arm, hz, v, ("ROS_VANILLA", (arm, hz))))
    for tag, v in getattr(MT, "ROS_SENSITIVITY", {}).items():
        hz = tag.split("_")[0]
        rows.append((tag, int(hz) if hz.isdigit() else "—", v, ("ROS_SENSITIVITY", tag)))
    for arm, hz, v, key in sorted(rows, key=lambda r: (str(r[0]), str(r[1]))):
        ts = sorted(trace_of.get(key, []))
        fs = sorted({f for t in ts for f in figs.get(t, ())})
        gap = v.get("ctrl_gap_mean_ms")
        L.append(f"| `{arm}` | {hz} | {v.get('chain_goal_ms', v.get('e2e_goal_med_ms', '—'))} | "
                 f"{gap or '—'} | {f'{1000.0 / gap:.0f}' if gap else '—'} | "
                 f"{', '.join('`' + t + '`' for t in ts) or '—'} | {', '.join(fs) or '—'} |")

    # ---- replay arms ------------------------------------------------------------
    L += ["", "## 3. Replayed cadence traces", "",
          "A flight runs neither runtime. It replays one of these — a control-output cadence cut from a",
          "board trace — with the arm's measured camera→control latency injected. `hold` is the goal",
          "hold, one camera period where the baseline cannot refresh faster than the camera.", "",
          "| trace | injected lat ms | hold ms | camera Hz | re-derives from | drawn in |",
          "|---|---|---|---|---|---|"]
    for t in sorted(FC.ARM_BY_TRACE):
        a = FC.ARM_BY_TRACE[t]
        d = f"`{a.derive[1]}`" if a.derive else "—"
        L.append(f"| `{t}` | {a.csv_lat} | {a.csv_hold} | {a.cam_hz} | {d} | "
                 f"{', '.join(sorted(figs.get(t, ()))) or '—'} |")

    L += ["", "## 4. Reading two rows against each other", "",
          "The comparisons the figures are built on, and the single thing that differs in each:", "",
          "| pair | what differs | where |",
          "|---|---|---|",
          "| `p45freer` vs `acpsat_hardr` | the placement: solved, or given by hand. Same spec, same camera. | `showdown_45hz_solver_vs_rospinned_s1007` against `..._pinned_vs_rospinned_s1011` |",
          "| `p36freer` vs `p45freer` | the camera period the spec was solved for, 27.8 ms against 22.2 ms | the 36 Hz and 45 Hz figures |",
          "| `p45freer` vs `p45detr` | the solver's worker count: 8, or 1 for a table reproducible by recipe | not drawn; `p45detr` is the determinism check |",
          "| `w2pg36base` vs `w2pg36ime` | whether convolution goes to the IME. Same source tree, built twice. | neither is drawn — see `artifact_checklist.md` §5 |",
          "| `vanilla4x2` vs `vanilla4x2ns4c` | a four-way pool under the nav net as well as YOLO | `showdown_36hz_solver_vs_rosallhart_s1006` |",
          "| `cp3` vs `vanilla4` | a static pinned partition against ROS 2 unpinned as normally written | `..._pinned_vs_rospinned_s1011` against `..._pinned_vs_rosdefault_s1000` |",
          ""]
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(REPO, "docs/Artifact/run_index.md"))
    ap.add_argument("--check", action="store_true", help="fail if the committed page is stale")
    a = ap.parse_args()
    text = render()
    if a.check:
        cur = open(a.out).read() if os.path.exists(a.out) else ""
        if cur != text:
            print(f"FAIL  {os.path.relpath(a.out, REPO)} is stale; regenerate with scripts/run_index.py")
            return 1
        print(f"PASS  {os.path.relpath(a.out, REPO)} matches the registries")
        return 0
    open(a.out, "w").write(text)
    print(f"wrote {a.out}: {text.count(chr(10))} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
