/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 26
#define FLOWC_N_LANES 12

static const int flowc_e12_deps[] = { 3 };
static const int flowc_e18_deps[] = { 10 };
static const int flowc_e23_deps[] = { 2 };
static const int flowc_e25_deps[] = { 24 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "dronet", 0, 0, "qnn_graph", "dronet_full", "dsp", 6, 0.000000, 0.645000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 0, 24, 0, 23 },
    { 1, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.000000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 2, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 0.645000, 13.267000, 0, NULL, 0, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 2, 103, 0, 102 },
    { 3, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 2.182000, 13.909000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 3, 103, 0, 102 },
    { 4, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 3.000000, 0.107000, 0, NULL, 1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 5, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 6.000000, 0.107000, 0, NULL, 4, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 6, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 9.000000, 0.107000, 0, NULL, 5, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 7, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 12.000000, 0.107000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 8, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 15.000000, 0.107000, 0, NULL, 7, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 9, "dronet", 1, 0, "qnn_graph", "dronet_full", "cpu", 5, 15.895000, 6.998000, 0, NULL, 8, "CPU", "libQnnCpu.so", "ctx_dronet_full_hta__Cpu.bin", "dronet_full_hta", 0, 4, 24, 0, 23 },
    { 10, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 16.091000, 13.909000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 5, 103, 0, 102 },
    { 11, "mlp_control", 6, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 18.445000, 0.589000, 0, NULL, 2, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 12, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 19.034000, 15.377000, 1, flowc_e12_deps, 11, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 7, 146, 103, 248 },
    { 13, "mlp_control", 7, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 22.893000, 0.107000, 0, NULL, 8, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 14, "mlp_control", 8, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 25.893000, 0.107000, 0, NULL, 13, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 15, "mlp_control", 9, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 27.000000, 0.107000, 0, NULL, 14, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 16, "dronet", 2, 0, "qnn_graph", "dronet_full", "hta", 7, 30.000000, 2.030000, 0, NULL, 3, "HTA", "libQnnHta.so", "ctx_dronet_full_hta__Hta.bin", "dronet_full_hta", 1, 8, 24, 0, 23 },
    { 17, "mlp_control", 10, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 30.000000, 0.107000, 0, NULL, 15, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 1, 7, 0, 6 },
    { 18, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "cpu", 5, 30.107000, 39.464000, 1, flowc_e18_deps, 17, "CPU", "libQnnCpu.so", "ctx_yolov8n_head__Cpu.bin", "yolov8n_HTA_split_seg101", 0, 9, 146, 103, 248 },
    { 19, "mlp_control", 11, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 34.411000, 0.589000, 0, NULL, 11, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 20, "mlp_control", 12, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 36.000000, 0.589000, 0, NULL, 19, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 21, "mlp_control", 13, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 39.000000, 0.589000, 0, NULL, 20, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 22, "mlp_control", 14, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 42.000000, 0.589000, 0, NULL, 21, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 6, 7, 0, 6 },
    { 23, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 42.589000, 15.377000, 1, flowc_e23_deps, 21, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 2, 146, 103, 248 },
    { 24, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 44.057000, 13.909000, 0, NULL, 16, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 10, 103, 0, 102 },
    { 25, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 57.966000, 15.377000, 1, flowc_e25_deps, 22, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 11, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "dsp|dronet",
    "cpu|mlp_control",
    "dsp|yolov8n_d",
    "hta|yolov8n_a",
    "cpu|dronet",
    "hta|yolov8n_c",
    "dsp|mlp_control",
    "dsp|yolov8n_a",
    "hta|dronet",
    "cpu|yolov8n_c",
    "hta|yolov8n_b",
    "dsp|yolov8n_b",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 6, 5, 6, 7, 4, 7, 6, 6, 7, 5, 7, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 276, 200, 200, 2000, 200, 200, 200, 200, 2000, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 40, 0, 0, 40, 0, 0, 0, 0, 40, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "6",
    "4,5",
    "6",
    "7",
    "4,5",
    "7",
    "6",
    "6",
    "7",
    "4,5",
    "7",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
