#!/usr/bin/env bash
#
# Phase 2: Convert vision slices to quantized DLCs for DSP + CPU execution.
#
# Pipeline per DSP segment:
#   1. snpe-onnx-to-dlc → fp32 DLC
#   2. qairt-quantizer (int8) with realistic calibration data
#   3. (optional) qnn-context-binary-generator --backend libQnnDsp.so
#
# Pipeline per CPU segment (trivial single Tanh):
#   1. snpe-onnx-to-dlc → fp32 DLC (no quantization needed)
#
# Calibration data is generated by running the original model through
# onnxruntime and capturing intermediate activations at all boundary
# tensors (realistic distribution, not random noise).
#
# Usage:
#   ./build_vision_slices.sh                # full pipeline
#   ./build_vision_slices.sh --gen-calib    # only generate calibration data
#   ./build_vision_slices.sh --convert-only # only convert ONNX → DLC (skip quantize)
#   ./build_vision_slices.sh --seg=3        # process only dsp_seg_03
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SLICES_DIR="$SCRIPT_DIR/vision_slices"
DLC_DIR="$SLICES_DIR/dlc"
CALIB_DIR="$SLICES_DIR/calibration"
QNN_SDK="${QNN_SDK:-/scratch2/dima/misc_sw/qualcomm/qairt/2.45.0.260326}"
DOCKER_IMAGE="qnn-convert"
PYTHON="${PYTHON:-/scratch2/dima/miniforge3/envs/xpurt/bin/python}"
NUM_CALIB=10

# Parse args
GEN_CALIB=true
CONVERT=true
QUANTIZE=true
SEG_FILTER=""

for arg in "$@"; do
    case $arg in
        --gen-calib)    CONVERT=false; QUANTIZE=false ;;
        --convert-only) GEN_CALIB=false; QUANTIZE=false ;;
        --seg=*)        SEG_FILTER="${arg#*=}" ;;
        *) echo "Unknown arg: $arg"; exit 1 ;;
    esac
done

mkdir -p "$DLC_DIR" "$CALIB_DIR"

docker_run() {
    sudo docker run --rm \
        -v "$QNN_SDK":/qnn:ro \
        -v "$SLICES_DIR":/workspace \
        "$DOCKER_IMAGE" "$@"
}

# ===========================================================================
# Step 1: Generate calibration data from real activations
# ===========================================================================
if $GEN_CALIB; then
    echo "=== Generating calibration data (${NUM_CALIB} samples) ==="
    $PYTHON "$SCRIPT_DIR/gen_vision_slice_calibration.py" \
        --src "$SCRIPT_DIR/smolvlm_vision.onnx" \
        --slices-dir "$SLICES_DIR" \
        --out-dir "$CALIB_DIR" \
        --num-samples $NUM_CALIB
    echo ""
fi

# ===========================================================================
# Step 2: Convert and quantize DSP segments
# ===========================================================================
if $CONVERT; then
    echo "=== Converting DSP segments ==="
    for seg_onnx in "$SLICES_DIR"/dsp_seg_*.onnx; do
        seg_name="$(basename "$seg_onnx" .onnx)"
        seg_idx="${seg_name#dsp_seg_}"

        if [ -n "$SEG_FILTER" ] && [ "$seg_idx" != "$(printf '%02d' "$SEG_FILTER")" ]; then
            continue
        fi

        echo "--- $seg_name ---"

        # Build --input_layout flags from the ONNX inputs
        INPUT_FLAGS=$($PYTHON -c "
import onnx
model = onnx.load('$seg_onnx')
flags = []
for inp in model.graph.input:
    dims = [d.dim_value for d in inp.type.tensor_type.shape.dim]
    flags.append('-d {} {}'.format(inp.name, ','.join(str(d) for d in dims)))
    if len(dims) == 4:
        flags.append('--input_layout {} NCHW'.format(inp.name))
    else:
        flags.append('--input_layout {} NONTRIVIAL'.format(inp.name))
print(' '.join(flags))
")

        # Convert ONNX → DLC
        echo "  Converting to DLC..."
        docker_run bash -c "\
            pip install -q 'numpy<2' && \
            python3.10 /qnn/bin/x86_64-linux-clang/snpe-onnx-to-dlc \
                --input_network /workspace/${seg_name}.onnx \
                ${INPUT_FLAGS} \
                --output_path /workspace/dlc/${seg_name}.dlc" 2>&1 | tail -5
        sudo chown "$(id -u):$(id -g)" "$DLC_DIR/${seg_name}.dlc"
        echo "  DLC: $(du -h "$DLC_DIR/${seg_name}.dlc" | cut -f1)"

        if $QUANTIZE; then
            # Build calibration input list
            # Each line: "input0_name:=/path/to/raw input1_name:=/path/to/raw ..."
            CAL_LIST="$CALIB_DIR/${seg_name}_cal_list.txt"
            $PYTHON -c "
import onnx, os
model = onnx.load('$seg_onnx')
input_names = [inp.name for inp in model.graph.input]
lines = []
for i in range($NUM_CALIB):
    parts = []
    for name in input_names:
        path = '/workspace/calibration/{}_{}_{}.raw'.format('$seg_name', name, i)
        parts.append('{}:={}'.format(name, path))
    lines.append(' '.join(parts))
with open('$CAL_LIST', 'w') as f:
    f.write('\n'.join(lines) + '\n')
"

            # Build --preserve_io_datatype flags for all inputs
            PRESERVE_FLAGS=$($PYTHON -c "
import onnx
model = onnx.load('$seg_onnx')
inputs = [inp.name for inp in model.graph.input]
outputs = [out.name for out in model.graph.output]
# Preserve all IO datatypes to avoid batch-dim inference bug
flags = []
for name in inputs + outputs:
    flags.append('--preserve_io_datatype {}'.format(name))
print(' '.join(flags))
")

            echo "  Quantizing to int8..."
            if docker_run python3.10 /qnn/bin/x86_64-linux-clang/qairt-quantizer \
                --input_dlc "/workspace/dlc/${seg_name}.dlc" \
                --output_dlc "/workspace/dlc/${seg_name}_quantized.dlc" \
                --input_list "/workspace/calibration/${seg_name}_cal_list.txt" \
                --act_bitwidth 8 \
                --weights_bitwidth 8 \
                --bias_bitwidth 8 \
                $PRESERVE_FLAGS 2>&1 | tail -10; then
                sudo chown "$(id -u):$(id -g)" "$DLC_DIR/${seg_name}_quantized.dlc"
                echo "  Quantized: $(du -h "$DLC_DIR/${seg_name}_quantized.dlc" | cut -f1)"
            else
                echo "  QUANTIZATION FAILED for $seg_name"
            fi
        fi
        echo ""
    done
fi

# ===========================================================================
# Step 3: Convert CPU segments (fp32 only, no quantization)
# ===========================================================================
if $CONVERT; then
    echo "=== Converting CPU segments (fp32) ==="
    for seg_onnx in "$SLICES_DIR"/cpu_seg_*.onnx; do
        seg_name="$(basename "$seg_onnx" .onnx)"

        INPUT_FLAGS=$($PYTHON -c "
import onnx
model = onnx.load('$seg_onnx')
flags = []
for inp in model.graph.input:
    dims = [d.dim_value for d in inp.type.tensor_type.shape.dim]
    flags.append('-d {} {}'.format(inp.name, ','.join(str(d) for d in dims)))
    flags.append('--input_layout {} NONTRIVIAL'.format(inp.name))
print(' '.join(flags))
")

        echo "  $seg_name..."
        docker_run bash -c "\
            pip install -q 'numpy<2' && \
            python3.10 /qnn/bin/x86_64-linux-clang/snpe-onnx-to-dlc \
                --input_network /workspace/${seg_name}.onnx \
                ${INPUT_FLAGS} \
                --output_path /workspace/dlc/${seg_name}.dlc" 2>&1 | tail -3
        sudo chown "$(id -u):$(id -g)" "$DLC_DIR/${seg_name}.dlc"
    done
    echo "  Done — CPU DLCs are fp32 (no quantization needed for Tanh)."
fi

echo ""
echo "=== Build complete ==="
echo "  DSP DLCs: $DLC_DIR/dsp_seg_*.dlc"
echo "  CPU DLCs: $DLC_DIR/cpu_seg_*.dlc"
ls -lh "$DLC_DIR"/*.dlc 2>/dev/null | wc -l | xargs -I{} echo "  Total DLC files: {}"
