"""Stage multi-graph context binaries on the board for the bundle-aware
v3 runtime.

Companion to stage_v3_bundles_ctx.py, but for the multi-graph build pipeline:
each segment's ctx_bin_name in the dispatch table refers to a multi-graph
bin (produced by build_multi_graph_ctx.py and already living at
/root/multi_ctx/ on the board). This script:

  1. Reads the multi-graph manifests for each backend.
  2. For each dispatch in the schedule, figures out (ctx_bin_name on disk,
     graph_name within) for its target backend.
  3. Emits a small Bash script that symlinks /root/<CTX_DIR>/<ctx_bin_name>
     -> /root/multi_ctx/<ctx_bin_name> so the runtime's CTX_DIR lookups
     succeed.

The dispatch table already has ctx_bin_name baked in (via generate_runtime
--graph-index), so no rewriting of paths in source.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

_HERE = Path(__file__).parent
_REPO = _HERE.parent.parent


def main():
    ap = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ctx-src", default="/root/multi_ctx",
                    help="board-side dir where build_multi_graph_ctx.py wrote the bins")
    ap.add_argument("--ctx-dst", default="/root/qnn_runtime_ctx_v3",
                    help="board-side dir the runtime will look in (CTX_DIR)")
    ap.add_argument("--graph-index", action="append", required=True,
                    help="path(s) to *_graph_index.json files; pass multiple "
                         "for different backends")
    ap.add_argument("--schedule", required=True,
                    help="schedule JSON (used to determine which graphs are needed)")
    ap.add_argument("--seg-perf", default=None,
                    help="optional segment_perf.json — used to resolve synthetic "
                         "conv pseudo-names (e.g. 'dsp_seg_01_conv1') into the "
                         "actual conv-node-names inside the HTA conv DLCs.")
    ap.add_argument("--out-script", default=str(_HERE / "stage_v3_bundles_multigraph.sh"))
    args = ap.parse_args()

    # Merge graph_index files; key by (graph_name, backend_upper) -> info
    by_key: dict[tuple[str, str], dict] = {}
    for p in args.graph_index:
        with open(p) as f:
            gi = json.load(f)
        for gname, info in gi.items():
            be = info.get("backend", "").upper()
            by_key[(gname, be)] = info

    # Optional pseudo-name -> real-name map for the HTA conv slots.
    conv_resolver: dict[str, str] = {}
    if args.seg_perf:
        with open(args.seg_perf) as f:
            perf = json.load(f)
        for seg_name, data in perf.items():
            convs = data.get("Hta", {}).get("convs", [])
            for i, c in enumerate(convs):
                pseudo = f"{seg_name}_conv{i+1}"
                real = c.get("name", "")
                if real:
                    conv_resolver[pseudo] = real

    # Walk the schedule, collect the distinct (ctx_bin_name, backend) we'll
    # actually need based on dispatch routings.
    with open(args.schedule) as f:
        sched = json.load(f)
    slot_to_be = {"CPU_P": "HTA", "CPU_E": "DSP", "CPU_X": "CPU"}
    needed: dict[str, set[str]] = {}   # ctx_bin_name -> set of graph names that live in it
    missing = []
    for d in sched["dispatches"].values():
        gname = d["module_name"]
        if gname in conv_resolver:
            gname = conv_resolver[gname]
        hw = slot_to_be[d["hardware_target"].split("#")[0]]
        info = by_key.get((gname, hw))
        if info is None:
            # No multi-graph entry — fall back to single-graph (handled by
            # the legacy stage script + single-bin staging)
            missing.append((gname, hw))
            continue
        needed.setdefault(info["bin"], set()).add(gname)

    print(f"Multi-graph staging summary:")
    print(f"  needed: {len(needed)} distinct multi-graph ctx binaries")
    for bin_name, graphs in sorted(needed.items()):
        print(f"    {bin_name}: {len(graphs)} graphs ({sorted(graphs)[:3]}...)")
    if missing:
        print(f"  {len(missing)} dispatches have NO multi-graph mapping:")
        for gname, hw in missing[:8]:
            print(f"    '{gname}' @ {hw}")
        if len(missing) > 8:
            print(f"    ... ({len(missing) - 8} more)")
        print("  These will fall back to single-graph staging.")

    # Emit symlink script. We just symlink the multi-graph ctx bins into
    # the runtime's CTX_DIR. The runtime's dispatch table already specifies
    # the bin filename, so symlink target name == source name.
    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append("# Auto-generated by stage_v3_bundles_multigraph.py — do not edit.")
    lines.append("set -euo pipefail")
    lines.append(f'CTX_SRC="${{CTX_SRC:-{args.ctx_src}}}"')
    lines.append(f'CTX_DST="${{CTX_DST:-{args.ctx_dst}}}"')
    lines.append('mkdir -p "$CTX_DST"')
    lines.append('n_ok=0; n_missing=0')
    for bin_name in sorted(needed):
        lines.append(f'if [ -f "$CTX_SRC/{bin_name}" ]; then')
        lines.append(f'  ln -sf "$CTX_SRC/{bin_name}" "$CTX_DST/{bin_name}"; n_ok=$((n_ok+1))')
        lines.append(f'else')
        lines.append(f'  echo "MISSING: $CTX_SRC/{bin_name}"; n_missing=$((n_missing+1))')
        lines.append(f'fi')
    lines.append('echo "Staged $n_ok multi-graph ctx symlinks; $n_missing missing."')

    with open(args.out_script, "w") as f:
        f.write("\n".join(lines) + "\n")
    Path(args.out_script).chmod(0o755)
    print(f"\nWrote {args.out_script}")


if __name__ == "__main__":
    main()
