/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 19
#define FLOWC_N_LANES 6

static const int flowc_e5_deps[] = { 2, 0 };
static const int flowc_e7_deps[] = { 1 };
static const int flowc_e11_deps[] = { 8, 10 };
static const int flowc_e16_deps[] = { 4 };
static const int flowc_e17_deps[] = { 15, 13 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 0.000000, 0.014000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 0, 2, 6, 7 },
    { 1, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 0.000000, 13.267000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 1, 103, 0, 102 },
    { 2, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 0.000000, 0.931000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 3, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.014000, 0.107000, 0, NULL, 0, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 4, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 0.931000, 13.909000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 5, "fused_split", 0, 2, "qnn_graph", "fused_tail", "cpu", 5, 5.646000, 0.354000, 2, flowc_e5_deps, 3, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 0, 10, 4, 15 },
    { 6, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 6.000000, 0.107000, 0, NULL, 3, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 7, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 13.267000, 15.377000, 1, flowc_e7_deps, 1, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 1, 146, 103, 248 },
    { 8, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 14.840000, 0.931000, 0, NULL, 2, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 9, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 14.893000, 0.107000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 10, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 15.000000, 0.014000, 0, NULL, 9, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 0, 2, 6, 7 },
    { 11, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 15.771000, 0.354000, 2, flowc_e11_deps, 10, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 0, 10, 4, 15 },
    { 12, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 18.000000, 0.107000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 13, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 24.000000, 1.568000, 0, NULL, 8, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 2, 2, 6, 7 },
    { 14, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 24.000000, 0.107000, 0, NULL, 12, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 15, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 25.568000, 0.931000, 0, NULL, 8, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 2, 4, 0, 3 },
    { 16, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 28.644000, 15.377000, 1, flowc_e16_deps, 1, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 5, 146, 103, 248 },
    { 17, "fused_split", 2, 2, "qnn_graph", "fused_tail", "cpu", 5, 29.646000, 0.354000, 2, flowc_e17_deps, 14, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 0, 10, 4, 15 },
    { 18, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 30.000000, 0.107000, 0, NULL, 14, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "cpu|fused_split",
    "dsp|yolov8n_a",
    "hta|fused_split",
    "cpu|mlp_control",
    "hta|yolov8n_b",
    "dsp|yolov8n_b",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 5, 6, 7, 4, 7, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 192, 200, 200, 776, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 40, 0, 0, 40, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "4,5",
    "6",
    "7",
    "4,5",
    "7",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
