/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 16
#define FLOWC_N_LANES 8

static const int flowc_e3_deps[] = { 0 };
static const int flowc_e8_deps[] = { 7 };
static const int flowc_e9_deps[] = { 1 };
static const int flowc_e13_deps[] = { 12 };
static const int flowc_e15_deps[] = { 5 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "dronet_a", 0, 0, "qnn_graph", "dronet_full", "dsp", 6, 0.000000, 1.068000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 0, 24, 0, 23 },
    { 1, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 2.741000, 13.191000, 0, NULL, 0, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 1, 103, 0, 102 },
    { 2, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 2.935000, 0.065000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 2, 7, 0, 6 },
    { 3, "dronet_b", 0, 0, "qnn_graph", "dronet_full", "hta", 7, 7.213000, 1.787000, 1, flowc_e3_deps, -1, "HTA", "libQnnHta.so", "ctx_dronet_full_hta__Hta.bin", "dronet_full_hta", 1, 3, 24, 0, 23 },
    { 4, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 8.935000, 0.065000, 0, NULL, 2, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 2, 7, 0, 6 },
    { 5, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 13.262000, 13.951000, 0, NULL, 3, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 6, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 14.935000, 0.065000, 0, NULL, 4, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 2, 7, 0, 6 },
    { 7, "dronet_a", 1, 0, "qnn_graph", "dronet_full", "dsp", 6, 15.932000, 1.068000, 0, NULL, 0, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 0, 24, 0, 23 },
    { 8, "dronet_b", 1, 0, "qnn_graph", "dronet_full", "dsp", 6, 17.000000, 1.068000, 1, flowc_e8_deps, 1, "DSP", "libQnnDsp.so", "ctx_dronet_full_hta__Dsp.bin", "dronet_full_hta", 1, 5, 24, 0, 23 },
    { 9, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 18.068000, 17.468000, 1, flowc_e9_deps, 8, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 1, 146, 103, 248 },
    { 10, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 20.935000, 0.065000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 2, 7, 0, 6 },
    { 11, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 26.935000, 0.065000, 0, NULL, 10, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 2, 7, 0, 6 },
    { 12, "dronet_a", 2, 0, "qnn_graph", "dronet_full", "hta", 7, 27.213000, 1.787000, 0, NULL, 3, "HTA", "libQnnHta.so", "ctx_dronet_full_hta__Hta.bin", "dronet_full_hta", 1, 6, 24, 0, 23 },
    { 13, "dronet_b", 2, 0, "qnn_graph", "dronet_full", "hta", 7, 29.000000, 1.787000, 1, flowc_e13_deps, 12, "HTA", "libQnnHta.so", "ctx_dronet_full_hta__Hta.bin", "dronet_full_hta", 1, 3, 24, 0, 23 },
    { 14, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 32.935000, 0.065000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 2, 7, 0, 6 },
    { 15, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 35.536000, 17.468000, 1, flowc_e15_deps, 9, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 7, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "dsp|dronet_a",
    "dsp|yolov8n_b",
    "cpu|mlp_control",
    "hta|dronet_b",
    "hta|yolov8n_a",
    "dsp|dronet_b",
    "hta|dronet_a",
    "dsp|yolov8n_a",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 6, 6, 5, 7, 7, 6, 7, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 200, 1499, 200, 200, 200, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 0, 40, 0, 0, 0, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "6",
    "6",
    "4,5",
    "7",
    "7",
    "6",
    "7",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
