"""Emit CMakeLists.txt files for the generated compiler project.

Generates:
  - Top-level CMakeLists.txt (mirrors MLIR standalone example)
  - include/CMakeLists.txt (aggregates dialect includes)
  - include/{Prefix}/CMakeLists.txt (per-dialect tablegen targets)
  - lib/CMakeLists.txt (aggregates dialect libraries)
  - lib/{Prefix}/CMakeLists.txt (per-dialect library targets)
  - compgen-opt/CMakeLists.txt (optimizer driver)
"""

from __future__ import annotations

from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from compgen.extensions.mlir_cppgen.introspect import DialectInfo

_TEMPLATE_DIR = Path(__file__).parent / "templates"


def _make_env() -> Environment:
    return Environment(
        loader=FileSystemLoader(str(_TEMPLATE_DIR)),
        keep_trailing_newline=True,
        trim_blocks=True,
        lstrip_blocks=True,
    )


def emit_top_cmake(dialects: list[DialectInfo]) -> str:
    """Generate top-level CMakeLists.txt."""
    env = _make_env()
    tmpl = env.get_template("top_cmake.j2")
    return tmpl.render(dialects=dialects)


def emit_include_cmake(info: DialectInfo, *, has_passes: bool = False) -> str:
    """Generate include/{Prefix}/CMakeLists.txt with tablegen targets."""
    env = _make_env()
    tmpl = env.get_template("include_cmake.j2")
    return tmpl.render(
        prefix=info.prefix,
        dialect_name=info.name,
        has_attrs=bool(info.attrs),
        has_passes=has_passes,
    )


def emit_lib_cmake(
    info: DialectInfo,
    *,
    has_passes: bool = False,
    dep_targets: list[str] | None = None,
    dep_libs: list[str] | None = None,
) -> str:
    """Generate lib/{Prefix}/CMakeLists.txt with library target."""
    env = _make_env()
    tmpl = env.get_template("lib_cmake.j2")
    return tmpl.render(
        prefix=info.prefix,
        has_attrs=bool(info.attrs),
        has_passes=has_passes,
        dep_targets=dep_targets or [],
        dep_libs=dep_libs or [],
    )


def write_cmake_files(
    dialects: list[DialectInfo],
    output_dir: Path,
    *,
    dep_graph: dict[str, list[str]] | None = None,
    dialects_with_passes: set[str] | None = None,
) -> list[Path]:
    """Write all CMake files for the generated compiler project.

    Args:
        dialects: All dialects to include.
        output_dir: Root of the generated project.
        dep_graph: Maps dialect prefix → list of dependency prefixes.
        dialects_with_passes: Set of dialect prefixes that have passes.

    Returns:
        List of written file paths.
    """
    dep_graph = dep_graph or {}
    dialects_with_passes = dialects_with_passes or set()
    written: list[Path] = []

    # Top-level CMakeLists.txt
    top_path = output_dir / "CMakeLists.txt"
    top_path.write_text(emit_top_cmake(dialects))
    written.append(top_path)

    # include/CMakeLists.txt
    include_dir = output_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)
    include_cmake = include_dir / "CMakeLists.txt"
    lines = ["# Auto-generated by CompGen mlir_cppgen\n"]
    for d in dialects:
        lines.append(f"add_subdirectory({d.prefix})\n")
    include_cmake.write_text("".join(lines))
    written.append(include_cmake)

    # Per-dialect include CMake
    for d in dialects:
        dialect_include_dir = include_dir / d.prefix
        dialect_include_dir.mkdir(parents=True, exist_ok=True)
        path = dialect_include_dir / "CMakeLists.txt"
        has_passes = d.prefix in dialects_with_passes
        path.write_text(emit_include_cmake(d, has_passes=has_passes))
        written.append(path)

    # lib/CMakeLists.txt
    lib_dir = output_dir / "lib"
    lib_dir.mkdir(parents=True, exist_ok=True)
    lib_cmake = lib_dir / "CMakeLists.txt"
    lines = ["# Auto-generated by CompGen mlir_cppgen\n"]
    for d in dialects:
        lines.append(f"add_subdirectory({d.prefix})\n")
    lib_cmake.write_text("".join(lines))
    written.append(lib_cmake)

    # Per-dialect lib CMake
    for d in dialects:
        deps = dep_graph.get(d.prefix, [])
        dep_targets = [f"CompGen{dep}OpsIncGen" for dep in deps]
        dep_libs = [f"CompGen{dep}" for dep in deps]
        if d.attrs:
            dep_targets_full = dep_targets + [f"CompGen{dep}AttrsIncGen" for dep in deps if dep != d.prefix]
        else:
            dep_targets_full = dep_targets

        has_passes = d.prefix in dialects_with_passes
        dialect_lib_dir = lib_dir / d.prefix
        dialect_lib_dir.mkdir(parents=True, exist_ok=True)
        path = dialect_lib_dir / "CMakeLists.txt"
        path.write_text(emit_lib_cmake(
            d,
            has_passes=has_passes,
            dep_targets=dep_targets_full,
            dep_libs=dep_libs,
        ))
        written.append(path)

    # compgen-opt/CMakeLists.txt
    opt_dir = output_dir / "compgen-opt"
    opt_dir.mkdir(parents=True, exist_ok=True)
    opt_cmake = opt_dir / "CMakeLists.txt"
    lib_names = [f"CompGen{d.prefix}" for d in dialects]
    # Add pass libraries
    for d in dialects:
        if d.prefix in dialects_with_passes:
            lib_names.append(f"CompGen{d.prefix}Passes")
    opt_cmake_content = _emit_opt_cmake(lib_names)
    opt_cmake.write_text(opt_cmake_content)
    written.append(opt_cmake)

    return written


def _emit_opt_cmake(lib_names: list[str]) -> str:
    """Generate compgen-opt/CMakeLists.txt."""
    libs = "\n    ".join(lib_names)
    return f"""\
# Auto-generated by CompGen mlir_cppgen
get_property(dialect_libs GLOBAL PROPERTY MLIR_DIALECT_LIBS)
get_property(conversion_libs GLOBAL PROPERTY MLIR_CONVERSION_LIBS)

set(LIBS
    ${{dialect_libs}}
    ${{conversion_libs}}
    {libs}
    MLIROptLib
    MLIRIR
    MLIRPass
    MLIRSupport
)

add_llvm_executable(compgen-opt compgen-opt.cpp)
llvm_update_compile_flags(compgen-opt)
target_link_libraries(compgen-opt PRIVATE ${{LIBS}})
mlir_check_all_link_libraries(compgen-opt)
"""


__all__ = [
    "emit_include_cmake",
    "emit_lib_cmake",
    "emit_top_cmake",
    "write_cmake_files",
]
