"""Generate MLIR roundtrip test files for the generated compiler.

Produces ``.mlir`` files with FileCheck directives that verify:
1. Dialect ops can be parsed by compgen-opt
2. Parsed ops can be reprinted identically (roundtrip)
3. Each pass produces expected attribute annotations

Test files go in ``test/{Dialect}/`` in the generated project.
"""

from __future__ import annotations

from pathlib import Path

from compgen.extensions.mlir_cppgen.introspect import DialectInfo, OpInfo
from compgen.extensions.mlir_cppgen.pass_emitter import PassInfo


def _op_test_body(info: DialectInfo, op: OpInfo) -> str:
    """Generate a test snippet for one op."""
    lines = []
    lines.append(f"// CHECK: {info.name}.{op.mnemonic}")

    # Build a minimal op with required properties
    props = []
    for p in op.properties:
        if p.is_optional:
            continue
        if p.tablegen_type == "StrAttr":
            props.append(f'{p.name} = "test"')
        elif p.tablegen_type == "I64Attr":
            props.append(f"{p.name} = 0 : i64")
        elif p.tablegen_type == "FlatSymbolRefAttr":
            props.append(f"{p.name} = @test_ref")
        elif p.tablegen_type == "ArrayAttr":
            props.append(f"{p.name} = []")
        elif "Attr" in p.tablegen_type:
            # Custom attr — use generic syntax
            props.append(f'{p.name} = "default"')

    props_str = ", ".join(props)
    if props_str:
        props_str = " {" + props_str + "}"

    lines.append(f'"{info.name}.{op.mnemonic}"(){props_str} : () -> ()')
    return "\n".join(lines)


def emit_roundtrip_test(info: DialectInfo) -> str:
    """Generate a roundtrip .mlir test file for a dialect.

    The test parses MLIR through compgen-opt and checks that all ops
    survive the roundtrip.
    """
    lines = [
        "// RUN: compgen-opt %s | compgen-opt | FileCheck %s",
        f"// Roundtrip test for {info.name} dialect ({len(info.ops)} ops)",
        "",
    ]

    for op in info.ops:
        lines.append(f"// --- {op.class_name} ---")
        lines.append(_op_test_body(info, op))
        lines.append("")

    return "\n".join(lines)


def emit_pass_test(p: PassInfo) -> str:
    """Generate a .mlir test file for a single pass.

    Tests that running the pass annotates ops with expected attributes.
    """
    lines = [
        f"// RUN: compgen-opt --{p.pass_flag} %s | FileCheck %s",
        f"// Test for pass: {p.pass_flag}",
        f"// Type: {p.pattern}",
        "",
        "module {",
        "  func.func @test() {",
        "    return",
        "  }",
        "}",
        "",
    ]

    if p.pattern == "attr_annotation":
        lines.append("// CHECK: func.func @test")
    elif p.pattern == "structural":
        lines.append("// CHECK: module")

    return "\n".join(lines)


def write_test_files(
    dialects: list[DialectInfo],
    passes: list[PassInfo] | None,
    output_dir: Path,
) -> list[Path]:
    """Write all MLIR test files to the generated project.

    Args:
        dialects: Dialects to generate roundtrip tests for.
        passes: Passes to generate pass tests for.
        output_dir: Root of the generated project.

    Returns:
        List of written file paths.
    """
    test_dir = output_dir / "test"
    test_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    # Per-dialect roundtrip tests
    for info in dialects:
        if not info.ops:
            continue
        dialect_test_dir = test_dir / info.prefix
        dialect_test_dir.mkdir(parents=True, exist_ok=True)

        path = dialect_test_dir / "roundtrip.mlir"
        path.write_text(emit_roundtrip_test(info))
        written.append(path)

    # Per-pass tests
    if passes:
        pass_test_dir = test_dir / "Passes"
        pass_test_dir.mkdir(parents=True, exist_ok=True)

        for p in passes:
            path = pass_test_dir / f"{p.name}.mlir"
            path.write_text(emit_pass_test(p))
            written.append(path)

    # lit.cfg.py
    lit_cfg = test_dir / "lit.cfg.py"
    lit_cfg.write_text(_emit_lit_cfg())
    written.append(lit_cfg)

    return written


def _emit_lit_cfg() -> str:
    """Generate lit.cfg.py for the test suite."""
    return """\
# -*- Python -*-
# Auto-generated by CompGen mlir_cppgen

import os
import lit.formats

config.name = "CompGen"
config.test_format = lit.formats.ShTest(not llvm_config.use_lit_shell)
config.suffixes = [".mlir"]
config.test_source_root = os.path.dirname(__file__)

# Add compgen-opt to the PATH
tool_dirs = [config.llvm_tools_dir]
tools = ["compgen-opt"]
llvm_config.add_tool_substitutions(tools, tool_dirs)
"""


__all__ = [
    "emit_pass_test",
    "emit_roundtrip_test",
    "write_test_files",
]
