#!/usr/bin/env python
"""Render docs/generated/pass_cards/INDEX.md from the registry (M-33.6).

Walks every card under ``default_registry_root()`` and emits a
human-readable index grouped by family + level. The index is the
single navigable surface for the agent and for human reviewers.

Usage::

    uv run python scripts/dev/render_pass_card_index.py

Exit 0 on success. Writes ``docs/generated/pass_cards/INDEX.md``.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

from compgen.passes import (
    PassCardRegistry,
    default_registry_root,
)


def _utc_now() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def render_index(*, root: Path | None = None) -> str:
    """Return the rendered INDEX.md content."""
    root = root or default_registry_root()
    registry = PassCardRegistry.load(root)

    by_family: dict[str, list] = defaultdict(list)
    by_source: dict[str, list[str]] = defaultdict(list)
    by_level: dict[str, list[str]] = defaultdict(list)
    for card in registry:
        by_family[card.family].append(card)
        by_source[card.source or "(unspecified)"].append(card.pass_id)
        by_level[card.level].append(card.pass_id)

    lines: list[str] = []
    lines.append("# CompGen pass card index")
    lines.append("")
    lines.append(f"_Generated: `{_utc_now()}`_")
    lines.append("")
    lines.append(f"**{len(registry)} cards** across {len(by_family)} families.")
    lines.append("")
    lines.append("This file is auto-generated by ")
    lines.append("`scripts/dev/render_pass_card_index.py`. Do not hand-edit.")
    lines.append("")
    lines.append("## At a glance")
    lines.append("")
    lines.append("| Family | Count | Levels |")
    lines.append("| --- | --- | --- |")
    for family in sorted(by_family):
        cards = by_family[family]
        levels = sorted({c.level for c in cards})
        lines.append(f"| `{family}` | {len(cards)} | {', '.join(levels)} |")
    lines.append("")
    lines.append("## By source / provenance")
    lines.append("")
    lines.append("| Source | Count | Pass IDs |")
    lines.append("| --- | --- | --- |")
    for source in sorted(by_source):
        ids = sorted(by_source[source])
        rendered_ids = ", ".join(f"`{i}`" for i in ids[:5])
        if len(ids) > 5:
            rendered_ids += f" (+{len(ids) - 5} more)"
        lines.append(f"| {source} | {len(ids)} | {rendered_ids} |")
    lines.append("")
    lines.append("## Cards by family")
    lines.append("")
    for family in sorted(by_family):
        cards = sorted(by_family[family], key=lambda c: c.pass_id)
        lines.append(f"### {family}")
        lines.append("")
        lines.append("| Pass ID | Level | Source | Refinement | Cost |")
        lines.append("| --- | --- | --- | --- | --- |")
        for card in cards:
            source = card.source or "(unspecified)"
            lines.append(
                f"| `{card.pass_id}` | {card.level} | {source} | "
                f"{card.preserves_refinement} | {card.cost} |"
            )
        lines.append("")
    lines.append("## Coverage notes")
    lines.append("")
    no_source = [c for c in registry if not c.source]
    no_impl_path = [c for c in registry if not c.impl_path]
    lines.append(
        f"- {len(no_source)} card(s) have no `source` declaration. "
        "Every card must declare provenance for the realness audit."
    )
    lines.append(
        f"- {len(no_impl_path)} card(s) have no `impl_path` declaration."
    )
    lines.append("")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--root", type=Path, default=None,
        help="Override the registry root (default: package-resolved)",
    )
    p.add_argument(
        "--out", type=Path, default=None,
        help="Override the output path (default: <root>/INDEX.md)",
    )
    args = p.parse_args(argv)

    root = args.root or default_registry_root()
    out = args.out or (root / "INDEX.md")
    rendered = render_index(root=root)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(rendered, encoding="utf-8")
    print(f"wrote {out} ({len(rendered)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
