/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 40
#define FLOWC_N_LANES 15

static const int flowc_e6_deps[] = { 0, 1 };
static const int flowc_e9_deps[] = { 4 };
static const int flowc_e11_deps[] = { 8, 10 };
static const int flowc_e18_deps[] = { 14, 16 };
static const int flowc_e19_deps[] = { 12 };
static const int flowc_e21_deps[] = { 2 };
static const int flowc_e26_deps[] = { 22, 25 };
static const int flowc_e31_deps[] = { 28, 29 };
static const int flowc_e33_deps[] = { 23 };
static const int flowc_e38_deps[] = { 17 };
static const int flowc_e39_deps[] = { 34, 35 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 0.000000, 0.931000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 1, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 0.000000, 0.014000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 2, "vint", 0, 0, "qnn_graph", "vint_encoders", "dsp", 6, 0.000000, 14.213000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_vint_encoders__Dsp.bin", "vint_encoders", 1, 2, 539, 0, 538 },
    { 3, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.014000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 4, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 0.931000, 13.909000, 0, NULL, 0, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 5, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 7.000000, 0.107000, 0, NULL, 3, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 6, "fused_split", 0, 2, "qnn_graph", "fused_tail", "cpu", 5, 10.646000, 0.354000, 2, flowc_e6_deps, 5, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 7, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 14.000000, 0.107000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 8, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 14.840000, 0.931000, 0, NULL, 0, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 9, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 14.840000, 15.377000, 1, flowc_e9_deps, 2, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 5, 146, 103, 248 },
    { 10, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 15.757000, 0.014000, 0, NULL, 7, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 11, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 15.771000, 0.354000, 2, flowc_e11_deps, 10, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 12, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 15.771000, 13.909000, 0, NULL, 8, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 6, 103, 0, 102 },
    { 13, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 21.000000, 0.107000, 0, NULL, 11, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 14, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 29.680000, 0.931000, 0, NULL, 8, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 15, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 30.217000, 0.589000, 0, NULL, 2, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 7, 7, 0, 6 },
    { 16, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 30.597000, 0.014000, 0, NULL, 13, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 17, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 30.611000, 13.909000, 0, NULL, 12, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 8, 103, 0, 102 },
    { 18, "fused_split", 2, 2, "qnn_graph", "fused_tail", "cpu", 5, 30.611000, 0.354000, 2, flowc_e18_deps, 16, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 19, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 30.806000, 15.377000, 1, flowc_e19_deps, 9, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 9, 146, 103, 248 },
    { 20, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 35.000000, 0.107000, 0, NULL, 18, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 21, "vint", 0, 1, "qnn_graph", "vint_decoder", "cpu", 5, 35.107000, 37.826000, 1, flowc_e21_deps, 20, "CPU", "libQnnCpu.so", "ctx_vint_decoder_fp32__Cpu.bin", "vint_decoder", 0, 10, 66, 539, 604 },
    { 22, "fused_split", 3, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 44.520000, 0.931000, 0, NULL, 14, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 23, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 45.451000, 13.909000, 0, NULL, 22, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 11, 103, 0, 102 },
    { 24, "mlp_control", 6, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 46.183000, 0.589000, 0, NULL, 19, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 7, 7, 0, 6 },
    { 25, "fused_split", 3, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 46.772000, 0.392000, 0, NULL, 19, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 12, 2, 6, 7 },
    { 26, "fused_split", 3, 2, "qnn_graph", "fused_tail", "dsp", 6, 47.164000, 4.303000, 2, flowc_e26_deps, 24, "DSP", "libQnnDsp.so", "ctx_fused_tail_from_conv__Dsp.bin", "fused_tail_from_conv", 1, 12, 10, 4, 15 },
    { 27, "mlp_control", 7, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 51.467000, 0.589000, 0, NULL, 26, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 7, 7, 0, 6 },
    { 28, "fused_split", 4, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 56.000000, 0.459000, 0, NULL, 27, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 12, 4, 0, 3 },
    { 29, "fused_split", 4, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 56.459000, 0.392000, 0, NULL, 28, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 12, 2, 6, 7 },
    { 30, "mlp_control", 8, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 58.108000, 0.589000, 0, NULL, 29, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 7, 7, 0, 6 },
    { 31, "fused_split", 4, 2, "qnn_graph", "fused_tail", "dsp", 6, 58.697000, 4.303000, 2, flowc_e31_deps, 30, "DSP", "libQnnDsp.so", "ctx_fused_tail_from_conv__Dsp.bin", "fused_tail_from_conv", 1, 12, 10, 4, 15 },
    { 32, "mlp_control", 9, 0, "qnn_graph", "mlp_control_full", "dsp", 6, 63.000000, 0.589000, 0, NULL, 31, "DSP", "libQnnDsp.so", "ctx_mlp_control__Dsp.bin", "mlp_control", 1, 7, 7, 0, 6 },
    { 33, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 63.589000, 15.377000, 1, flowc_e33_deps, 31, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 13, 146, 103, 248 },
    { 34, "fused_split", 5, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 70.000000, 0.931000, 0, NULL, 23, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 35, "fused_split", 5, 1, "qnn_graph", "fused_depth_conv", "hta", 7, 70.931000, 1.568000, 0, NULL, 34, "HTA", "libQnnHta.so", "ctx_fused_depth_conv__Hta.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 36, "mlp_control", 10, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 72.933000, 0.107000, 0, NULL, 20, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 37, "mlp_control", 11, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 77.000000, 0.107000, 0, NULL, 36, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 38, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 78.966000, 15.377000, 1, flowc_e38_deps, 32, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 14, 146, 103, 248 },
    { 39, "fused_split", 5, 2, "qnn_graph", "fused_tail", "cpu", 5, 80.646000, 0.354000, 2, flowc_e39_deps, 37, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "hta|fused_split",
    "cpu|fused_split",
    "dsp|vint",
    "cpu|mlp_control",
    "hta|yolov8n_b",
    "dsp|yolov8n_b",
    "hta|yolov8n_c",
    "dsp|mlp_control",
    "hta|yolov8n_a",
    "dsp|yolov8n_c",
    "cpu|vint",
    "hta|yolov8n_d",
    "dsp|fused_split",
    "dsp|yolov8n_d",
    "dsp|yolov8n_a",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 7, 5, 6, 4, 7, 6, 7, 6, 7, 6, 5, 7, 6, 6, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 3, 200, 1016, 200, 200, 200, 200, 200, 200, 2000, 200, 97, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 40, 0, 40, 0, 0, 0, 0, 0, 0, 40, 0, 0, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "7",
    "4,5",
    "6",
    "4,5",
    "7",
    "6",
    "7",
    "6",
    "7",
    "6",
    "4,5",
    "7",
    "6",
    "6",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
