/* @generated by qnn_models/flow_c/flowc/emit_runtime.py — do not edit. */
#pragma once
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* The first block is field-for-field modelblaster's xpurt_sched_entry_t
 * (pipeline/ingest_xpurt_schedule.py) so a reader of one table can read
 * the other; the second block is what a QNN dispatch additionally needs. */
typedef struct {
    int          entry_id;
    const char  *network;
    int          instance;
    int          dispatch_id;      /* binding id == coarse-IR dispatch_id */
    const char  *op;               /* IR op kind: always "qnn_graph" here */
    const char  *name;             /* binding name */
    const char  *core_kind;        /* registry kind: hta / dsp / cpu */
    int          hart;             /* host core this lane pins to */
    double       start_time_ms;
    double       duration_ms;
    int          n_deps;
    const int   *deps;
    int          time_dep_entry_id;
    /* ---- Flow C ---- */
    const char  *backend_label;    /* HTA / DSP / CPU — profile-side label */
    const char  *backend_lib;      /* libQnn*.so to dlopen */
    const char  *ctx;              /* context binary filename */
    const char  *graph;            /* graph inside that context */
    int          exec_serialized;  /* backend needs a process-wide exec lock */
    int          lane;             /* worker lane index */
    int          n_ir_ops;         /* IR ops this tile covers */
    int          ir_first;
    int          ir_last;
} flowc_sched_entry_t;

#define FLOWC_N_ENTRIES 35
#define FLOWC_N_LANES 13

static const int flowc_e6_deps[] = { 0, 1 };
static const int flowc_e12_deps[] = { 9, 8 };
static const int flowc_e15_deps[] = { 2 };
static const int flowc_e17_deps[] = { 13, 14 };
static const int flowc_e23_deps[] = { 21, 22 };
static const int flowc_e24_deps[] = { 10 };
static const int flowc_e29_deps[] = { 27, 28 };
static const int flowc_e31_deps[] = { 19 };
static const int flowc_e32_deps[] = { 4 };
static const int flowc_e34_deps[] = { 33 };

static const flowc_sched_entry_t FLOWC_TABLE[FLOWC_N_ENTRIES] = {
    { 0, "fused_split", 0, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 0.000000, 0.459000, 0, NULL, -1, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 1, "fused_split", 0, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 0.000000, 0.014000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 2, "yolov8n_e", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 0.000000, 13.909000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 2, 103, 0, 102 },
    { 3, "mlp_control", 0, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 0.014000, 0.107000, 0, NULL, -1, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 4, "yolov8n_c", 0, 0, "qnn_graph", "yolov8n_backbone", "dsp", 6, 0.459000, 13.267000, 0, NULL, 0, "DSP", "libQnnDsp.so", "ctx_yolov8n_backbone__Dsp.bin", "yolov8n_HTA_split_seg100", 1, 4, 103, 0, 102 },
    { 5, "mlp_control", 1, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 5.000000, 0.107000, 0, NULL, 3, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 6, "fused_split", 0, 2, "qnn_graph", "fused_tail", "cpu", 5, 6.646000, 0.354000, 2, flowc_e6_deps, 5, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 7, "mlp_control", 2, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 10.000000, 0.107000, 0, NULL, 6, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 8, "fused_split", 1, 1, "qnn_graph", "fused_depth_conv", "dsp", 6, 13.726000, 0.392000, 0, NULL, 4, "DSP", "libQnnDsp.so", "ctx_fused_depth_conv__Dsp.bin", "fused_depth_conv", 1, 0, 2, 6, 7 },
    { 9, "fused_split", 1, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 13.909000, 0.931000, 0, NULL, -1, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 5, 4, 0, 3 },
    { 10, "yolov8n_d", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 14.840000, 13.909000, 0, NULL, 9, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 6, 103, 0, 102 },
    { 11, "mlp_control", 3, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 15.000000, 0.107000, 0, NULL, 7, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 12, "fused_split", 1, 2, "qnn_graph", "fused_tail", "cpu", 5, 16.646000, 0.354000, 2, flowc_e12_deps, 11, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 13, "fused_split", 2, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 20.000000, 0.459000, 0, NULL, 8, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 14, "fused_split", 2, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 20.000000, 0.014000, 0, NULL, 12, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 15, "yolov8n_e", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 20.810000, 15.377000, 1, flowc_e15_deps, 13, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 7, 146, 103, 248 },
    { 16, "mlp_control", 4, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 22.893000, 0.107000, 0, NULL, 14, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 17, "fused_split", 2, 2, "qnn_graph", "fused_tail", "cpu", 5, 23.000000, 0.354000, 2, flowc_e17_deps, 16, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 18, "mlp_control", 5, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 25.000000, 0.107000, 0, NULL, 17, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 19, "yolov8n_b", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 28.749000, 13.909000, 0, NULL, 9, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 8, 103, 0, 102 },
    { 20, "mlp_control", 6, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 32.893000, 0.107000, 0, NULL, 18, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 21, "fused_split", 3, 0, "qnn_graph", "fused_vision_conv", "dsp", 6, 36.187000, 0.459000, 0, NULL, 13, "DSP", "libQnnDsp.so", "ctx_fused_vision_conv__Dsp.bin", "fused_vision_conv", 1, 0, 4, 0, 3 },
    { 22, "fused_split", 3, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 36.632000, 0.014000, 0, NULL, 20, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 23, "fused_split", 3, 2, "qnn_graph", "fused_tail", "cpu", 5, 36.646000, 0.354000, 2, flowc_e23_deps, 20, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 24, "yolov8n_d", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 36.646000, 15.377000, 1, flowc_e24_deps, 21, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 9, 146, 103, 248 },
    { 25, "mlp_control", 7, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 37.000000, 0.107000, 0, NULL, 23, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 26, "mlp_control", 8, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 40.000000, 0.107000, 0, NULL, 25, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 27, "fused_split", 4, 0, "qnn_graph", "fused_vision_conv", "hta", 7, 42.658000, 0.931000, 0, NULL, 10, "HTA", "libQnnHta.so", "ctx_fused_vision_conv__Hta.bin", "fused_vision_conv", 1, 5, 4, 0, 3 },
    { 28, "fused_split", 4, 1, "qnn_graph", "fused_depth_conv", "cpu", 5, 43.575000, 0.014000, 0, NULL, 26, "CPU", "libQnnCpu.so", "ctx_fused_depth_conv__Cpu.bin", "fused_depth_conv", 0, 1, 2, 6, 7 },
    { 29, "fused_split", 4, 2, "qnn_graph", "fused_tail", "cpu", 5, 43.589000, 0.354000, 2, flowc_e29_deps, 26, "CPU", "libQnnCpu.so", "ctx_fused_tail_from_conv_fp32__Cpu.bin", "fused_tail_from_conv", 0, 1, 10, 4, 15 },
    { 30, "mlp_control", 9, 0, "qnn_graph", "mlp_control_full", "cpu", 5, 45.000000, 0.107000, 0, NULL, 29, "CPU", "libQnnCpu.so", "ctx_mlp_control_fp32__Cpu.bin", "mlp_control_fp32", 0, 3, 7, 0, 6 },
    { 31, "yolov8n_b", 0, 1, "qnn_graph", "yolov8n_head", "cpu", 5, 45.107000, 39.464000, 1, flowc_e31_deps, 29, "CPU", "libQnnCpu.so", "ctx_yolov8n_head__Cpu.bin", "yolov8n_HTA_split_seg101", 0, 10, 146, 103, 248 },
    { 32, "yolov8n_c", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 52.023000, 15.377000, 1, flowc_e32_deps, 21, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 4, 146, 103, 248 },
    { 33, "yolov8n_a", 0, 0, "qnn_graph", "yolov8n_backbone", "hta", 7, 53.491000, 13.909000, 0, NULL, 27, "HTA", "libQnnHta.so", "ctx_yolov8n_backbone__Hta.bin", "yolov8n_HTA_split_seg100", 1, 11, 103, 0, 102 },
    { 34, "yolov8n_a", 0, 1, "qnn_graph", "yolov8n_head", "dsp", 6, 67.400000, 15.377000, 1, flowc_e34_deps, 24, "DSP", "libQnnDsp.so", "ctx_yolov8n_head__Dsp.bin", "yolov8n_HTA_split_seg101", 1, 12, 146, 103, 248 },
};

static const char *const FLOWC_LANE_NAME[FLOWC_N_LANES] = {
    "dsp|fused_split",
    "cpu|fused_split",
    "hta|yolov8n_e",
    "cpu|mlp_control",
    "dsp|yolov8n_c",
    "hta|fused_split",
    "hta|yolov8n_d",
    "dsp|yolov8n_e",
    "hta|yolov8n_b",
    "dsp|yolov8n_d",
    "cpu|yolov8n_b",
    "hta|yolov8n_a",
    "dsp|yolov8n_a",
};
static const int FLOWC_LANE_HART[FLOWC_N_LANES] = { 6, 5, 7, 4, 6, 7, 7, 6, 7, 6, 5, 7, 6 };
/* Spin-before-deadline budget per lane. The registry's
 * qnn.gate_spin_us, capped at a quarter of the lane's own minimum
 * inter-entry gap: a lane whose period equals its spin window spins
 * essentially continuously, which is fine while it owns its core and
 * ruinous once another lane's compute shares the cluster. */
static const long FLOWC_LANE_SPIN_US[FLOWC_N_LANES] = { 200, 3, 200, 526, 200, 200, 200, 200, 200, 200, 2000, 200, 200 };
/* SCHED_FIFO priority per lane (0 = leave the lane on SCHED_OTHER), from the registry's qnn.sched_fifo_prio. */
static const int FLOWC_LANE_FIFO[FLOWC_N_LANES] = { 0, 40, 0, 40, 0, 0, 0, 0, 0, 0, 40, 0, 0 };
/* Cores the backend's own threads may use during execute, from
 * the registry's qnn.exec_cores. Empty string = the whole machine. */
static const char *const FLOWC_LANE_EXEC_CORES[FLOWC_N_LANES] = {
    "6",
    "4,5",
    "7",
    "4,5",
    "6",
    "7",
    "7",
    "6",
    "7",
    "6",
    "4,5",
    "7",
    "6",
};

#ifdef __cplusplus
}  /* extern "C" */
#endif
